"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {authClient} from "../../lib/auth/client";
type Profile={id:string;nickname:string;age_band:string;consent_at:string};
type Progress={game_key:string;completed:boolean;score:number;updated_at:string};
const ageLabels={en:{"under-8":"Under 8","8-12":"8–12","13-17":"13–17"},ar:{"under-8":"أقل من ٨","8-12":"٨–١٢","13-17":"١٣–١٧"}};
const copy={
 en:{space:"FAMILY SPACE",loginTitle:"A calmer way to support learning.",loginP:"Sign in to create an optional learning profile for your child. We save a nickname, age band and learning progress only — no public profile, ranking or weight target.",login:"SIGN IN TO CONTINUE →",family:"Your family space.",create:"Create a learning profile.",intro:"Learning progress stays private to your account. This is an educational profile, not a medical record or treatment tracker.",nick:"Nickname",nickPh:"Example: Noor",age:"Age band",consent:"I am the parent or guardian and I agree to save this limited learning profile.",saving:"Saving…",save:"Save profile",remove:"Delete child profile",progress:"LEARNING PROGRESS",complete:"Complete",ongoing:"In progress",points:"points",back:"BACK TO ILAMA BLOOM ←",loadFail:"We couldn't load the family space.",saved:"Family profile saved.",saveFail:"We couldn't save the profile.",removed:"Child profile deleted.",switch:"عربي"},
 ar:{space:"مساحة الأهل",loginTitle:"طريقة أهدى لدعم التعلّم.",loginP:"سجّل الدخول لإنشاء ملف تعلّم اختياري للطفل. نحفظ اسمًا مستعارًا، والفئة العمرية، والتقدم التعليمي فقط — من غير ملف عام أو ترتيب أو هدف وزن.",login:"دخول للمتابعة ←",family:"مساحة عائلتك.",create:"أنشئ ملف تعلّم.",intro:"التقدم التعليمي يظل خاصًا بحسابك. هذا ملف تعليمي، وليس سجلًا طبيًا أو متابعًا للعلاج.",nick:"اسم مستعار",nickPh:"مثال: نور",age:"الفئة العمرية",consent:"أنا ولي الأمر وأوافق على حفظ ملف التعلّم المحدود ده.",saving:"جارٍ الحفظ…",save:"احفظ الملف",remove:"احذف ملف الطفل",progress:"التقدم التعليمي",complete:"مكتمل",ongoing:"قيد التقدم",points:"نقطة",back:"العودة إلى Ilama Bloom ←",loadFail:"تعذر تحميل مساحة العائلة.",saved:"تم حفظ ملف العائلة.",saveFail:"تعذر حفظ الملف.",removed:"تم حذف ملف الطفل.",switch:"EN"}
};
export default function ParentPage(){
 const{data:session}=authClient.useSession();const[lang,setLang]=useState<"ar"|"en">("en");const t=copy[lang];
 const[profile,setProfile]=useState<Profile|null>(null),[progress,setProgress]=useState<Progress[]>([]),[nickname,setNickname]=useState(""),[ageBand,setAgeBand]=useState("8-12"),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const queryLang=new URLSearchParams(window.location.search).get("lang");const storedLang=localStorage.getItem("ilama-bloom-lang");const saved=queryLang==="ar"||queryLang==="en"?queryLang:(storedLang==="ar"||storedLang==="en"?storedLang:"en");setLang(saved);localStorage.setItem("ilama-bloom-lang",saved);if(!session)return;Promise.all([fetch("/api/child-profile").then(async r=>{if(!r.ok)throw new Error("profile");return r.json()}),fetch("/api/progress").then(async r=>{if(!r.ok)throw new Error("progress");return r.json()})]).then(([p,g])=>{const next=p?.profiles?.[0];if(next){setProfile(next);setNickname(next.nickname);setAgeBand(next.age_band);setConsent(true)}if(Array.isArray(g?.progress))setProgress(g.progress)}).catch(()=>setMessage(copy[saved==="ar"?"ar":"en"].loadFail))},[session]);
 const toggle=()=>{const n=lang==="en"?"ar":"en";setLang(n);localStorage.setItem("ilama-bloom-lang",n);const url=new URL(window.location.href);url.searchParams.set("lang",n);window.history.replaceState({},"",url)};
 if(!session)return <main className="parentPage" dir={lang==="ar"?"rtl":"ltr"} lang={lang}><section className="parentCard"><div className="privacyTop"><Link href="/" className="authBrand">ILAMA <span>BLOOM</span></Link><button type="button" className="authLang" onClick={toggle}>{t.switch}</button></div><small>{t.space}</small><h1>{t.loginTitle}</h1><p>{t.loginP}</p><Link className="parentPrimary" href={`/auth/sign-in?next=%2Fparent&lang=${lang}`}>{t.login}</Link></section></main>;
 const save=async()=>{setBusy(true);setMessage("");try{const r=await fetch("/api/child-profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({nickname:nickname.trim(),ageBand,consent})});const data=await r.json().catch(()=>null);if(!r.ok||!data?.profile)throw new Error(data?.error||"save failed");setProfile(data.profile);setNickname(data.profile.nickname);setMessage(t.saved)}catch(error){setMessage(error instanceof Error&&error.message!=="save failed"?error.message:t.saveFail)}finally{setBusy(false)}};
 const remove=async()=>{setBusy(true);setMessage("");try{const r=await fetch("/api/child-profile",{method:"DELETE"});if(!r.ok)throw new Error("delete failed");setProfile(null);setNickname("");setConsent(false);setMessage(t.removed)}catch{setMessage(t.saveFail)}finally{setBusy(false)}};
 return <main className="parentPage" dir={lang==="ar"?"rtl":"ltr"} lang={lang}><section className="parentCard"><div className="privacyTop"><Link href="/" className="authBrand">ILAMA <span>BLOOM</span></Link><button type="button" className="authLang" onClick={toggle}>{t.switch}</button></div><small>{t.space}</small><h1>{profile?t.family:t.create}</h1><p>{t.intro}</p><div className="parentForm"><label>{t.nick}<input maxLength={40} value={nickname} onChange={e=>setNickname(e.target.value)} placeholder={t.nickPh}/></label><label>{t.age}<select value={ageBand} onChange={e=>setAgeBand(e.target.value)}>{Object.entries(ageLabels[lang]).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="consentRow"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{t.consent}</span></label><button type="button" className="parentPrimary" disabled={busy||!nickname.trim()||!consent} onClick={save}>{busy?t.saving:t.save}</button>{profile&&<button type="button" className="parentDanger" disabled={busy} onClick={remove}>{t.remove}</button>}<p className="parentMessage" aria-live="polite">{message}</p></div>{progress.length>0&&<section className="progressPanel"><small>{t.progress}</small>{progress.map(item=><div key={item.game_key}><b>{item.game_key}</b><span>{item.completed?t.complete:t.ongoing} · {item.score} {t.points}</span></div>)}</section>}<Link href="/" className="parentBack">{t.back}</Link></section></main>
}
