"use client";
import {FormEvent,useEffect,useState} from "react";
import {authClient} from "../../lib/auth/client";


const copy={
 ar:{signIn:{title:"تسجيل الدخول",description:"أدخل بريدك الإلكتروني للمتابعة إلى حسابك.",action:"دخول"},signUp:{title:"إنشاء حساب",description:"أنشئ حسابًا لحفظ يومياتك وبياناتك بأمان.",action:"إنشاء حساب"},name:"الاسم",namePh:"اسمك",email:"البريد الإلكتروني",password:"كلمة المرور",passwordPh:"8 أحرف على الأقل",busy:"جارٍ التنفيذ…",social:"أو تابع باستخدام",existing:"لديك حساب بالفعل؟ سجّل الدخول",newAccount:"ليس لديك حساب؟ أنشئ حسابًا",invalid:"هذه الصفحة غير متاحة حاليًا. استخدم تسجيل الدخول أو إنشاء حساب.",error:"تعذر تنفيذ الطلب. حاول مرة أخرى.",socialError:"تعذر بدء تسجيل الدخول.",lang:"EN"},
 en:{signIn:{title:"Sign in",description:"Enter your email to continue to your account.",action:"Sign in"},signUp:{title:"Create account",description:"Create an account to keep your journal and saved details together.",action:"Create account"},name:"Name",namePh:"Your name",email:"Email",password:"Password",passwordPh:"At least 8 characters",busy:"Working…",social:"Or continue with",existing:"Already have an account? Sign in",newAccount:"New here? Create an account",invalid:"This page is not available. Use sign in or create an account.",error:"We couldn't complete that request. Please try again.",socialError:"We couldn't start sign in.",lang:"عربي"}
};


export function AuthClient({path}:{path:string}){
 const {data:session}=authClient.useSession();const [lang,setLang]=useState<"ar"|"en">("en");const t=copy[lang];
 const signUp=path.includes("sign-up");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [name,setName]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const [next,setNext]=useState("/");useEffect(()=>{const rawNext=new URLSearchParams(window.location.search).get("next");setNext(rawNext&&rawNext.startsWith("/")&&!rawNext.startsWith("//")?rawNext:"/")},[]);
 useEffect(()=>{const queryLang=new URLSearchParams(window.location.search).get("lang");const storedLang=localStorage.getItem("ilama-bloom-lang");const saved=queryLang==="ar"||queryLang==="en"?queryLang:(storedLang==="ar"||storedLang==="en"?storedLang:"en");setLang(saved);localStorage.setItem("ilama-bloom-lang",saved);if(session)window.location.replace(next)},[session,next]);
 const changeLang=()=>{const n=lang==="en"?"ar":"en";setLang(n);localStorage.setItem("ilama-bloom-lang",n);const url=new URL(window.location.href);url.searchParams.set("lang",n);window.history.replaceState({},"",url)};
 if(!path.includes("sign-in")&&!signUp)return <p className="authNotice" dir={lang==="ar"?"rtl":"ltr"}>{t.invalid}</p>;
 const submit=async(event:FormEvent)=>{event.preventDefault();if(busy)return;setMessage("");setBusy(true);try{const result=signUp?await authClient.signUp.email({name:name.trim()||email.split("@")[0],email:email.trim(),password,callbackURL:next}):await authClient.signIn.email({email:email.trim(),password,callbackURL:next});if(result.error)setMessage(result.error.message||t.error)}catch{setMessage(t.error)}finally{setBusy(false)}};
 const social=async(provider:"google"|"facebook"|"twitter")=>{if(busy)return;setMessage("");setBusy(true);try{const result=await authClient.signIn.social({provider,callbackURL:next});if(result.error){setMessage(result.error.message||t.socialError);setBusy(false)}}catch{setMessage(t.socialError);setBusy(false)}};
 const mode=signUp?t.signUp:t.signIn;
 const switchHref=`${signUp?"/auth/sign-in":"/auth/sign-up"}?lang=${lang}`;
 return <div className="authForm" dir={lang==="ar"?"rtl":"ltr"} lang={lang} aria-busy={busy}><button className="authLang" type="button" onClick={changeLang}>{t.lang}</button><h1>{mode.title}</h1><p>{mode.description}</p><form onSubmit={submit}>{signUp&&<label>{t.name}<input value={name} onChange={e=>setName(e.target.value)} placeholder={t.namePh} autoComplete="name"/></label>}<label>{t.email}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com" autoComplete="email"/></label><label>{t.password}<input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder={t.passwordPh} autoComplete={signUp?"new-password":"current-password"}/></label><button type="submit" disabled={busy}>{busy?t.busy:mode.action}</button></form><div className="authSocial"><span>{t.social}</span><div><button type="button" onClick={()=>social("google")} disabled={busy}>Google</button><button type="button" onClick={()=>social("facebook")} disabled={busy}>Facebook</button></div></div>{message&&<p className="authMessage" role="alert">{message}</p>}<a className="authSwitch" href={switchHref}>{signUp?t.existing:t.newAccount}</a></div>;
}
