'use client';
import {useEffect,useRef,useState} from 'react';
import {useAdventureState} from './KidsJourney';
import styles from './AquaWorld.module.css';
const species=[
{id:'tilapia',ar:'البلطي النيلي',en:'Nile tilapia',home:'river',arFact:'سمكة مياه عذبة ومصدر للبروتين.',enFact:'A freshwater fish and a source of protein.'},
{id:'catfish',ar:'القرموط',en:'Catfish',home:'river',arFact:'يعيش في المياه العذبة.',enFact:'Lives in freshwater.'},
{id:'perch',ar:'قشر البياض النيلي',en:'Nile perch',home:'river',arFact:'من أسماك المياه العذبة في أفريقيا.',enFact:'A freshwater fish found in Africa.'},
{id:'sardine',ar:'السردين',en:'Sardine',home:'sea',arFact:'من الأسماك الدهنية التي قد توفر أوميجا ٣.',enFact:'An oily fish that can provide omega-3.'},
{id:'mullet',ar:'البوري',en:'Mullet',home:'sea',arFact:'يعيش في مياه ساحلية وبعض المياه قليلة الملوحة.',enFact:'Lives in coastal and some brackish waters.'},
{id:'mackerel',ar:'الماكريل',en:'Mackerel',home:'sea',arFact:'من أسماك البحر الدهنية؛ العناصر الغذائية تختلف بين الأنواع.',enFact:'An oily marine fish; nutrient amounts vary across species.'}
];
const clues=[{id:'habitat',ar:'أي بيئة مناسبة للبلطي النيلي؟',en:'Which habitat suits Nile tilapia?',options:[{id:'fresh',ar:'مياه عذبة',en:'Freshwater'},{id:'sand',ar:'رمال جافة',en:'Dry sand'},{id:'tree',ar:'فوق الشجر',en:'Treetops'}],answer:'fresh',arWhy:'البلطي النيلي من أسماك المياه العذبة.',enWhy:'Nile tilapia is a freshwater fish.'},{id:'variety',ar:'هل كل أنواع السمك لها نفس العناصر الغذائية؟',en:'Do all fish species have the same nutrients?',options:[{id:'vary',ar:'تختلف حسب النوع',en:'They vary by species'},{id:'same',ar:'كلها متطابقة',en:'All are identical'},{id:'none',ar:'لا تحتوي أي عناصر',en:'None contain nutrients'}],answer:'vary',arWhy:'السمك قد يوفر البروتين، وكميات أوميجا ٣ وفيتامين د تختلف حسب النوع.',enWhy:'Fish can provide protein; omega-3 and vitamin D amounts vary by species.'}];
export default function AquaWorld({ar,onComplete}:{ar:boolean;onComplete?:()=>void}){
 const [home,setHome]=useState('river'),[picked,setPicked]=useState<string|null>(null),[clue,setClue]=useState(0),[answer,setAnswer]=useState<string|null>(null),[habitat,setHabitat]=useState<string|null>(null);
 const [found,setFound,ready]=useAdventureState<string[]>('aqua',[]);
 const clueHeading=useRef<HTMLHeadingElement>(null),focusNext=useRef(false);
 useEffect(()=>{if(found.length===species.length)onComplete?.()},[found,onComplete]);
 useEffect(()=>{if(focusNext.current){clueHeading.current?.focus({preventScroll:true});focusNext.current=false}},[clue]);
 const t=(a:string,b:string)=>ar?a:b,q=clues[clue],fish=species.find(f=>f.id===picked);
 const explore=(id:string)=>{if(!ready)return;setPicked(id);setHabitat(null);setFound(previous=>previous.includes(id)?previous:[...previous,id])};
 return <section dir={ar?'rtl':'ltr'} aria-label={t('اكتشاف الأسماك','Fish discovery')} className={styles.world}>
 <header className={styles.header}><div><h2>{t('🐟 عالم الأسماك','🐟 Aqua World')}</h2><p>{t('اكتشف أسماك النيل والبحر، وتعرف على الغذاء والبيئات المائية.','Discover Nile and sea fish, aquatic habitats and food stories.')}</p></div><img src="/kids/ilamo.webp" alt="" width={100} height={100} loading="lazy"/></header>
 <div className={styles.actions} role="group" aria-label={t('اختار بيئة مائية','Choose an aquatic habitat')}>{['river','sea'].map(h=><button key={h} type="button" aria-pressed={home===h} onClick={()=>{setHome(h);setPicked(null);setHabitat(null)}}>{h==='river'?t('🏞️ النيل','🏞️ Nile'):t('🌊 البحر','🌊 Sea')}</button>)}</div>
 <p className={styles.habitatNote}>{home==='river'?t('هنا نستكشف أسماك المياه العذبة. اختار سمكة ولاحظ حكايتها.','Here we explore freshwater fish. Choose a fish and notice its story.'):t('هنا نستكشف أسماك البحر والسواحل. بعض الأنواع تعيش في أكثر من بيئة.','Here we explore sea and coastal fish. Some species live in more than one habitat.')}</p>
 <div className={styles.water} data-habitat={home} aria-busy={!ready}>{species.filter(f=>f.home===home).map(f=><button type="button" key={f.id} disabled={!ready} aria-pressed={picked===f.id} onClick={()=>explore(f.id)}><span aria-hidden="true" className={styles.fish}>🐟</span><strong>{t(f.ar,f.en)}</strong><span className={styles.discovery}>{found.includes(f.id)?t('✓ اكتشاف محفوظ','✓ Discovery saved'):t('افتح الحكاية','Open the story')}</span></button>)}</div>
 <div role="status" aria-live="polite" className={styles.fact}>{fish?<p>{t(fish.arFact,fish.enFact)}</p>:t('اختار سمكة علشان تعرف حكايتها.','Choose a fish to learn its story.')}</div>
 {fish&&<article className={styles.habitatGame}><h3>{t('لاحظ موطن السمكة','Notice the fish’s habitat')}</h3><p>{t('أي بيئة اكتشفناها في حكاية هذه السمكة؟','Which habitat did we explore in this fish’s story?')}</p><div className={styles.actions} role="group" aria-label={t('اختيارات موطن السمكة','Fish habitat choices')}>{['river','sea'].map(h=><button key={h} type="button" aria-pressed={habitat===h} onClick={()=>setHabitat(h)}>{h==='river'?t('المياه العذبة','Freshwater'):t('البحر والسواحل','Sea and coasts')}</button>)}</div><p role="status">{habitat===fish.home?t('لاحظت الحكاية! تقدر تستكشف نوعًا آخر وقت ما تحب.','You noticed the story! Explore another species whenever you like.'):habitat?t('ارجع لمعلومة السمكة وجرب تاني. بعض الأنواع تعيش في أكثر من بيئة.','Revisit the fish fact and try again. Some species live in more than one habitat.'):t('الحكاية تساعدك؛ مفيش درجات أو خسارة.','The story can help; no grades or losses.')}</p></article>}
 <p>{t('اكتشافاتك: ','Your discoveries: ')}{found.length}/{species.length}</p>
 <article className={styles.detective}><p className={styles.clueCount}>{t('المعلومة','Clue')} {clue+1} / {clues.length}</p><h3>{t('🔎 محقق المياه','🔎 Water detective')}</h3><h4 ref={clueHeading} tabIndex={-1}>{t(q.ar,q.en)}</h4><div className={styles.actions}>{q.options.map(option=><button type="button" key={option.id} aria-pressed={answer===option.id} onClick={()=>setAnswer(option.id)}>{t(option.ar,option.en)}</button>)}</div>{answer&&<p role="status">{answer===q.answer?t(q.arWhy,q.enWhy):t('تخمين جميل. جرب اختيارًا آخر أو لاحظ قصص الأسماك.','Nice guess. Try another choice or explore the fish stories.')}</p>}<button type="button" onClick={()=>{focusNext.current=true;setClue(i=>(i+1)%clues.length);setAnswer(null)}} className={styles.next}>{t('معلومة أخرى ←','Another clue →')}</button></article>
 <p className={styles.safety}>{t('التحضير والطهي بمساعدة شخص بالغ. اختيار الطعام يعتمد على احتياجات الأسرة والحساسية المتاحة لها؛ لا يوجد ضغط لتذوق السمك.','Preparation and cooking need a grown-up. Food choices depend on family needs and allergies; there is no pressure to taste fish.')}</p>
 </section>;
}
