"use client";
import {useEffect,useState} from "react";
type L={ar:string;en:string};const tr=(ar:boolean,x:L)=>ar?x.ar:x.en;
type Activity={id:string;icon:string;name:L;description:L;question:L;choices:L[];correct:number;explanation:L;category:"food"|"science"|"egypt"|"nature"|"family"};
const A:Activity[]=[
{id:"colors",icon:"🌈",category:"food",name:{ar:"ألوان الطعام",en:"Food Colors"},description:{ar:"اكتشف تنوع ألوان الطعام",en:"Explore colorful foods"},question:{ar:"أي طعام لونه برتقالي غالبًا؟",en:"Which food is often orange?"},choices:[{ar:"الجزر",en:"Carrot"},{ar:"الخيار",en:"Cucumber"},{ar:"الباذنجان",en:"Eggplant"}],correct:0,explanation:{ar:"الجزر غالبًا برتقالي، وفيه أصناف بألوان أخرى.",en:"Carrots are often orange, though other colors exist."}},
{id:"protein",icon:"🥚",category:"food",name:{ar:"مصادر البروتين",en:"Protein Sources"},description:{ar:"تعرف على أطعمة مختلفة",en:"Discover different foods"},question:{ar:"أي طعام من مصادر البروتين؟",en:"Which food provides protein?"},choices:[{ar:"البيض",en:"Eggs"},{ar:"الماء",en:"Water"},{ar:"الملح",en:"Salt"}],correct:0,explanation:{ar:"البيض مصدر بروتين، وفيه بدائل نباتية مثل العدس.",en:"Eggs provide protein; lentils are another option."}},
{id:"hydration",icon:"💧",category:"food",name:{ar:"المياه مهمة",en:"Water Matters"},description:{ar:"اكتشف أهمية المياه",en:"Learn about hydration"},question:{ar:"إيه مشروب مناسب للعطش اليومي؟",en:"What's a good everyday drink for thirst?"},choices:[{ar:"المياه",en:"Water"},{ar:"مياه البحر",en:"Seawater"},{ar:"مشروب شديد الملوحة",en:"Very salty drink"}],correct:0,explanation:{ar:"المياه مناسبة للشرب اليومي لمعظم الناس.",en:"Water is a good everyday drink for most people."}},
{id:"wash",icon:"🧼",category:"food",name:{ar:"قبل الأكل",en:"Before Eating"},description:{ar:"تعلم النظافة",en:"Learn hygiene"},question:{ar:"نعمل إيه قبل تحضير الأكل؟",en:"What should we do before preparing food?"},choices:[{ar:"نغسل إيدينا",en:"Wash hands"},{ar:"نلمس التراب",en:"Touch soil"},{ar:"نترك الأكل مكشوف",en:"Leave food uncovered"}],correct:0,explanation:{ar:"غسل اليدين يساعد في تقليل انتقال الجراثيم.",en:"Handwashing helps reduce the spread of germs."}},
{id:"plant",icon:"🌱",category:"science",name:{ar:"سر النبات",en:"Plant Secrets"},description:{ar:"اكتشف احتياجات النبات",en:"Discover plant needs"},question:{ar:"إيه اللي بيساعد معظم النباتات تنمو؟",en:"What helps most plants grow?"},choices:[{ar:"ضوء ومياه",en:"Light and water"},{ar:"ظلام دائم",en:"Permanent darkness"},{ar:"بلا مياه",en:"No water"}],correct:0,explanation:{ar:"معظم النباتات تحتاج ضوء ومياه وعناصر غذائية.",en:"Most plants need light, water and nutrients."}},
{id:"roots",icon:"🥕",category:"science",name:{ar:"الجذور",en:"Roots"},description:{ar:"شوف إزاي النبات يعيش",en:"How plants live"},question:{ar:"الجذور بتمتص إيه من التربة؟",en:"What do roots absorb from soil?"},choices:[{ar:"المياه والأملاح",en:"Water and minerals"},{ar:"أشعة القمر",en:"Moonbeams"},{ar:"الأصوات",en:"Sounds"}],correct:0,explanation:{ar:"الجذور تساعد النبات على امتصاص الماء والعناصر المعدنية.",en:"Roots absorb water and mineral nutrients."}},
{id:"sun",icon:"☀️",category:"science",name:{ar:"ضوء الشمس",en:"Sunlight"},description:{ar:"تجربة مع الضوء",en:"Explore light"},question:{ar:"الشمس بتساعد النبات يعمل إيه؟",en:"What does sunlight help plants do?"},choices:[{ar:"يصنع غذاءه",en:"Make its food"},{ar:"يتحول لحجر",en:"Turn to stone"},{ar:"يختفي",en:"Disappear"}],correct:0,explanation:{ar:"النبات يستخدم طاقة الضوء في البناء الضوئي.",en:"Plants use light energy for photosynthesis."}},
{id:"seasons",icon:"🌦️",category:"science",name:{ar:"الفصول",en:"Seasons"},description:{ar:"اكتشف تغير الجو",en:"Discover weather changes"},question:{ar:"إيه اللي ممكن يتغير بين الصيف والشتاء؟",en:"What may change between summer and winter?"},choices:[{ar:"درجة الحرارة",en:"Temperature"},{ar:"عدد أيام الأسبوع",en:"Days in a week"},{ar:"شكل الأرض",en:"Earth's shape"}],correct:0,explanation:{ar:"درجات الحرارة والنهار والطقس تتغير بين الفصول.",en:"Temperature, daylight and weather vary with seasons."}},
{id:"nile",icon:"🏞️",category:"egypt",name:{ar:"نهر النيل",en:"The Nile"},description:{ar:"رحلة مع المياه",en:"A river journey"},question:{ar:"النيل نوعه إيه؟",en:"What type of waterway is the Nile?"},choices:[{ar:"نهر",en:"River"},{ar:"محيط",en:"Ocean"},{ar:"بركان",en:"Volcano"}],correct:0,explanation:{ar:"النيل نهر مهم للزراعة والحياة في مصر.",en:"The Nile is an important river for life and agriculture in Egypt."}},
{id:"delta",icon:"🌾",category:"egypt",name:{ar:"أرض الدلتا",en:"The Delta"},description:{ar:"استكشف الزراعة",en:"Explore farmland"},question:{ar:"إيه نشاط منتشر في دلتا النيل؟",en:"What activity is common in the Nile Delta?"},choices:[{ar:"الزراعة",en:"Farming"},{ar:"التزلج على الجليد",en:"Ice skiing"},{ar:"تسلق البراكين",en:"Volcano climbing"}],correct:0,explanation:{ar:"دلتا النيل منطقة زراعية مهمة.",en:"The Nile Delta is an important farming region."}},
{id:"aswan",icon:"🌴",category:"egypt",name:{ar:"رحلة أسوان",en:"Aswan Journey"},description:{ar:"جنوب مصر",en:"Southern Egypt"},question:{ar:"أسوان في أي جزء من مصر؟",en:"Where is Aswan in Egypt?"},choices:[{ar:"الجنوب",en:"South"},{ar:"الشمال الغربي",en:"Northwest"},{ar:"وسط البحر",en:"Middle of the sea"}],correct:0,explanation:{ar:"أسوان في جنوب مصر على نهر النيل.",en:"Aswan is in southern Egypt along the Nile."}},
{id:"fish",icon:"🐟",category:"nature",name:{ar:"السمك والبيئة",en:"Fish Habitats"},description:{ar:"بيئات مختلفة للأسماك",en:"Explore aquatic habitats"},question:{ar:"البلطي النيلي يعيش غالبًا فين؟",en:"Where does Nile tilapia generally live?"},choices:[{ar:"مياه عذبة",en:"Freshwater"},{ar:"رمال جافة",en:"Dry sand"},{ar:"فوق الأشجار",en:"Treetops"}],correct:0,explanation:{ar:"البلطي النيلي من أسماك المياه العذبة.",en:"Nile tilapia is a freshwater fish."}},
{id:"reef",icon:"🪸",category:"nature",name:{ar:"الشعاب المرجانية",en:"Coral Reefs"},description:{ar:"استكشف البحر الأحمر",en:"Explore the Red Sea"},question:{ar:"الشعاب المرجانية بتوفر إيه؟",en:"What do coral reefs provide?"},choices:[{ar:"موائل لكائنات بحرية",en:"Marine habitats"},{ar:"طرق للسيارات",en:"Roads for cars"},{ar:"ثلوج دائمة",en:"Permanent snow"}],correct:0,explanation:{ar:"الشعاب المرجانية موائل مهمة لكائنات بحرية كثيرة.",en:"Coral reefs provide habitat for many marine species."}},
{id:"compost",icon:"♻️",category:"nature",name:{ar:"بقايا النبات",en:"Plant Scraps"},description:{ar:"تعلم تقليل الهدر",en:"Reduce waste"},question:{ar:"بقايا الخضار النباتية ممكن تستخدم في إيه مع إشراف بالغ؟",en:"With adult guidance, what can some vegetable scraps become?"},choices:[{ar:"سماد عضوي",en:"Compost"},{ar:"بطاريات",en:"Batteries"},{ar:"زجاج",en:"Glass"}],correct:0,explanation:{ar:"بعض البقايا النباتية تصلح للتسميد بطريقة صحيحة.",en:"Some plant scraps can be composted properly."}},
{id:"family",icon:"👨‍👩‍👧",category:"family",name:{ar:"مهمة الأسرة",en:"Family Mission"},description:{ar:"اكتشفوا سوا بعيد عن الشاشة",en:"Discover together offline"},question:{ar:"إيه نشاط ممكن تعمله مع حد كبير؟",en:"What can you do with a trusted adult?"},choices:[{ar:"تزرع بذرة",en:"Plant a seed"},{ar:"تلمس نار ساخنة",en:"Touch a hot flame"},{ar:"تستخدم سكينة وحدك",en:"Use a knife alone"}],correct:0,explanation:{ar:"زراعة بذرة مع الأسرة نشاط ممتع وآمن.",en:"Planting a seed together is a fun activity."}}
];
type Age="little"|"middle"|"older";
const categories=[{id:"food",ar:"الغذاء",en:"Food",icon:"🍎"},{id:"science",ar:"العلوم",en:"Science",icon:"🔬"},{id:"egypt",ar:"مصر",en:"Egypt",icon:"🗺️"},{id:"nature",ar:"الطبيعة",en:"Nature",icon:"🌿"},{id:"family",ar:"الأسرة",en:"Family",icon:"❤️"}] as const;
export default function DiscoveryLab({ar,userId,onComplete}:{ar:boolean;userId?:string;onComplete?:()=>void}){
const [category,setCategory]=useState<string>("food");const [active,setActive]=useState<Activity|null>(null);const [answer,setAnswer]=useState<number|null>(null);const [completed,setCompleted]=useState<string[]>([]);const [age,setAge]=useState<Age>("middle");const [showHint,setShowHint]=useState(false);
const key="ilama-discoveries-v2:"+(userId||"guest");
const [loadedKey,setLoadedKey]=useState<string|null>(null);
useEffect(()=>{setActive(null);setAnswer(null);setShowHint(false);setLoadedKey(null);try{const data=JSON.parse(localStorage.getItem(key)||"[]");setCompleted(Array.isArray(data)?[...new Set(data.filter((x):x is string=>typeof x==="string"&&A.some(a=>a.id===x)))]:[])}catch{setCompleted([])}setLoadedKey(key)},[key]);
useEffect(()=>{if(loadedKey!==key)return;try{localStorage.setItem(key,JSON.stringify(completed))}catch{}},[completed,key,loadedKey]);
const choose=(i:number)=>{if(loadedKey!==key||!active||i<0||i>=active.choices.length)return;setAnswer(i);if(i===active.correct){onComplete?.();setCompleted(prev=>prev.includes(active.id)?prev:[...prev,active.id])}};
const t=(a:string,b:string)=>ar?a:b;
const visibleChoices=active?active.choices.map((choice,index)=>({choice,index})).filter(({index})=>age!=="little"||index===active.correct||index===(active.correct+1)%active.choices.length):[];
const offset=active?[...active.id].reduce((sum,c)=>sum+c.charCodeAt(0),0)%Math.max(1,visibleChoices.length):0;
const orderedChoices=[...visibleChoices.slice(offset),...visibleChoices.slice(0,offset)];
return <section dir={ar?"rtl":"ltr"} style={{margin:"28px 0",padding:"clamp(12px,3vw,28px)",background:"#fff4e9",borderRadius:26,color:"#51422e"}}>
<h2 style={{fontSize:"clamp(24px,4vw,40px)"}}>{t("✨ معمل الاكتشافات","✨ Discovery Lab")}</h2><p>{t("أنشطة قصيرة فيها أسئلة وتجارب وأفكار جديدة. مفيش عقوبات على المحاولات.","Short challenges and discoveries. No penalties for trying.")}</p>
<fieldset style={{border:0,padding:0,marginBottom:15}}><legend>{t("اختار المرحلة العمرية","Choose age group")}</legend><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{([{id:"little",ar:"٣–٥",en:"3–5"},{id:"middle",ar:"٦–٨",en:"6–8"},{id:"older",ar:"٩–١٢",en:"9–12"}] as const).map(g=><button type="button" key={g.id} aria-pressed={age===g.id} onClick={()=>{setAge(g.id);setAnswer(null);setShowHint(false)}} style={{borderRadius:12,padding:"9px 15px",border:"1px solid #94714e",background:age===g.id?"#785c3f":"white",color:age===g.id?"white":"#4c3a29"}}>{t(g.ar,g.en)}</button>)}</div></fieldset>
<div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:18}}>{categories.map(c=><button type="button" key={c.id} aria-pressed={category===c.id} onClick={()=>{setCategory(c.id);setActive(null);setAnswer(null)}} style={{padding:"10px 13px",border:"2px solid #bd9b75",borderRadius:16,background:category===c.id?"#805b3d":"#fff",color:category===c.id?"white":"#483a2a"}}>{c.icon} {t(c.ar,c.en)}</button>)}</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:12}}>{A.filter(a=>a.category===category).map(a=><button type="button" key={a.id} onClick={()=>{setActive(a);setAnswer(null);setShowHint(false)}} aria-pressed={active?.id===a.id} style={{textAlign:ar?"right":"left",borderRadius:18,border:"2px solid #d4b995",background:"white",padding:16,color:"#4e3c29",minHeight:120}}><span style={{fontSize:27}}>{a.icon}</span><strong style={{display:"block",margin:"6px 0"}}>{tr(ar,a.name)} {completed.includes(a.id)?"✓":""}</strong><span>{tr(ar,a.description)}</span></button>)}</div>
{active&&<article style={{background:"#fff",borderRadius:18,padding:18,marginTop:18}}><h3>{tr(ar,active.question)}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:9}}>{orderedChoices.map(({choice:c,index:i})=><button type="button" key={i} onClick={()=>choose(i)} style={{padding:15,borderRadius:14,border:"2px solid #b48c5f",background:answer===i?"#f7e4c5":"#fff",color:"#4e3c29"}}>{tr(ar,c)}</button>)}</div>{answer!==null&&<p role="status" aria-live="polite">{answer===active.correct?t("أحسنت! 🌟 ","Well done! 🌟 ")+tr(ar,active.explanation):t("محاولة جميلة! جرّب مرة تانية، أو اطلب تلميحًا.","Nice try! Try again or ask for a hint.")}</p>}{answer!==active.correct&&<button type="button" onClick={()=>setShowHint(v=>!v)} style={{border:0,background:"transparent",textDecoration:"underline",padding:8,color:"#684c32"}}>{t("💡 تلميح","💡 Hint")}</button>}{showHint&&<p>{tr(ar,active.explanation)}</p>}</article>}
<p style={{marginTop:18}}>{t("اكتشافاتك المكتملة: ","Discoveries completed: ")}<strong>{completed.length}/{A.length}</strong></p><small>{t("مفيش سباق أو خصم نقاط. تقدر توقف وتكمل وقت ما تحب. بعض الأنشطة الخارجية تحتاج إشراف بالغ.","No races or point deductions. Stop anytime. Offline activities may require adult supervision.")}</small>
</section>
}