"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./EditorialPages.module.css";

export type View="home"|"learn"|"kids"|"everyday"|"weekly"|"easy"|"lens"|"atlas"|"log"|"journal"|"visit"|"about"|"privacy"|"sitemap";
export type Entry={id?:string;type:string;value:string;at:string};
const labels:{[k:string]:string}={Meal:"وجبة",Water:"مياه",Sleep:"نوم",Medication:"دواء","Medication check":"متابعة دواء",Symptom:"عرض","Symptom severity":"شدة العرض","Work / activity":"نشاط / شغل",Smoking:"تدخين",Condition:"حالة صحية","Previous operation":"عملية سابقة",Feeling:"إحساس",Measurement:"قياس",Note:"ملاحظة","Question for visit":"سؤال للزيارة","Food label":"بطاقة طعام",Food:"أكل"};
const Hero=({kicker,title,italic,copy,img}:{kicker:string;title:string;italic?:string;copy:string;img:string})=><section className={styles.hero}><div><p className={styles.kicker}>{kicker}</p><h1>{title}{italic&&<><br/><em>{italic}</em></>}</h1><p>{copy}</p></div><figure><img src={img} alt=""/></figure></section>;
const Arrow=()=> <span aria-hidden="true">→</span>;

export function LearnEditorial({go,ar}:{go:(v:View)=>void;ar:boolean}){
 type Guide={id:string;eyebrow_en:string;eyebrow_ar:string;title_en:string;title_ar:string;body_en:string;body_ar:string;practical_en:string;practical_ar:string};
 const [q,setQ]=useState(""),[active,setActive]=useState<string|null>(null),[db,setDb]=useState<Guide[]>([]);
 useEffect(()=>{fetch("/api/learning-guides").then(r=>r.ok?r.json():null).then(d=>Array.isArray(d?.guides)&&setDb(d.guides)).catch(()=>{})},[]);
 const fallback:Guide[]=[{id:"carbs",eyebrow_en:"CARBOHYDRATES",eyebrow_ar:"الكربوهيدرات",title_en:"Carbohydrates, without the drama.",title_ar:"الكربوهيدرات من غير تعقيد.",body_en:"Start with what the food contains and the portion.",body_ar:"ابدأ بمكونات الأكل والكمية.",practical_en:"Bread, rice, fruit, milk and legumes can contribute carbohydrate.",practical_ar:"العيش والأرز والفاكهة واللبن والبقوليات ممكن تضيف كربوهيدرات."}];
 const guides=(db.length?db:fallback).map(g=>({id:g.id,eye:ar?g.eyebrow_ar:g.eyebrow_en,title:ar?g.title_ar:g.title_en,body:ar?g.body_ar:g.body_en,practical:ar?g.practical_ar:g.practical_en})); const needle=q.toLowerCase().trim(); const shown=guides.filter(g=>!needle||Object.values(g).join(" ").toLowerCase().includes(needle));
 return <div className={styles.page}><Hero kicker={ar?"التغذية · المكتبة":"NUTRITION · LIBRARY"} title={ar?"المعرفة التي":"Knowledge that"} italic={ar?"تخدم يومك.":"serves real life."} copy={ar?"ابحث في موضوعات التغذية والصحة بلغة واضحة، ثم افتح ما تحتاجه فقط.":"Explore nutrition and health in plain language, then open only what you need."} img="https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.library}><div className={styles.search}><label>{ar?"ابحث في المكتبة":"SEARCH THE LIBRARY"}</label><div><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?"كربوهيدرات، طعام، تحاليل...":"Carbs, food, labs..."}/>{q&&<button onClick={()=>setQ("")}>×</button>}</div></div><div className={styles.guideGrid}>{shown.map((g,i)=><article key={g.id}><span>0{i+1}</span><p className={styles.kicker}>{g.eye}</p><h2>{g.title}</h2><p>{g.body}</p>{active===g.id&&<aside><b>{ar?"بشكل عملي":"MAKE IT PRACTICAL"}</b><p>{g.practical}</p></aside>}<button onClick={()=>setActive(active===g.id?null:g.id)}>{active===g.id?(ar?"إغلاق":"Close"):(ar?"اقرأ الدليل":"Read guide")} <Arrow/></button></article>)}</div><div className={styles.bridge}><div><p className={styles.kicker}>{ar?"من المعرفة للتطبيق":"FROM KNOWLEDGE TO CONTEXT"}</p><h2>{ar?"احتفظ بما يهمك.":"Keep what matters."}</h2></div><button onClick={()=>go("log")}>{ar?"أضف لليوميات":"Add to journal"} <Arrow/></button></div></section></div>
}

export function LensEditorial({add,go,ar}:{add:(t:string,v:string)=>Promise<boolean>|boolean;go:(v:View)=>void;ar:boolean}){
 const [serving,setServing]=useState("30"),[carbs,setCarbs]=useState(""),[basis,setBasis]=useState("100"),[saved,setSaved]=useState(false);
 const result=useMemo(()=>{const a=Number(carbs),b=Number(serving),c=Number(basis);return carbs&&serving&&basis&&a>=0&&b>0&&c>0?a*b/c:null},[carbs,serving,basis]);
 return <div className={styles.page}><Hero kicker={ar?"عدسة الطعام":"FOOD LENS"} title={ar?"اقرأ البطاقة":"Read the label."} italic={ar?"احسب حصتك.":"Know your portion."} copy={ar?"حساب بسيط من الأرقام المكتوبة على العبوة — بدون تخمين أو قرارات علاجية.":"Simple portion arithmetic from the numbers on the pack — no guessing, no treatment decisions."} img="https://images.pexels.com/photos/7262897/pexels-photo-7262897.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.toolSplit}><div className={styles.formCard}><p className={styles.kicker}>01 · {ar?"بيانات البطاقة":"LABEL"}</p><label>{ar?"إجمالي الكربوهيدرات":"Total carbohydrate"}<span><input inputMode="decimal" value={carbs} onChange={e=>{setCarbs(e.target.value);setSaved(false)}} placeholder="68"/><i>g</i></span></label><label>{ar?"الكمية المرجعية":"Label basis"}<span><input inputMode="decimal" value={basis} onChange={e=>{setBasis(e.target.value);setSaved(false)}}/><i>g</i></span></label><p className={styles.kicker}>02 · {ar?"حصتك":"YOUR PORTION"}</p><label>{ar?"الكمية":"Portion"}<span><input inputMode="decimal" value={serving} onChange={e=>{setServing(e.target.value);setSaved(false)}}/><i>g</i></span></label></div><aside className={styles.result}><p className={styles.kicker}>{ar?"لهذه الحصة":"FOR THIS PORTION"}</p><strong>{result===null?"—":result.toFixed(1)}<i>{result===null?"":"g"}</i></strong><h2>{ar?"كربوهيدرات":"carbohydrate"}</h2>{result!==null&&<><p>{carbs} g × {serving} g ÷ {basis} g</p><button onClick={async()=>{const ok=await add("Food label",`Label: ${carbs} g carbohydrate per ${basis} g; portion ${serving} g ≈ ${result.toFixed(1)} g carbohydrate`);setSaved(Boolean(ok))}}>{saved?(ar?"✓ تم الحفظ":"✓ Saved"):(ar?"احفظ في اليوميات":"Remember this")} <Arrow/></button></>}<button className={styles.textBtn} onClick={()=>go("atlas")}>{ar?"اذهب لأطلس الطعام":"Explore Food Atlas"} <Arrow/></button></aside></section></div>
}

export function LogEditorial({add,go,ar}:{add:(t:string,v:string)=>Promise<boolean>|boolean;go:(v:View)=>void;ar:boolean}){
 const [type,setType]=useState("Meal"),[value,setValue]=useState(""); const types=[["Meal","Meal"],["Water","Water"],["Sleep","Sleep"],["Medication","Medication"],["Work / activity","Activity"],["Feeling","Feeling"],["Measurement","Measurement"],["Note","Note"]];
 return <div className={styles.page}><Hero kicker={ar?"سجل سريع":"QUICK LOG"} title={ar?"لحظة واحدة.":"One moment."} italic={ar?"احتفظ بها.":"Worth remembering."} copy={ar?"اختار النوع، اكتب ما يهمك، واحفظه في يومياتك.":"Choose a category, write what matters, and keep it in your journal."} img="https://images.pexels.com/photos/4050990/pexels-photo-4050990.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.logPanel}><p className={styles.kicker}>01 · {ar?"اختر النوع":"CHOOSE A CATEGORY"}</p><div className={styles.typeRow}>{types.map(([key,name])=><button className={type===key?styles.active:""} key={key} onClick={()=>setType(key)}>{ar?(labels[key]||key):name}</button>)}</div><label className={styles.noteField}><span>02 · {ar?"اكتب ما تريد تذكره":"WRITE WHAT YOU WANT TO REMEMBER"}</span><textarea maxLength={180} value={value} onChange={e=>setValue(e.target.value)} placeholder={ar?"تفصيلة قصيرة تكفي...":"A short note is enough..."}/><small>{value.length}/180</small></label><div className={styles.actions}><button className={styles.textBtn} onClick={()=>go("journal")}>{ar?"إلغاء":"Cancel"}</button><button disabled={!value.trim()} onClick={async()=>{if(await add(type,value.trim())){setValue("");go("journal")}}}>{ar?"احفظ في اليوميات":"Save to journal"} <Arrow/></button></div></section></div>
}

export function JournalEditorial({entries,go,clearEntries,removeEntry,updateEntry,undoEntry,undoRemove,ar}:{entries:Entry[];go:(v:View|"mind")=>void;clearEntries:()=>void;removeEntry:(at:string)=>void;updateEntry:(at:string,value:string)=>void;undoEntry:Entry|null;undoRemove:()=>void;ar:boolean}){
 const [editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState(""),[filter,setFilter]=useState("All"),[wellbeing,setWellbeing]=useState<any[]>([]); useEffect(()=>{const id=localStorage.getItem("ilama-active-family");const q=id?`?familyProfileId=${encodeURIComponent(id)}`:"";fetch("/api/care"+q).then(r=>r.ok?r.json():null).then(d=>setWellbeing(Array.isArray(d?.records)?d.records.filter((x:any)=>x.kind==="wellbeing-observation"):[])).catch(()=>setWellbeing([]))},[]); const types=["All",...Array.from(new Set(entries.map(e=>e.type)))]; const shown=filter==="All"?entries:entries.filter(e=>e.type===filter);
 return <div className={styles.page}><Hero kicker={ar?"اليوميات":"YOUR JOURNAL"} title={ar?"يومك،":"Your day,"} italic={ar?"بوضوح وهدوء.":"without the paperwork."} copy={ar?"خط زمني بسيط للحاجات التي اخترت الاحتفاظ بها.":"A calm timeline of what you chose to remember."} img="https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.journal}>{wellbeing.length>0&&<div className={styles.moodJournal}><div><p className={styles.kicker}>{ar?"MOOD & FOOD · ملاحظات Care":"MOOD & FOOD · CARE OBSERVATIONS"}</p><h2>{ar?"ملاحظاتك، منفصلة عن الاستنتاجات.":"Your observations, kept separate from conclusions."}</h2><p>{ar?"هذه السجلات من ملف Care النشط. لا نحولها لدرجة نفسية ولا نستنتج السبب.":"These records come from the active Care profile. They are not turned into a mental-health score or a causal claim."}</p></div><div>{wellbeing.slice(0,6).map((x:any)=><article key={x.id}><time>{new Date(x.occurred_at).toLocaleDateString()}</time><b>{x.title}</b>{x.detail&&<span>{x.detail}</span>}</article>)}</div><button onClick={()=>go("mind")}>{ar?"أضف ملاحظة Mood & Food":"Add Mood & Food observation"} →</button></div>}{undoEntry&&<div className={styles.notice}>{ar?"تم حذف السجل.":"Entry deleted."}<button onClick={undoRemove}>{ar?"تراجع":"Undo"}</button></div>}<div className={styles.journalTop}><div className={styles.filters}>{types.map(t=><button className={filter===t?styles.active:""} onClick={()=>setFilter(t)} key={t}>{ar?(t==="All"?"الكل":labels[t]||t):t}</button>)}</div><button onClick={()=>go("log")}>{ar?"+ سجل جديد":"+ New entry"}</button></div>{!shown.length?<div className={styles.empty}><p className={styles.kicker}>{ar?"مساحة هادئة":"A QUIET SPACE"}</p><h2>{ar?"لا توجد سجلات هنا بعد.":"Nothing here yet."}</h2><p>{ar?"أضف فقط ما يستحق أن ترجع إليه.":"Add only what feels worth returning to."}</p></div>:<div className={styles.timeline}>{shown.map(e=><article key={e.at}><time>{new Date(e.at).toLocaleDateString(undefined,{month:"short",day:"numeric"})}<small>{new Date(e.at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small></time><div><p className={styles.kicker}>{ar?(labels[e.type]||e.type):e.type}</p>{editing===e.at?<><textarea value={draft} maxLength={180} onChange={x=>setDraft(x.target.value)}/><div className={styles.inlineActions}><button onClick={()=>setEditing(null)}>{ar?"إلغاء":"Cancel"}</button><button onClick={()=>{updateEntry(e.at,draft);setEditing(null)}}>{ar?"حفظ":"Save"}</button></div></>:<h3>{e.value}</h3>}</div>{editing!==e.at&&<div className={styles.inlineActions}><button onClick={()=>{setEditing(e.at);setDraft(e.value)}}>{ar?"تعديل":"Edit"}</button><button onClick={()=>removeEntry(e.at)}>×</button></div>}</article>)}</div>} {entries.length>0&&<button className={styles.clear} onClick={clearEntries}>{ar?"مسح اليوميات":"Clear journal"}</button>}</section></div>
}

export function VisitEditorial({entries,add,ar,familyProfileId,familyProfileName}:{entries:Entry[];add:(t:string,v:string)=>Promise<boolean>|boolean;ar:boolean;familyProfileId?:string|null;familyProfileName?:string}){
 type Care={id:string;kind:string;title:string;detail:string;severity:number|null;metadata?:{dose?:string;frequency?:string;status?:string;startDate?:string;onset?:string;duration?:string;trigger?:string};occurred_at:string};
 const [days,setDays]=useState(7),[question,setQuestion]=useState(""),[copied,setCopied]=useState(false),[med,setMed]=useState(""),[medNote,setMedNote]=useState(""),[medDose,setMedDose]=useState(""),[medFrequency,setMedFrequency]=useState(""),[medStatus,setMedStatus]=useState("active"),[symptom,setSymptom]=useState(""),[severity,setSeverity]=useState(3),[symptomNote,setSymptomNote]=useState(""),[symptomOnset,setSymptomOnset]=useState(""),[symptomDuration,setSymptomDuration]=useState(""),[symptomStatus,setSymptomStatus]=useState("ongoing"),[symptomTrigger,setSymptomTrigger]=useState(""),[care,setCare]=useState<Care[]>([]),[editingCare,setEditingCare]=useState<string|null>(null),[careDraft,setCareDraft]=useState(""),[mentalPrompt,setMentalPrompt]=useState("");
 useEffect(()=>{const q=familyProfileId?`?familyProfileId=${encodeURIComponent(familyProfileId)}`:"";fetch("/api/care"+q).then(r=>r.ok?r.json():null).then(d=>setCare(Array.isArray(d?.records)?d.records:[])).catch(()=>setCare([]))},[familyProfileId]);
 const recent=useMemo(()=>familyProfileId?[]:entries.filter(e=>Date.now()-new Date(e.at).getTime()<days*86400000),[entries,days,familyProfileId]);
 const careRecent=useMemo(()=>care.filter(e=>Date.now()-new Date(e.occurred_at).getTime()<days*86400000),[care,days]);
 const careTimeline=useMemo(()=>careRecent.filter(e=>!(e.kind==="visit-note"&&e.detail==="Question for visit")),[careRecent]);
 const structuredQuestions=careRecent.filter(e=>e.kind==="visit-note"&&e.detail==="Question for visit");
 const legacyQuestions=recent.filter(e=>e.type==="Question for visit").filter(e=>!structuredQuestions.some(q=>q.title.trim().toLowerCase()===e.value.trim().toLowerCase()&&new Date(q.occurred_at).toISOString().slice(0,10)===new Date(e.at).toISOString().slice(0,10)));
 const questions=[...structuredQuestions.map(e=>({id:e.id,value:e.title,at:e.occurred_at,structured:true})),...legacyQuestions.map(e=>({id:e.id||e.at,value:e.value,at:e.at,structured:false}))].sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime());
 const legacyContext=recent.filter(e=>!["Question for visit","Medication","Medication check","Symptom","Symptom severity"].includes(e.type));
 const structuredKeys=useMemo(()=>new Set(careTimeline.map(e=>`${e.kind}|${e.title.trim().toLowerCase()}|${new Date(e.occurred_at).toISOString().slice(0,10)}`)),[careTimeline]);
 const legacyCare=recent.filter(e=>["Medication","Medication check","Symptom","Symptom severity"].includes(e.type)).filter(e=>{const kind=e.type.startsWith("Medication")?"medication":"symptom";const title=e.value.split(/ — | · /)[0].trim().toLowerCase();return !structuredKeys.has(`${kind}|${title}|${new Date(e.at).toISOString().slice(0,10)}`)});
 const timeline=useMemo(()=>[...careTimeline.map(e=>({id:e.id,at:e.occurred_at,kind:e.kind,title:e.title,detail:e.detail,severity:e.severity,structured:true})),...legacyCare.map(e=>({id:e.id||e.at,at:e.at,kind:e.type.startsWith("Medication")?"medication":"symptom",title:e.value,detail:"",severity:null,structured:false})),...legacyContext.map(e=>({id:e.id||e.at,at:e.at,kind:e.type,title:e.value,detail:"",severity:null,structured:false}))].sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime()),[careTimeline,legacyCare,legacyContext]);
 const saveCare=async(kind:string,title:string,detail:string,severityValue:number|null,metadata:Record<string,string>={})=>{try{const r=await fetch("/api/care",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,title,detail,severity:severityValue,metadata,occurredAt:new Date().toISOString(),familyProfileId:familyProfileId||null})});if(!r.ok)return false;const d=await r.json();if(d?.record)setCare(v=>[d.record,...v].slice(0,300));return true}catch{return false}};
 const contextText=(e:any)=>e.structured&&e.kind==="medication"&&e.metadata?[e.metadata.dose,e.metadata.frequency,e.metadata.status].filter(Boolean).join(" · "):e.structured&&e.kind==="symptom"&&e.metadata?[e.metadata.onset,e.metadata.duration,e.metadata.status,e.metadata.trigger].filter(Boolean).join(" · "):e.structured&&e.kind==="wellbeing-observation"&&e.metadata?[e.metadata.mood&&`Mood: ${e.metadata.mood}`,e.metadata.appetite&&`Appetite: ${e.metadata.appetite}`,e.metadata.mealRegularity&&`Meals: ${e.metadata.mealRegularity}`,e.metadata.sleep&&`Sleep: ${e.metadata.sleep}`,e.metadata.energy&&`Energy: ${e.metadata.energy}`,e.metadata.caffeine&&`Caffeine: ${e.metadata.caffeine}`,e.metadata.hydration&&`Hydration: ${e.metadata.hydration}`,e.metadata.giComfort&&`GI: ${e.metadata.giComfort}`,e.metadata.medicationContext&&`Medication context: ${e.metadata.medicationContext}`].filter(Boolean).join(" · "):"";
 const summary=()=>[ar?"ILAMA BLOOM — ملخص تجهيز الزيارة":"ILAMA BLOOM — VISIT PREP SUMMARY",familyProfileId?`${ar?"الملف":"PROFILE"}: ${familyProfileName|| (ar?"فرد العائلة":"Family member")}`:"",`${ar?"الفترة":"WINDOW"}: ${days} ${ar?"يوم":"days"}`,"",ar?"الخط الزمني:":"TIMELINE:",...timeline.map(e=>`- ${new Date(e.at).toLocaleDateString()} · ${e.kind.toUpperCase()} · ${e.title}${e.severity?` · ${e.severity}/5`:""}${e.detail?` — ${e.detail}`:""}${contextText(e)?` · ${contextText(e)}`:""}`),"",ar?"أسئلة للزيارة:":"QUESTIONS FOR THE VISIT:",...questions.map(e=>`? ${e.value}`)].filter(Boolean).join("\n");
 const copy=async()=>{try{await navigator.clipboard.writeText(summary());setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{}};
 const download=()=>{const blob=new Blob([summary()],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`ilama-visit-prep-${new Date().toISOString().slice(0,10)}.txt`;a.click();URL.revokeObjectURL(url)};
 const share=async()=>{const text=summary();try{if(navigator.share)await navigator.share({title:"ILAMA BLOOM — Visit Prep",text});else await navigator.clipboard.writeText(text)}catch{}};
 const saveMed=async()=>{if(!med.trim())return;if(await saveCare("medication",med.trim(),medNote.trim(),null,{dose:medDose.trim(),frequency:medFrequency.trim(),status:medStatus})){setMed("");setMedNote("");setMedDose("");setMedFrequency("");setMedStatus("active")}};
 const saveQuestion=async()=>{const value=question.trim();if(!value)return;if(await saveCare("visit-note",value,"Question for visit",null)){setQuestion("")}}; const mentalQuestions=ar?["هل تغيّر الشهية أو انتظام الأكل مهم في حالتي؟","هل توقيت الكافيين ممكن يؤثر على نومي أو الأعراض التي ألاحظها؟","لاحظت تغيرًا في الشهية/النوم مع الدواء — ماذا يجب أن أراقب؟"]:["Could my appetite or meal-pattern change be relevant to my care?","Could caffeine timing be affecting my sleep or what I notice?","I noticed appetite/sleep changes with medication — what should I monitor?"]; const addMentalQuestion=async()=>{if(!mentalPrompt)return;if(await saveCare("visit-note",mentalPrompt,"Question for visit",null))setMentalPrompt("")};
 const saveSymptom=async()=>{if(!symptom.trim())return;if(await saveCare("symptom",symptom.trim(),symptomNote.trim(),severity,{onset:symptomOnset.trim(),duration:symptomDuration.trim(),status:symptomStatus,trigger:symptomTrigger.trim()})){setSymptom("");setSymptomNote("");setSeverity(3);setSymptomOnset("");setSymptomDuration("");setSymptomStatus("ongoing");setSymptomTrigger("")}};
 const deleteCare=async(id:string)=>{try{const r=await fetch("/api/care",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id,familyProfileId:familyProfileId||null})});if(r.ok)setCare(v=>v.filter(x=>x.id!==id))}catch{}};
 const updateCare=async(record:Care)=>{const title=careDraft.trim();if(!title)return;try{const r=await fetch("/api/care",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:record.id,familyProfileId:familyProfileId||null,title,detail:record.detail,severity:record.severity,metadata:record.metadata||{},occurredAt:record.occurred_at})});const d=await r.json().catch(()=>null);if(r.ok&&d?.record){setCare(v=>v.map(x=>x.id===record.id?d.record:x));setEditingCare(null);setCareDraft("")}}catch{}};
 return <div className={styles.page}><Hero kicker={ar?"تجهيز الزيارة":"VISIT PREP"} title={ar?"خذ معك السياق،":"Bring context,"} italic={ar?"لا اختبارًا للذاكرة.":"not a memory test."} copy={ar?"ملخص مرتب مبني فقط على ما سجلته أنت.":"A compact, organized summary made only from what you recorded."} img="https://images.pexels.com/photos/3786157/pexels-photo-3786157.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.visit}>{familyProfileId&&<div className={styles.familyScope}><b>{ar?"ملف العائلة النشط":"ACTIVE FAMILY PROFILE"}</b><span>{familyProfileName||(ar?"فرد العائلة":"Family member")}</span><p>{ar?"كل ما تحفظه هنا يظل داخل هذا الملف ولا يختلط بيومياتك الشخصية.":"Everything saved here stays in this profile and does not mix with your personal Journal."}</p></div>}
 <div className={styles.careTools}><article><p className={styles.kicker}>01 · {ar?"الأدوية":"MEDICATION"}</p><h2>{ar?"سجل ما تريد تذكره عن الدواء.":"Keep the medicine context you want to remember."}</h2><label>{ar?"اسم الدواء":"Medication"}<input value={med} maxLength={80} onChange={e=>setMed(e.target.value)}/></label><label>{ar?"ملاحظة اختيارية":"Optional context"}<textarea value={medNote} maxLength={160} onChange={e=>setMedNote(e.target.value)} placeholder={ar?"مثلاً: بدأت اليوم، فاتتني جرعة، أريد سؤال الطبيب...":"e.g. started today, missed a dose, question for clinician..."}/></label><div className={styles.careFields}><label>{ar?"الجرعة كما هي مكتوبة":"Dose as recorded"}<input value={medDose} maxLength={80} onChange={e=>setMedDose(e.target.value)}/></label><label>{ar?"التكرار كما تستخدمه":"Frequency as recorded"}<input value={medFrequency} maxLength={80} onChange={e=>setMedFrequency(e.target.value)}/></label><label>{ar?"الحالة":"Status"}<select value={medStatus} onChange={e=>setMedStatus(e.target.value)}><option value="active">{ar?"حالي":"Active"}</option><option value="as-needed">{ar?"عند الحاجة":"As needed"}</option><option value="stopped">{ar?"متوقف":"Stopped"}</option></select></label></div><button disabled={!med.trim()} onClick={saveMed}>{ar?"احفظ":"Save medication note"} <Arrow/></button></article>
 <article><p className={styles.kicker}>02 · {ar?"الأعراض":"SYMPTOM"}</p><h2>{ar?"صف ما حدث، بدون تشخيص.":"Describe what happened, without diagnosing it."}</h2><label>{ar?"العرض":"Symptom"}<input value={symptom} maxLength={80} onChange={e=>setSymptom(e.target.value)}/></label><div className={styles.severity}><span>{ar?"الشدة التي شعرت بها":"How strong it felt"}</span>{[1,2,3,4,5].map(n=><button className={severity===n?styles.active:""} key={n} onClick={()=>setSeverity(n)}>{n}</button>)}</div><label>{ar?"السياق":"Context"}<textarea value={symptomNote} maxLength={160} onChange={e=>setSymptomNote(e.target.value)} placeholder={ar?"متى بدأ؟ ماذا كنت تفعل؟ ماذا لاحظت؟":"When did it start? What were you doing? What did you notice?"}/></label><div className={styles.careFields}><label>{ar?"البداية":"Onset"}<input value={symptomOnset} maxLength={80} onChange={e=>setSymptomOnset(e.target.value)}/></label><label>{ar?"المدة":"Duration"}<input value={symptomDuration} maxLength={80} onChange={e=>setSymptomDuration(e.target.value)}/></label><label>{ar?"الحالة الآن":"Current status"}<select value={symptomStatus} onChange={e=>setSymptomStatus(e.target.value)}><option value="ongoing">{ar?"مستمر":"Ongoing"}</option><option value="intermittent">{ar?"متقطع":"Intermittent"}</option><option value="improved">{ar?"تحسن":"Improved"}</option><option value="resolved">{ar?"انتهى":"Resolved"}</option></select></label><label>{ar?"محفز أو سياق لاحظته":"Trigger / context noticed"}<input value={symptomTrigger} maxLength={160} onChange={e=>setSymptomTrigger(e.target.value)}/></label></div><button disabled={!symptom.trim()} onClick={saveSymptom}>{ar?"احفظ":"Save symptom"} <Arrow/></button></article></div>
 <div className={styles.structuredNote}><b>CARE 3.0</b><span>{ar?`${careRecent.length} سجل منظم · السجلات القديمة تظهر فقط عندما لا يوجد لها سجل منظم مطابق`:`${careRecent.length} structured records · legacy care entries appear only when no matching structured record exists`}</span></div>
 <div className={styles.range}><p className={styles.kicker}>03 · {ar?"الفترة":"TIME WINDOW"}</p>{[7,14,30].map(n=><button className={days===n?styles.active:""} onClick={()=>setDays(n)} key={n}>{n} {ar?"يوم":"days"}</button>)}</div>
 <div className={styles.stats}><span><small>{ar?"أحداث الخط الزمني":"TIMELINE EVENTS"}</small><b>{timeline.length}</b></span><span><small>{ar?"الأسئلة":"QUESTIONS"}</small><b>{questions.length}</b></span><div className={styles.summaryActions}><button onClick={copy}>{copied?(ar?"✓ تم النسخ":"✓ Copied"):(ar?"نسخ":"Copy")}</button><button onClick={download}>{ar?"تنزيل":"Download"}</button><button onClick={share}>{ar?"مشاركة":"Share"}</button></div></div>
 <div className={styles.visitGrid}><div><p className={styles.kicker}>04 · {ar?"الخط الزمني":"CLINICIAN-FACING TIMELINE"}</p>{timeline.length?timeline.map(e=><article key={e.id}><b>{e.kind==="medication"?(ar?"دواء":"Medication"):e.kind==="symptom"?(ar?"عرض":"Symptom"):(ar?(labels[e.kind]||e.kind):e.kind)}</b><p>{e.structured&&editingCare===e.id?<span className={styles.careEdit}><input value={careDraft} maxLength={120} onChange={x=>setCareDraft(x.target.value)}/><button onClick={()=>updateCare(care.find(x=>x.id===e.id)!)}>{ar?"حفظ":"Save"}</button><button onClick={()=>setEditingCare(null)}>{ar?"إلغاء":"Cancel"}</button></span>:<><strong>{e.title}</strong>{e.severity?<> · {e.severity}/5</>:null}{e.detail?<><br/><span>{e.detail}</span></>:null}</>}</p><small>{new Date(e.at).toLocaleString()}</small>{e.structured&&<span className={styles.careRecordActions}><button onClick={()=>{setEditingCare(e.id);setCareDraft(e.title)}}>{ar?"تعديل":"Edit"}</button><button onClick={()=>deleteCare(e.id)}>{ar?"حذف":"Delete"}</button></span>}</article>):<div className={styles.empty}><h2>{ar?"لا توجد سجلات في هذه الفترة.":"No records in this period."}</h2></div>}</div>
 <aside><p className={styles.kicker}>05 · {ar?"جيب الأسئلة":"QUESTION POCKET"}</p><h2>{familyProfileId?(ar?"احفظ أسئلة هذا الفرد داخل ملفه فقط.":"Keep this family member’s questions inside their profile."):(ar?"احفظ السؤال قبل أن تنساه.":"Save it before you forget it.")}</h2><textarea value={question} maxLength={180} onChange={e=>setQuestion(e.target.value)} placeholder={ar?"ماذا أريد أن أسأل؟":"What do I want to ask?"}/><button disabled={!question.trim()} onClick={saveQuestion}>{ar?"احفظ السؤال":"Save question"} <Arrow/></button><div className={styles.mentalVisit}><b>{ar?"التغذية والصحة النفسية":"MENTAL HEALTH & NUTRITION"}</b><p>{ar?"اقتراحات أسئلة للتجهيز فقط — لا تفترض تشخيصًا.":"Optional prompts for visit preparation — they do not assume a diagnosis."}</p><select value={mentalPrompt} onChange={e=>setMentalPrompt(e.target.value)}><option value="">{ar?"اختر سؤالًا اختياريًا":"Choose an optional question"}</option>{mentalQuestions.map(x=><option key={x} value={x}>{x}</option>)}</select><button disabled={!mentalPrompt} onClick={addMentalQuestion}>{ar?"أضف السؤال":"Add question"}</button></div>{questions.map(q=><p className={styles.savedQ} key={q.id}>? {q.value}{q.structured&&<button className={styles.questionDelete} onClick={()=>deleteCare(q.id)} aria-label={ar?"حذف السؤال":"Delete question"}>×</button>}</p>)}<p className={styles.safetyNote}>{ar?"هذا الملخص للتذكر والتنظيم ومناقشة المعلومات مع مختص صحي. لا يقدم تشخيصًا أو قرارًا علاجيًا. إذا كانت الحالة عاجلة، استخدم خدمات الطوارئ المحلية.":"This summary is for remembering, organizing and discussing information with a health professional. It does not provide diagnosis or treatment decisions. For urgent concerns, use local emergency services."}</p></aside></div></section></div>
}

export function EasyEditorial({go,add,ar}:{go:(v:View)=>void;add:(t:string,v:string)=>Promise<boolean>|boolean;ar:boolean}){
 const [note,setNote]=useState(""),[saved,setSaved]=useState(false);
 const actions=[["EAT",ar?"الأكل":"Eat","atlas"],["MOVE",ar?"الحركة":"Move","log"],["MEDICINE",ar?"الدواء":"Medicine","visit"],["FEEL",ar?"كيف أشعر":"Feel","log"],["HELP",ar?"مساعدة وتجهيز الزيارة":"Help","visit"]] as const;
 return <div className={styles.page}><section className={styles.easyHero}><p className={styles.kicker}>{ar?"وضع سهل · WELLAGE":"EASY MODE · WELLAGE"}</p><h1>{ar?"الأهم فقط، بخطوات واضحة.":"Only what matters, in clear steps."}</h1><p>{ar?"واجهة أهدأ باختيارات أقل ونص أكبر. مناسبة لأي شخص يفضّل تجربة أبسط، بما في ذلك كبار السن.":"A calmer view with fewer choices and larger text. Useful for anyone who prefers a simpler experience, including older adults."}</p></section><section className={styles.easyActions}>{actions.map(([k,label,target])=><button key={k} onClick={()=>go(target as View)}><small>{k}</small><b>{label}</b><Arrow/></button>)}</section><section className={styles.wellAge}><div><p className={styles.kicker}>{ar?"WELLAGE · اليوم":"WELLAGE · TODAY"}</p><h2>{ar?"ملاحظة واحدة تكفي.":"One note is enough."}</h2><p>{ar?"اكتب ما تريد تذكره عن الأكل أو الشرب أو الحركة أو الدواء أو شعورك. لا توجد درجات أو أهداف إجبارية.":"Keep one thing you want to remember about food, drink, movement, medicine or how you feel. No scores and no compulsory targets."}</p></div><div><textarea maxLength={180} value={note} onChange={e=>{setNote(e.target.value);setSaved(false)}} placeholder={ar?"مثال: شربت كويس اليوم · مشيت قليلًا · عندي سؤال عن دوائي":"e.g. Drank well today · moved a little · I have a medicine question"}/><button disabled={!note.trim()} onClick={async()=>{if(await add("Note",note.trim())){setNote("");setSaved(true)}}}>{saved?(ar?"تم الحفظ":"Saved"):(ar?"احفظ في يومياتي":"Save to my journal")}</button></div></section><section className={styles.wellAge}><div><p className={styles.kicker}>{ar?"WELLAGE · سياق يومي":"WELLAGE · DAILY CONTEXT"}</p><h2>{ar?"خطوات قليلة، لكن مفيدة.":"Small prompts, useful context."}</h2><p>{ar?"اختَر ما يناسب يومك: الشهية، السوائل، سهولة الوصول للأكل، وجبة فيها بروتين، الحركة أو سؤال للدواء. لا توجد درجات ولا تشخيص تلقائي.":"Choose only what fits today: appetite, hydration, food access, a protein-containing meal, movement or a medicine question. No scores and no automatic diagnosis."}</p><ul><li>{ar?"الشهية: هل تغيّرت وما الذي جعل الأكل أسهل؟":"Appetite: did it change, and what made eating easier?"}</li><li>{ar?"السوائل: هل الوصول للشرب سهل اليوم؟":"Hydration: is drinking easy to access today?"}</li><li>{ar?"القوة والوظيفة: ما الحركة التي كانت ممكنة؟":"Strength and function: what movement was possible?"}</li><li>{ar?"الأدوية والدعم: ما السؤال الذي تريد أخذه للزيارة؟":"Medicines and support: what question should come to the visit?"}</li></ul></div></section><section className={styles.easySafety}><b>{ar?"للتذكّر والتنظيم، وليس للتشخيص.":"For remembering and organizing, not diagnosis."}</b><p>{ar?"إذا كنت تحتاج مساعدة طبية عاجلة، استخدم خدمات الطوارئ المحلية بدل الاعتماد على هذه الصفحة.":"If you need urgent medical help, use your local emergency services rather than relying on this page."}</p></section></div>
}

export function AboutEditorial({ar}:{ar:boolean}){return <div className={styles.page}><Hero kicker={ar?"عن إيلاما بلوم":"ABOUT ILAMA BLOOM"} title={ar?"معلومات صحية،":"Health information,"} italic={ar?"بلغة إنسانية.":"made human."} copy={ar?"فكرة بسيطة: المعرفة الغذائية والصحية اليومية يجب أن تكون أسهل في الفهم والتذكر والنقاش الحقيقي.":"A simple idea: everyday nutrition and health information should be easier to understand, remember and bring into real conversations."} img="https://images.pexels.com/photos/5945652/pexels-photo-5945652.jpeg?auto=compress&cs=tinysrgb&w=1600"/>
 <section className={styles.about}><div><p className={styles.kicker}>{ar?"فلسفتنا":"OUR PHILOSOPHY"}</p><h2>{ar?"افهم · تذكّر · ناقش":"Understand · Remember · Discuss"}</h2><p>{ar?"إيلاما بلوم يضع الطعام والجسد والسياق في صورة واحدة، بعيدًا عن ثقافة الدايت والأحكام والتعقيد غير الضروري.":"ILAMA BLOOM brings food, body and context into one picture — away from diet culture, judgement and unnecessary complexity."}</p></div><aside><p className={styles.kicker}>{ar?"الصوت الطبي":"CLINICAL VOICE"}</p><h3>{ar?"د. دينا حسن":"Dr. Dina Hassan"}</h3><b>{ar?"طب الأطفال · التغذية العلاجية":"Pediatrics · Clinical Nutrition"}</b><p>MRCPCH · Final examination September 2026 · result pending</p><p>{ar?"دبلومة التغذية العلاجية · NNI":"Diploma in Clinical Nutrition · NNI"}</p></aside></section></div>}

export function PrivacyEditorial({ar}:{ar:boolean}){const rows=ar?[["01","ما الذي نحفظه","بيانات الملف الشخصي التي تختار إضافتها، وسجلات اليوميات، وتقدم الألعاب المدعوم يمكن حفظها مع حسابك."],["02","تحكمك","يمكنك تعديل سجلات اليوميات أو حذفها أو مسحها، وتعديل ملفك الشخصي من مساحة My ILAMA."],["03","الحجز","عند فتح Calendly من My ILAMA، يتم تمرير الاسم والبريد الإلكتروني فقط للتعبئة المسبقة. لا نرسل السياق الصحي إلى Calendly."],["04","الغرض","المعلومات التعليمية وأدوات التسجيل لا تستبدل التقييم أو التشخيص أو العلاج الطبي."],["05","ملفات العائلة","كل ملف عائلي مرتبط بحساب المالك النشط، وسجلات الرعاية تُحفظ مع الملف المختار بدل خلط أفراد العائلة."]]:[["01","What we store","Profile information you choose to add, journal entries and supported game progress can be stored with your account."],["02","Your control","You can edit or delete journal entries, clear them, and update your profile from My ILAMA."],["03","Booking","When Calendly opens inside My ILAMA, only your name and email are passed for prefilling. Health context is not sent to Calendly."],["04","Purpose","Educational information and tracking tools do not replace medical assessment, diagnosis or treatment."],["05","Family profiles","Each family profile is tied to the owning account, and Care records stay with the selected profile rather than mixing family members."]];return <div className={styles.page}><Hero kicker={ar?"الخصوصية":"PRIVACY"} title={ar?"بياناتك،":"Your data,"} italic={ar?"بوضوح.":"clearly."} copy={ar?"نستخدم بيانات الحساب واليوميات فقط لتقديم الخصائص التي تختار استخدامها.":"We use account and journal data to provide the features you choose to use."} img="https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&w=1600"/><section className={styles.policy}>{rows.map(([n,t,c])=><article key={n}><span>{n}</span><h2>{t}</h2><p>{c}</p></article>)}</section></div>}

export function SitemapEditorial({go,ar}:{go:(v:View)=>void;ar:boolean}){const links:(readonly [string,string,View])[]=[ar?["التغذية","المكتبة والأدلة","learn"]:["Nutrition","Library & guides","learn"],ar?["الأطفال","التعلم والألعاب","kids"]:["Kids","Learning & games","kids"],ar?["أطلس الطعام","الأطعمة والحصص","atlas"]:["Food Atlas","Foods & portions","atlas"],ar?["الحياة اليومية","مصر · الميزانية · المراهقون","everyday"]:["Everyday","Egypt · budget · teens","everyday"],ar?["عدسة الطعام","حساب البطاقة","lens"]:["Food Lens","Label calculator","lens"],ar?["اليوميات","سجلاتك الخاصة","journal"]:["Journal","Your private notes","journal"],ar?["إزهار الأسبوع","آخر 7 أيام، بلا درجات","weekly"]:["Weekly Bloom","Seven days, without scores","weekly"],ar?["تجهيز الزيارة","السياق والأسئلة","visit"]:["Visit Prep","Context & questions","visit"],ar?["عن إيلاما","الفكرة والفلسفة","about"]:["About","Idea & philosophy","about"]];return <div className={styles.page}><Hero kicker={ar?"خريطة الموقع":"SITE MAP"} title={ar?"كل شيء،":"Everything,"} italic={ar?"سهل الوصول.":"easy to find."} copy={ar?"اذهب مباشرة إلى أي مساحة داخل إيلاما بلوم.":"Jump directly to any space inside ILAMA BLOOM."} img="https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=1600"/><section className={styles.mapGrid}>{links.map(([t,c,v],i)=><button key={t} onClick={()=>go(v)}><span>0{i+1}</span><h2>{t}</h2><p>{c}</p><Arrow/></button>)}</section></div>}
