"use client";
import {useEffect,useState} from "react";
import styles from "./FoodAtlasEditorial.module.css";
type Food={id:string;name:string;name_en?:string;category:string;portion:string;portion_ar?:string;carbohydrate:string;source?:string;confidence?:string};
const catAr:{[k:string]:string}={All:"الكل","Bread & grains":"خبز وحبوب",Legumes:"بقوليات","Mixed dishes":"أطباق مختلطة",Starches:"نشويات",Pastries:"مخبوزات",Sweets:"حلويات",Dairy:"ألبان",Fruit:"فاكهة",Vegetables:"خضار",Drinks:"مشروبات"};
const en:{[k:string]:string}={"عيش بلدي":"Baladi bread","عيش شامي":"Shami bread","فول مدمس":"Ful medames","طعمية":"Taameya","أرز مطبوخ":"Cooked rice","رز بالشعرية":"Rice with vermicelli","مكرونة مطبوخة":"Cooked pasta","فريك":"Freekeh","برغل":"Bulgur","كشري":"Koshari","محشي":"Mahshi","محشي ورق عنب":"Stuffed vine leaves","محشي كرنب":"Stuffed cabbage","محشي كوسة":"Stuffed zucchini","حواوشي":"Hawawshi","فتة":"Fattah","ملوخية":"Molokhia","بطاطس مسلوقة":"Boiled potato","بطاطا":"Sweet potato","ذرة":"Corn","بسلة":"Peas","عدس":"Lentils","شوربة عدس":"Lentil soup","فاصوليا بيضا":"White beans","حمص":"Chickpeas","فطير مشلتت":"Feteer meshaltet","بسبوسة":"Basbousa","قطايف":"Qatayef","كنافة":"Konafa","أم علي":"Om Ali","أرز باللبن":"Rice pudding","كحك":"Kahk","زبادي سادة":"Plain yogurt","لبن":"Milk","تفاح":"Apple","موز":"Banana","برتقال":"Orange","مانجو":"Mango","عنب":"Grapes","بطيخ":"Watermelon","بلح / تمر":"Dates"};
const portions:{[k:string]:string}={"1 medium piece":"قطعة متوسطة","½ cup":"نصف كوب","3 pieces":"٣ قطع","⅓ cup":"ثلث كوب","1 plate":"طبق واحد","6 small pieces":"٦ قطع صغيرة","1 small":"واحدة صغيرة","½ cup cooked":"نصف كوب مطبوخ","1 small piece":"قطعة صغيرة","1 small cup":"كوب صغير"};
const photosByCategory:{[k:string]:string}={"Bread & grains":"https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=900",Legumes:"https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=900","Mixed dishes":"https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=900",Starches:"https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg?auto=compress&cs=tinysrgb&w=900",Pastries:"https://images.pexels.com/photos/2135/food-france-morning-breakfast.jpg?auto=compress&cs=tinysrgb&w=900",Sweets:"https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?auto=compress&cs=tinysrgb&w=900",Dairy:"https://images.pexels.com/photos/5946720/pexels-photo-5946720.jpeg?auto=compress&cs=tinysrgb&w=900",Fruit:"https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=900",Vegetables:"https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=900",Drinks:"https://images.pexels.com/photos/416528/pexels-photo-416528.jpeg?auto=compress&cs=tinysrgb&w=900"}; const photo=(f:Food)=>photosByCategory[f.category]||photosByCategory["Mixed dishes"];
export default function FoodAtlasEditorial({add,go,ar}:{add:(t:string,v:string)=>Promise<boolean>|boolean;go:(v:any)=>void;ar:boolean}){
 const [foods,setFoods]=useState<Food[]>([]),[q,setQ]=useState(""),[category,setCategory]=useState("All"),[loading,setLoading]=useState(true),[error,setError]=useState(false),[saved,setSaved]=useState<string|null>(null);
 useEffect(()=>{fetch("/api/foods").then(r=>r.ok?r.json():null).then(d=>Array.isArray(d?.foods)?setFoods(d.foods):setError(true)).catch(()=>setError(true)).finally(()=>setLoading(false))},[]);
 const cats=["All",...Array.from(new Set(foods.map(f=>f.category)))]; const shown=foods.filter(f=>(category==="All"||f.category===category)&&`${f.name} ${en[f.name]||""} ${f.category}`.toLowerCase().includes(q.toLowerCase())); const name=(f:Food)=>ar?f.name:(f.name_en||en[f.name]||f.name),portion=(f:Food)=>ar?(f.portion_ar||portions[f.portion]||f.portion):f.portion;
 return <div className={styles.page}><section className={styles.hero}><div><p className={styles.kicker}>{ar?"أطلس الطعام المصري":"EGYPTIAN FOOD ATLAS"}</p><h1>{ar?<>طعام مألوف.<br/><em>سياق أوضح.</em></>:<>Familiar food.<br/><em>Clearer context.</em></>}</h1><p>{ar?"مرجع بصري للطعام الذي نأكله فعلًا — حصص، كربوهيدرات وسياق بلغة واضحة.":"A visual reference for food we actually eat — portions, carbohydrate and context in plain language."}</p></div><figure><img src="https://images.pexels.com/photos/5945641/pexels-photo-5945641.jpeg?auto=compress&cs=tinysrgb&w=1800" alt=""/></figure></section>
 <section className={styles.controls}><div className={styles.search}><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?"ابحث: كشري، عيش، فول...":"Search koshari, bread, ful..."}/>{q&&<button onClick={()=>setQ("")}>×</button>}</div><div className={styles.cats}>{cats.map(c=><button className={category===c?styles.active:""} onClick={()=>setCategory(c)} key={c}>{ar?(catAr[c]||c):c}</button>)}</div></section>
 {loading?<div className={styles.state}>{ar?"جاري تحميل الأطلس…":"Loading the atlas…"}</div>:error?<div className={styles.state}>{ar?"الأطلس غير متاح مؤقتًا.":"The atlas is temporarily unavailable."}</div>:<section className={styles.grid}>{shown.map((f,i)=><article key={f.id}><figure><img src={photo(f)} alt=""/></figure><div><p className={styles.kicker}>{ar?(catAr[f.category]||f.category):f.category}</p><h2>{name(f)}</h2><dl><div><dt>{ar?"الحصة":"PORTION"}</dt><dd>{portion(f)}</dd></div><div><dt>{ar?"الكربوهيدرات":"CARBOHYDRATE"}</dt><dd>{f.carbohydrate}</dd></div></dl><p className={styles.meta}>{ar?"القيم مرجع تعليمي وقد تختلف حسب الوصفة والمنتج.":"Educational reference; values can vary by recipe and product."}</p><button onClick={async()=>{if(await add("Food",`${name(f)} · ${portion(f)} · ${f.carbohydrate} carbohydrate reference`)){setSaved(f.id);setTimeout(()=>setSaved(null),1500)}}}>{saved===f.id?(ar?"تم الحفظ ✓":"Saved ✓"):(ar?"احتفظ بها":"Remember")} <span>→</span></button></div></article>)}</section>}
 {!loading&&!error&&!shown.length&&<div className={styles.state}>{ar?"لا توجد نتيجة مطابقة.":"No matching food found."}</div>}
 <section className={styles.gentleCollection}><div><p className={styles.kicker}>GENTLE EATING · {ar?"أيام الطاقة القليلة":"LOW-CAPACITY DAYS"}</p><h2>{ar?"الأكل العملي له قيمة.":"Practical food still counts."}</h2><p>{ar?"لما الطبخ أو التنظيم يكون صعب، ابدأ بأكل مألوف ومتاح ومقبول بالنسبة لك. الهدف هنا تسهيل الأكل، مش وصف «دايت للصحة النفسية».":"When cooking or planning feels difficult, start with familiar, available food you can tolerate. The goal is to make eating easier — not prescribe a “mental-health diet.”"}</p></div><div><button onClick={()=>{setCategory("Dairy");setQ("")}}>{ar?"ألبان سهلة":"Easy dairy"}</button><button onClick={()=>{setCategory("Fruit");setQ("")}}>{ar?"فاكهة":"Fruit"}</button><button onClick={()=>{setCategory("Bread & grains");setQ("")}}>{ar?"خبز وحبوب":"Bread & grains"}</button><button onClick={()=>{setCategory("Legumes");setQ("")}}>{ar?"بقوليات":"Legumes"}</button><button onClick={()=>go("mind")}>{ar?"ارجع إلى Gentle Eating":"Open Gentle Eating"} →</button></div></section>
 <section className={styles.bridge}><div><p className={styles.kicker}>{ar?"هل معك العبوة؟":"HAVE THE PACK?"}</p><h2>{ar?"استخدم البطاقة الفعلية عندما تستطيع.":"Use the actual label when you can."}</h2></div><button onClick={()=>go("lens")}>{ar?"افتح عدسة الطعام":"Open Food Lens"} <span>→</span></button></section></div>
}