"use client";
import {useEffect,useState} from "react";
import styles from "./FoodAtlasEditorial.module.css";
import {FOOD_ATLAS_GOVERNANCE} from "../lib/content-governance";
type Food={id:string;name:string;name_en?:string;category:string;portion:string;portion_ar?:string;carbohydrate:string;source?:string;confidence?:string};
const atlasTags:{[k:string]:string[]}={"عيش بلدي":["portable","budget","family"],"عيش شامي":["portable","budget","school/work"],"فول مدمس":["budget","family","low-capacity"],"طعمية":["portable","budget","school/work"],"كشري":["budget","family","work"],"محشي":["family","seasonal"],"حواوشي":["portable","work"],"زبادي سادة":["quick","low-capacity","school/work"],"لبن":["quick","low-capacity","school/work"],"موز":["no-cook","portable","quick","low-capacity"],"تفاح":["no-cook","portable","school/work"],"برتقال":["no-cook","seasonal"],"عدس":["budget","family","low-capacity"],"بطاطس مسلوقة":["budget","low-capacity","family"],"حمص":["no-cook","portable","budget"],"شوربة عدس":["low-capacity","budget","family"]};
const tagLabels:{[k:string]:string[]}={all:["All","الكل"],"no-cook":["No-cook","بدون طبخ"],quick:["Quick","سريع"],portable:["Portable","سهل الحمل"],budget:["Budget","اقتصادي"],"low-capacity":["Low-capacity","قدرة قليلة"],family:["Family","عائلي"],"school/work":["School / work","مدرسة / شغل"],seasonal:["Seasonal","موسمي"]};
const catAr:{[k:string]:string}={All:"الكل","Bread & grains":"خبز وحبوب",Legumes:"بقوليات","Mixed dishes":"أطباق مختلطة",Starches:"نشويات",Pastries:"مخبوزات",Sweets:"حلويات",Dairy:"ألبان",Fruit:"فاكهة",Vegetables:"خضار",Drinks:"مشروبات"};
const en:{[k:string]:string}={"عيش بلدي":"Baladi bread","عيش شامي":"Shami bread","فول مدمس":"Ful medames","طعمية":"Taameya","أرز مطبوخ":"Cooked rice","رز بالشعرية":"Rice with vermicelli","مكرونة مطبوخة":"Cooked pasta","فريك":"Freekeh","برغل":"Bulgur","كشري":"Koshari","محشي":"Mahshi","محشي ورق عنب":"Stuffed vine leaves","محشي كرنب":"Stuffed cabbage","محشي كوسة":"Stuffed zucchini","حواوشي":"Hawawshi","فتة":"Fattah","ملوخية":"Molokhia","بطاطس مسلوقة":"Boiled potato","بطاطا":"Sweet potato","ذرة":"Corn","بسلة":"Peas","عدس":"Lentils","شوربة عدس":"Lentil soup","فاصوليا بيضا":"White beans","حمص":"Chickpeas","فطير مشلتت":"Feteer meshaltet","بسبوسة":"Basbousa","قطايف":"Qatayef","كنافة":"Konafa","أم علي":"Om Ali","أرز باللبن":"Rice pudding","كحك":"Kahk","زبادي سادة":"Plain yogurt","لبن":"Milk","تفاح":"Apple","موز":"Banana","برتقال":"Orange","مانجو":"Mango","عنب":"Grapes","بطيخ":"Watermelon","بلح / تمر":"Dates"};
const portions:{[k:string]:string}={"1 medium piece":"قطعة متوسطة","½ cup":"نصف كوب","3 pieces":"٣ قطع","⅓ cup":"ثلث كوب","1 plate":"طبق واحد","6 small pieces":"٦ قطع صغيرة","1 small":"واحدة صغيرة","½ cup cooked":"نصف كوب مطبوخ","1 small piece":"قطعة صغيرة","1 small cup":"كوب صغير"};
const photosByCategory:{[k:string]:string}={"Bread & grains":"https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=900",Legumes:"https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=900","Mixed dishes":"https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=900",Starches:"https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg?auto=compress&cs=tinysrgb&w=900",Pastries:"https://images.pexels.com/photos/2135/food-france-morning-breakfast.jpg?auto=compress&cs=tinysrgb&w=900",Sweets:"https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?auto=compress&cs=tinysrgb&w=900",Dairy:"https://images.pexels.com/photos/5946720/pexels-photo-5946720.jpeg?auto=compress&cs=tinysrgb&w=900",Fruit:"https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=900",Vegetables:"https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=900",Drinks:"https://images.pexels.com/photos/416528/pexels-photo-416528.jpeg?auto=compress&cs=tinysrgb&w=900"}; const photo=(f:Food)=>photosByCategory[f.category]||photosByCategory["Mixed dishes"];
export default function FoodAtlasEditorial({add,go,ar}:{add:(t:string,v:string)=>Promise<boolean>|boolean;go:(v:any)=>void;ar:boolean}){
 const [foods,setFoods]=useState<Food[]>([]),[q,setQ]=useState(""),[category,setCategory]=useState("All"),[atlasTag,setAtlasTag]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState(false),[saved,setSaved]=useState<string|null>(null),[gentle,setGentle]=useState<"all"|"nocook"|"five"|"low"|"sensory"|"budget"|"work">("all");
 useEffect(()=>{fetch("/api/foods").then(r=>r.ok?r.json():null).then(d=>Array.isArray(d?.foods)?setFoods(d.foods):setError(true)).catch(()=>setError(true)).finally(()=>setLoading(false))},[]);
 const cats=["All",...Array.from(new Set(foods.map(f=>f.category)))]; const tagsFor=(f:Food)=>atlasTags[f.name]||[]; const shown=foods.filter(f=>(category==="All"||f.category===category)&&(atlasTag==="all"||tagsFor(f).includes(atlasTag))&&`${f.name} ${en[f.name]||""} ${f.category}`.toLowerCase().includes(q.toLowerCase())); const name=(f:Food)=>ar?f.name:(f.name_en||en[f.name]||f.name),portion=(f:Food)=>ar?(f.portion_ar||portions[f.portion]||f.portion):f.portion;
 return <div className={styles.page} data-content-review={FOOD_ATLAS_GOVERNANCE.reviewStatus} data-reviewed-date={FOOD_ATLAS_GOVERNANCE.reviewedDate}><section className={styles.hero}><div><p className={styles.kicker}>{ar?"أطلس الطعام المصري":"EGYPTIAN FOOD ATLAS"}</p><h1>{ar?<>طعام مألوف.<br/><em>سياق أوضح.</em></>:<>Familiar food.<br/><em>Clearer context.</em></>}</h1><p>{ar?"مرجع بصري للطعام الذي نأكله فعلًا — حصص، كربوهيدرات وسياق بلغة واضحة.":"A visual reference for food we actually eat — portions, carbohydrate and context in plain language."}</p></div><figure><img src="https://images.pexels.com/photos/5945641/pexels-photo-5945641.jpeg?auto=compress&cs=tinysrgb&w=1800" alt=""/></figure></section>
 <section className={styles.controls}><div className={styles.search}><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?"ابحث: كشري، عيش، فول...":"Search koshari, bread, ful..."}/>{q&&<button onClick={()=>setQ("")}>×</button>}</div><div className={styles.cats}>{cats.map(c=><button className={category===c?styles.active:""} onClick={()=>setCategory(c)} key={c}>{ar?(catAr[c]||c):c}</button>)}</div><nav aria-label={ar?"سياق الطعام":"Food context"} className={styles.cats}>{Object.entries(tagLabels).map(([k,label])=><button className={atlasTag===k?styles.active:""} onClick={()=>setAtlasTag(k)} key={k}>{ar?label[1]:label[0]}</button>)}</nav></section>
 {loading?<div className={styles.state}>{ar?"جاري تحميل الأطلس…":"Loading the atlas…"}</div>:error?<div className={styles.state}>{ar?"الأطلس غير متاح مؤقتًا.":"The atlas is temporarily unavailable."}</div>:<section className={styles.grid}>{shown.map((f,i)=><article key={f.id}><figure><img src={photo(f)} alt=""/></figure><div><p className={styles.kicker}>{ar?(catAr[f.category]||f.category):f.category}</p><h2>{name(f)}</h2><dl><div><dt>{ar?"الحصة":"PORTION"}</dt><dd>{portion(f)}</dd></div><div><dt>{ar?"الكربوهيدرات":"CARBOHYDRATE"}</dt><dd>{f.carbohydrate}</dd></div></dl><p className={styles.meta}>{ar?"القيم مرجع تعليمي وقد تختلف حسب الوصفة والمنتج.":"Educational reference; values can vary by recipe and product."}</p><button onClick={async()=>{if(await add("Food",`${name(f)} · ${portion(f)} · ${f.carbohydrate} carbohydrate reference`)){setSaved(f.id);setTimeout(()=>setSaved(null),1500)}}}>{saved===f.id?(ar?"تم الحفظ ✓":"Saved ✓"):(ar?"احتفظ بها":"Remember")} <span>→</span></button></div></article>)}</section>}
 {!loading&&!error&&!shown.length&&<div className={styles.state}>{ar?"لا توجد نتيجة مطابقة.":"No matching food found."}</div>}
 <section className={styles.gentleCollection}><div><p className={styles.kicker}>GENTLE EATING · {ar?"أيام الطاقة أو الشهية القليلة":"LOW-CAPACITY OR LOW-APPETITE DAYS"}</p><h2>{ar?"الأكل العملي له قيمة.":"Practical food still counts."}</h2><p>{ar?"اختار حسب القدرة المتاحة اليوم، مش حسب فكرة «الوجبة المثالية». أمثلة مصرية مألوفة تساعدك تبدأ؛ ليست حمية علاجية ولا بديلًا للرعاية.":"Choose for the capacity you have today, not an “ideal meal.” Familiar Egyptian examples can help you start; this is not a therapeutic diet or a substitute for care."}</p><nav className={styles.gentleFilters}>{[["all","All","الكل"],["nocook","No-cook","بدون طبخ"],["five","5-minute","٥ دقائق"],["low","Low appetite","شهية قليلة"],["sensory","Sensory-friendly","مريح حسيًا"],["budget","Budget","اقتصادي"],["work","Work / school","شغل / مدرسة"]].map(([k,en,ara])=><button className={gentle===k?styles.gentleActive:""} key={k} onClick={()=>setGentle(k as any)}>{ar?ara:en}</button>)}</nav></div><div className={styles.gentleIdeas}>{({all:[["زبادي + موز","Yogurt + banana"],["عيش بلدي + جبنة","Baladi bread + cheese"],["فول + عيش","Ful + bread"],["لبن + فاكهة","Milk + fruit"]],nocook:[["زبادي + فاكهة","Yogurt + fruit"],["عيش + جبنة + خيار","Bread + cheese + cucumber"],["لبن + موز","Milk + banana"]],five:[["بيض + عيش","Eggs + bread"],["فول جاهز + عيش","Ready ful + bread"],["زبادي + شوفان","Yogurt + oats"]],low:[["زبادي","Yogurt"],["موز","Banana"],["شوربة عدس","Lentil soup"],["لبن","Milk"]],sensory:[["عيش محمص + جبنة","Toast + cheese"],["زبادي سادة","Plain yogurt"],["موز","Banana"],["أرز سادة","Plain rice"]],budget:[["فول + عيش","Ful + bread"],["عدس","Lentils"],["بيض + عيش","Eggs + bread"],["بطاطس مسلوقة","Boiled potato"]],work:[["ساندوتش جبنة","Cheese sandwich"],["موز + زبادي","Banana + yogurt"],["حمص + عيش","Chickpeas + bread"],["فاكهة موسمية","Seasonal fruit"]]} as any)[gentle].map((x:string[])=><button key={x[0]} onClick={()=>{setCategory("All");setQ(x[0].split(" + ")[0])}}><b>{ar?x[0]:x[1]}</b><small>{ar?"ابحث في الأطلس":"Find in Atlas"} →</small></button>)}</div><button className={styles.backMind} onClick={()=>go("mind")}>{ar?"ارجع إلى Gentle Eating":"Open Gentle Eating"} →</button></section>
 <section className={styles.bridge}><div><p className={styles.kicker}>{ar?"هل معك العبوة؟":"HAVE THE PACK?"}</p><h2>{ar?"استخدم البطاقة الفعلية عندما تستطيع.":"Use the actual label when you can."}</h2></div><button onClick={()=>go("lens")}>{ar?"افتح عدسة الطعام":"Open Food Lens"} <span>→</span></button></section></div>
}