'use client';
import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,type Dispatch,type SetStateAction,type ReactNode} from 'react';
import {cleanState,isZone,mergeLearning,zones,type KidsProfile,type KidsZone,type Snapshot} from '../lib/kids/domain';
import styles from './KidsJourney.module.css';
type Entry={state:unknown;revision:number;pending:boolean;conflict?:Snapshot};
type Entries=Partial<Record<KidsZone,Entry>>;
type Journey={ar:boolean;userId?:string;scope:string;ready:boolean;entries:Entries;set:(zone:KidsZone,fn:(previous:unknown)=>unknown)=>void;profiles:KidsProfile[];active:KidsProfile|null;select:(id:string)=>void;reload:()=>void;retry:()=>void;resolve:(zone:KidsZone,device:boolean)=>void;error:string;status:'local'|'loading'|'saving'|'saved'|'offline'|'conflict';profileError:boolean};
const Context=createContext<Journey|null>(null);
const legacy:Partial<Record<KidsZone,string>>={world:'ilama-world-stars-v2:',hub:'ilama-kids-hub-v1:',farm:'ilama-farm-v1:',egypt:'ilama-egypt-passport-v1:',discover:'ilama-discoveries-v2:',food:'ilama-discovery-v1:',quests:'ilama-quest-passport-v1:',kitchen:'ilama-kitchen-studio-v1:'};
const readCache=(key:string,userId?:string,childId?:string):Entries=>{
 let x:unknown;try{x=JSON.parse(localStorage.getItem(key)||'null')}catch{}
 const result:Entries={};
 if(x&&typeof x==='object'&&!Array.isArray(x))for(const zone of zones){const raw=(x as Record<string,Entry>)[zone];if(raw&&typeof raw==='object'&&Number.isSafeInteger(raw.revision)&&raw.revision>=0)result[zone]={state:cleanState(zone,raw.state),revision:raw.revision,pending:raw.pending===true}}
 // Keep pre-upgrade device progress in the default account/guest journey. New child profiles start fresh.
 if(!childId)for(const zone of zones){if(result[zone])continue;const oldKey=zone==='world'&&!userId?'ilama-world-stars-v1':legacy[zone]?(legacy[zone]+(userId||'guest')):null;if(oldKey)try{const raw=localStorage.getItem(oldKey);if(raw)result[zone]={state:cleanState(zone,JSON.parse(raw)),revision:0,pending:false}}catch{}}
 return result;
};
async function request(url:string,init:RequestInit={},signal?:AbortSignal){const controller=new AbortController();const abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});const timer=window.setTimeout(abort,9000);try{return await fetch(url,{...init,signal:controller.signal,cache:'no-store'})}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort)}}
export function KidsJourneyProvider({ar,userId,children}:{ar:boolean;userId?:string;children:ReactNode}){
 const [profiles,setProfiles]=useState<KidsProfile[]>([]),[activeId,setActiveId]=useState(''),[profilesLoaded,setProfilesLoaded]=useState(!userId),[profileError,setProfileError]=useState(false),[reloadIndex,setReloadIndex]=useState(0);
 const [entries,setEntries]=useState<Entries>({}),[ready,setReady]=useState(false),[loadedScope,setLoadedScope]=useState(''),[status,setStatus]=useState<Journey['status']>('loading'),[error,setError]=useState(''),[retryIndex,setRetryIndex]=useState(0);
 const active=profiles.find(p=>p.id===activeId)||null;
 const scope=(userId||'guest')+(active?':'+active.id:'');const cacheKey='ilama-journey-v2:'+scope;
 const epoch=useRef(0);const inFlight=useRef(false);const currentScope=useRef(scope);currentScope.current=scope;
 useEffect(()=>{let alive=true;const controller=new AbortController();setProfilesLoaded(!userId);setProfiles([]);setActiveId('');setProfileError(false);
 if(!userId)return()=>{alive=false;controller.abort()};
 void request('/api/kids/profiles',{},controller.signal).then(async r=>{if(!r.ok)throw Error('profiles');const data=await r.json();if(!Array.isArray(data.profiles))throw Error('profiles');if(!alive)return;const items=data.profiles.filter((p:KidsProfile)=>p&&typeof p.id==='string'&&typeof p.nickname==='string');setProfiles(items);let selected:string|null=null;try{selected=localStorage.getItem('ilama-active-child:'+userId)}catch{}setActiveId(selected===''?'':items.some((p:KidsProfile)=>p.id===selected)?selected!:items[0]?.id||'')}).catch(()=>{if(alive)setProfileError(true)}).finally(()=>{if(alive)setProfilesLoaded(true)});
 return()=>{alive=false;controller.abort()};
 },[userId,reloadIndex]);
 useEffect(()=>{if(!profilesLoaded)return;const token=++epoch.current;const controller=new AbortController();inFlight.current=false;setReady(false);setError('');setStatus(active?'loading':'local');const cached=readCache(cacheKey,userId,active?.id);setEntries(cached);
 if(!active){setLoadedScope(scope);setReady(true);
 if(userId)void request('/api/progress',{},controller.signal).then(async r=>{if(!r.ok)return;const data=await r.json();if(epoch.current!==token||!Array.isArray(data.progress))return;const stars=data.progress.filter((p:{completed?:boolean;game_key?:string})=>p.completed&&p.game_key?.startsWith('world:')).map((p:{game_key:string})=>p.game_key.slice(6));setEntries(old=>({...old,world:{state:mergeLearning('world',old.world?.state,stars),revision:0,pending:false}}))}).catch(()=>{});
 return()=>{epoch.current++;controller.abort()}}
 void request('/api/kids/snapshots?childId='+encodeURIComponent(active.id),{},controller.signal).then(async r=>{if(!r.ok)throw Error('load');const data=await r.json();if(!Array.isArray(data.snapshots))throw Error('load');if(epoch.current!==token)return;const next={...cached};let conflict=false;
 for(const raw of data.snapshots as Snapshot[]){if(!raw||!isZone(raw.zone)||!Number.isSafeInteger(raw.revision)||raw.revision<1)continue;const remote={...raw,state:cleanState(raw.zone,raw.state)},local=next[raw.zone];
 if(local?.pending&&local.revision!==remote.revision){const merged=mergeLearning(raw.zone,local.state,remote.state);if(merged===null){next[raw.zone]={...local,conflict:remote};conflict=true}else next[raw.zone]={state:merged,revision:remote.revision,pending:true}}
 else next[raw.zone]=local?.pending?local:{state:remote.state,revision:remote.revision,pending:false};
 }
 setEntries(next);setStatus(conflict?'conflict':'saved');
 }).catch(()=>{if(epoch.current===token){setStatus('offline');setError(ar?'اللعب متاح، لكن مزامنة التقدم غير متاحة حاليًا.':'Play is available, but progress sync is temporarily unavailable.')}}).finally(()=>{if(epoch.current===token){setLoadedScope(scope);setReady(true)}});
 return()=>{epoch.current++;controller.abort()};
 },[cacheKey,profilesLoaded,active?.id,userId,retryIndex]);
 useEffect(()=>{if(!ready||loadedScope!==scope)return;try{localStorage.setItem(cacheKey,JSON.stringify(entries))}catch{setError(ar?'التخزين على الجهاز غير متاح. حافظ على الصفحة مفتوحة أثناء اللعب.':'Device storage is unavailable. Keep this page open while playing.')}},[cacheKey,ready,loadedScope,scope,entries,ar]);
 useEffect(()=>{if(!ready||!active||status==='offline'||inFlight.current)return;const candidate=zones.find(z=>entries[z]?.pending&&!entries[z]?.conflict);if(!candidate)return;
 const token=epoch.current;const childId=active.id;const entry=entries[candidate]!;const timer=window.setTimeout(()=>{inFlight.current=true;setStatus('saving');
 void request('/api/kids/snapshots',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({childId,zone:candidate,state:entry.state,revision:entry.revision})}).then(async r=>{const data=await r.json();if(epoch.current!==token)return;if(r.status===409&&data.snapshot){const remote=data.snapshot as Snapshot;setEntries(old=>{const current=old[candidate];if(!current)return old;const merged=mergeLearning(candidate,current.state,remote.state);return {...old,[candidate]:merged===null?{...current,conflict:remote}:{state:merged,revision:remote.revision,pending:true}}});setStatus('conflict');return}if(!r.ok||!data.snapshot)throw Error('save');const saved=data.snapshot as Snapshot;setEntries(old=>{const current=old[candidate];if(!current)return old;return {...old,[candidate]:{state:current.state,revision:saved.revision,pending:JSON.stringify(current.state)!==JSON.stringify(entry.state)}}});setStatus('saved');setError('')
 }).catch(()=>{if(epoch.current===token){setStatus('offline');setError(ar?'تعذر الحفظ السحابي؛ التقدم ما زال على الجهاز إذا كان التخزين متاحًا.':'Cloud saving failed; progress remains on this device when storage is available.')}}).finally(()=>{if(epoch.current===token)inFlight.current=false});
 },600);return()=>clearTimeout(timer);
 },[entries,ready,active?.id,status,ar]);
 const set=useCallback((zone:KidsZone,fn:(previous:unknown)=>unknown)=>{if(!ready||loadedScope!==scope||currentScope.current!==scope)return;setEntries(old=>{if(currentScope.current!==scope)return old;const current=old[zone];const state=cleanState(zone,fn(current?.state));if(JSON.stringify(state)===JSON.stringify(current?.state))return old;return {...old,[zone]:{state,revision:current?.revision||0,pending:!!active,conflict:current?.conflict}}})},[ready,loadedScope,scope,active?.id]);
 const select=useCallback((id:string)=>{if(!profiles.some(p=>p.id===id)&&id!=='')return;setActiveId(id);try{localStorage.setItem('ilama-active-child:'+userId,id)}catch{}},[profiles,userId]);
 const resolve=useCallback((zone:KidsZone,device:boolean)=>{setStatus("saved");setEntries(old=>{const e=old[zone];if(!e?.conflict)return old;return {...old,[zone]:{state:device?e.state:e.conflict.state,revision:e.conflict.revision,pending:device}}})},[]);
 const value=useMemo(()=>({ar,userId,scope,ready:ready&&loadedScope===scope,entries:loadedScope===scope?entries:{},set,profiles,active,select,reload:()=>setReloadIndex(n=>n+1),retry:()=>setRetryIndex(n=>n+1),resolve,error,status,profileError}),[ar,userId,scope,ready,loadedScope,entries,set,profiles,active,select,resolve,error,status,profileError]);
 return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useKidsJourney(){const value=useContext(Context);if(!value)throw Error('KidsJourneyProvider is required');return value}
export function useAdventureState<T>(zone:KidsZone,initial:T):[T,Dispatch<SetStateAction<T>>,boolean]{
 const journey=useKidsJourney();const value=(journey.ready?(journey.entries[zone]?.state??initial):initial) as T;
 const set:Dispatch<SetStateAction<T>>=useCallback(next=>journey.set(zone,previous=>typeof next==='function'?(next as (v:T)=>T)((previous??initial) as T):next),[journey.set,zone]);
 return [value,set,journey.ready];
}
export function KidsJourneyToolbar(){
 const j=useKidsJourney(),ar=j.ar;const [editing,setEditing]=useState(false),[editId,setEditId]=useState<string|undefined>(undefined),[nickname,setNickname]=useState(''),[ageBand,setAgeBand]=useState('8-12'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[deleting,setDeleting]=useState(false);
 const t=(a:string,b:string)=>ar?a:b;
 useEffect(()=>{setEditing(false);setDeleting(false);setMessage('')},[j.scope]);
 const save=async()=>{setBusy(true);setMessage('');try{const r=await request('/api/kids/profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editId,nickname,ageBand,consent})});if(!r.ok)throw Error('save');const data=await r.json();try{localStorage.setItem('ilama-active-child:'+j.userId,data.profile.id)}catch{}setEditing(false);setNickname('');setConsent(false);j.reload()}catch{setMessage(t('تعذر إنشاء الملف. راجع الاتصال وحاول مرة أخرى.','Could not create the profile. Check your connection and retry.'))}finally{setBusy(false)}};
 const remove=async()=>{if(!j.active)return;setBusy(true);try{const r=await request('/api/kids/profiles',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:j.active.id})});if(!r.ok)throw Error('delete');try{localStorage.removeItem('ilama-journey-v2:'+j.scope);localStorage.removeItem('ilama-active-child:'+j.userId)}catch{}setDeleting(false);j.reload()}catch{setMessage(t('تعذر الحذف. لم نمسح تقدمك على الجهاز.','Deletion failed. Your device progress was kept.'))}finally{setBusy(false)}};
 const statuses={local:t('اللعب والحفظ على هذا الجهاز.','Play and save on this device.'),loading:t('تحميل رحلتك…','Loading your journey…'),saving:t('جارٍ حفظ الاكتشافات…','Saving discoveries…'),saved:t('التقدم محفوظ في ملف التعلّم.','Progress saved in the learning profile.'),offline:t('الرحلة متاحة بدون اتصال؛ المزامنة تحتاج اتصالًا.','Your journey is available offline; sync needs a connection.'),conflict:t('هناك تقدم مختلف على جهاز آخر.','Another device has different progress.')};
 return <section id="kids-family-space" className={styles.panel} aria-label={t('مساحة رحلة الأسرة','Family journey space')}>
 <div className={styles.top}><h2>{t('🌿 رحلة تخص كل طفل','🌿 A journey for each child')}</h2><a href={'/parent?lang='+(ar?'ar':'en')}>{t('مساحة الأهل','For parents')}</a></div>
 <p>{t('اسم مستعار وفئة عمرية فقط. لا صور شخصية ولا تاريخ ميلاد ولا بيانات عن الجسم.','A nickname and age band only. No profile photo, birth date or body measurements.')}</p>
 {j.userId?<div className={styles.tools}><label>{t('ملف التعلّم','Learning profile')} <select aria-label={t('اختار ملف الطفل','Choose child profile')} value={j.active?.id||''} disabled={!j.ready||busy} onChange={e=>j.select(e.target.value)}><option value="">{t('رحلة الحساب الحالية على الجهاز','Current account journey on this device')}</option>{j.profiles.map(p=><option key={p.id} value={p.id}>{p.nickname}</option>)}</select></label><button type="button" disabled={busy||j.profileError||j.profiles.length>=5} onClick={()=>{setEditId(undefined);setNickname("");setEditing(v=>!v);setConsent(false)}} aria-expanded={editing}>{t('إضافة ملف طفل','Add child profile')}</button>{j.active&&<button type="button" disabled={busy} onClick={()=>{setEditId(j.active!.id);setNickname(j.active!.nickname);setAgeBand(j.active!.age_band);setConsent(false);setEditing(true)}}>{t('تعديل الملف','Edit profile')}</button>}{j.active&&<button type="button" disabled={busy} className={styles.danger} onClick={()=>setDeleting(v=>!v)} aria-expanded={deleting}>{t('حذف هذا الملف','Delete this profile')}</button>}</div>:<p><a href={'/auth/sign-in?next=%2Fkids&lang='+(ar?'ar':'en')}>{t('دخول ولي الأمر للحفظ بين الأجهزة','Guardian sign-in to save across devices')}</a></p>}
 {j.profileError&&<div className={styles.notice}><p>{t('ملفات الأسرة غير متاحة مؤقتًا؛ رحلة الجهاز ما زالت متاحة.','Family profiles are temporarily unavailable; the device journey is still available.')}</p><button type="button" onClick={j.reload}>{t('إعادة تحميل الملفات','Reload profiles')}</button></div>}
 <p role="status" aria-live="polite" className={styles.status}>{statuses[j.status]} {j.error}</p>
 {j.status==='offline'&&<button type="button" onClick={j.retry}>{t('حاول المزامنة مرة أخرى','Retry sync')}</button>}
 {editing&&<form onSubmit={e=>{e.preventDefault();void save()}} className={styles.form}><label>{t('اسم مستعار','Nickname')}<input required maxLength={40} value={nickname} onChange={e=>setNickname(e.target.value)} autoComplete="off"/></label><label>{t('الفئة العمرية','Age band')}<select value={ageBand} onChange={e=>setAgeBand(e.target.value)}><option value="under-8">{t('أقل من ٨','Under 8')}</option><option value="8-12">{t('٨–١٢','8–12')}</option><option value="13-17">{t('١٣–١٧','13–17')}</option></select></label><label className={styles.consent}><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{t('أنا ولي الأمر وأوافق على حفظ ملف التعلّم والتقدم بصورة خاصة.','I am the guardian and consent to private learning profile and progress storage.')}</span></label><button className={styles.primary} disabled={busy||!consent||!nickname.trim()}>{busy?t('جارٍ الحفظ…','Saving…'):editId?t('احفظ تعديل الملف','Save profile changes'):t('احفظ الملف الجديد','Save new profile')}</button></form>}
 {deleting&&<div className={styles.notice}><p>{t('سيتم حذف ملف الطفل وكل تقدم المغامرات المحفوظ في هذا الملف من الحساب والجهاز الحالي. لا يمكن التراجع عن الحذف.','This deletes this child profile and its adventure progress from the account and this device. Deletion cannot be undone.')}</p><div className={styles.tools}><button type="button" disabled={busy} className={styles.danger} onClick={remove}>{t('تأكيد حذف الملف والتقدم','Confirm profile and progress deletion')}</button><button type="button" onClick={()=>setDeleting(false)}>{t('إلغاء','Cancel')}</button></div></div>}
 {zones.filter(z=>j.entries[z]?.conflict).map(zone=><div key={zone} className={styles.conflict}><p>{t('اكتشفنا اختلافًا في تقدم نشاط. اختار النسخة التي تريد الاحتفاظ بها.','An activity has different saved progress. Choose which version to keep.')}</p><div className={styles.tools}><button type="button" onClick={()=>j.resolve(zone,false)}>{t('استخدم النسخة المحفوظة في الحساب','Use the account version')}</button><button type="button" onClick={()=>j.resolve(zone,true)}>{t('احتفظ بنسخة هذا الجهاز','Keep this device version')}</button></div></div>)}
 {message&&<p role="status">{message}</p>}
 </section>;
}
export function KidsParentSummary(){const j=useKidsJourney();return <section className={styles.panel} aria-label={j.ar?'ملخص الاكتشافات':'Discovery summary'}><h2>{j.ar?'الاكتشافات، بدون مقارنة':'Discoveries, without comparison'}</h2><p>{j.ar?'التقدم يسجل الأنشطة، وليس تقييم الطفل أو صحته.':'Progress records activities, not a rating of a child or their health.'}</p><div className={styles.summary}>{[{zone:'egypt',ar:'محطات مصر',en:'Egypt stops'},{zone:'aqua',ar:'أنواع السمك',en:'Fish discoveries'},{zone:'movement',ar:'مغامرات الحركة',en:'Movement adventures'},{zone:'food',ar:'رحلات الطعام',en:'Food journeys'}].map(x=>{const state=j.entries[x.zone as KidsZone]?.state;return <article key={x.zone}><h3>{j.ar?x.ar:x.en}</h3><p>{Array.isArray(state)?state.length:0} {j.ar?'اكتشافات محفوظة':'saved discoveries'}</p></article>})}</div><p><a href={'/kids?lang='+(j.ar?'ar':'en')}>{j.ar?'العودة للعب ←':'Return to adventures →'}</a></p></section>}

export function KidsJourneyTrails(){
 const j=useKidsJourney();const ar=j.ar;
 const go=(zone:'farm'|'aqua'|'egypt'|'move')=>{j.set('hub',previous=>{const p=cleanState('hub',previous) as {zone:string;visited:string[];achievements:string[]};return {...p,zone,visited:[...p.visited,zone]}});document.getElementById('kids-adventure-hub')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})};
 const trails=[{zone:'farm' as const,icon:'🌱',ar:'من البذرة إلى الطبق',en:'From seed to plate',arSteps:'ازرع، احصد، ثم كوّن فكرة وجبة مع تيتا.',enSteps:'Plant, harvest, then build a meal idea with Grandma.',next:'#kids-kitchen-studio'},{zone:'aqua' as const,icon:'🐟',ar:'رحلة النيل والبحر',en:'Nile and sea journey',arSteps:'اكتشف سمكة، وتعرف على موطنها، ثم افتح حكاية السمك.',enSteps:'Discover a fish, explore its habitat, then try the fish story.',next:'#kids-quest-trail'},{zone:'egypt' as const,icon:'🗺️',ar:'مستكشف مصر',en:'Egypt explorer',arSteps:'اختار محافظة، واكتشف محصولًا، واحكِ لأسرتك.',enSteps:'Choose a governorate, discover a crop and share with family.',next:'#kids-food-discovery'},{zone:'move' as const,icon:'🦋',ar:'اتحرك ولاحظ الطبيعة',en:'Move and notice nature',arSteps:'اختار حركة مناسبة ثم خد راحة أو لاحظ نباتًا حقيقيًا.',enSteps:'Choose a comfortable move, then rest or notice a real plant.',next:'#kids-weather-lab'}];
 return <section className={styles.panel} aria-label={ar?'مسارات اكتشاف اختيارية':'Optional discovery trails'}><h2>{ar?'🎒 اختار حكاية لرحلتك':'🎒 Choose a story for your journey'}</h2><p>{ar?'كل مسار اقتراح لطيف، مش قائمة واجبات. تقدر تبدأ من أي مكان وتوقف وقت ما تحب.':'Each trail is a gentle suggestion, not homework. Start anywhere and stop whenever you like.'}</p><div className={styles.mission}>{trails.map(trail=><article key={trail.zone}><button type="button" disabled={!j.ready} className={`${styles.primary} ${styles.trailButton}`} onClick={()=>go(trail.zone)}><span className={styles.trailTitle}>{trail.icon} {ar?trail.ar:trail.en}</span><span className={styles.trailDescription}>{ar?trail.arSteps:trail.enSteps}</span></button><a href={trail.next}>{ar?'المحطة المرتبطة ←':'Related destination →'}</a></article>)}</div></section>;
}
