"use client";
import {useEffect,useState} from "react";
import styles from "./KidsEditorial.module.css";
type Mission={id:string;title_en:string;title_ar:string;prompt_en:string;prompt_ar:string;options_en:string[];options_ar:string[];answer:number;explanation_en:string;explanation_ar:string};
type Game={key:string;icon:string;title_en:string;title_ar:string;subtitle_en:string;subtitle_ar:string;payload:any};
export default function KidsEditorial({ar,saveProgress}:{ar:boolean;saveProgress:(key:string,score:number)=>Promise<boolean>}){
 const [ageBand,setAgeBand]=useState("6-9");
 const [missions,setMissions]=useState<Mission[]>([]),[mission,setMission]=useState(0),[answer,setAnswer]=useState<number|null>(null),[plate,setPlate]=useState<string[]>([]),[games,setGames]=useState<Game[]>([]),[game,setGame]=useState("plate"),[pick,setPick]=useState<string|null>(null),[multi,setMulti]=useState<string[]>([]);
 useEffect(()=>{fetch("/api/learning-missions").then(r=>r.ok?r.json():null).then(d=>Array.isArray(d?.missions)&&setMissions(d.missions)).catch(()=>{});fetch("/api/learning-games").then(r=>r.ok?r.json():null).then(d=>Array.isArray(d?.games)&&setGames(d.games)).catch(()=>{})},[]);
 const local:Mission={id:"local-carb",title_en:"Carb clue",title_ar:"دليل الكربوهيدرات",prompt_en:"Which one contains carbohydrate?",prompt_ar:"أنهي واحد فيهم فيه كربوهيدرات؟",options_en:["Chicken","Baladi bread","Egg"],options_ar:["فراخ","عيش بلدي","بيضة"],answer:1,explanation_en:"Bread is a grain food and contains carbohydrate.",explanation_ar:"العيش من الحبوب ويحتوي على كربوهيدرات."}; const list=missions.length?missions:[local],m=list[mission%list.length],opts=ar?m.options_ar:m.options_en;
 const fallback:Game[]=[{key:"plate",icon:"🍽️",title_en:"Build My Plate",title_ar:"اعمل وجبتك",subtitle_en:"Build + notice",subtitle_ar:"كوّن واكتشف",payload:{foods:[["🥖","Bread","عيش",true],["🍚","Rice","أرز",true],["🍗","Chicken","فراخ",false],["🥒","Cucumber","خيار",false],["🍊","Orange","برتقال",true],["🥛","Milk","لبن",true]]}},{key:"shop",icon:"🛒",title_en:"Supermarket Hunt",title_ar:"مهمة السوبرماركت",subtitle_en:"Find the label clue",subtitle_ar:"دور على المعلومة",payload:{rows:[["Energy","الطاقة","380 kcal","380 سعر"],["Protein","البروتين","7 g","7 جم"],["Total Carbohydrate","إجمالي الكربوهيدرات","68 g","68 جم"],["Fat","الدهون","8 g","8 جم"]],answer:"Total Carbohydrate"}},{key:"lunch",icon:"🎒",title_en:"Pack My Lunchbox",title_ar:"حضّر شنطتك",subtitle_en:"Pack + discover",subtitle_ar:"اختار واكتشف",payload:{foods:[["🥖","Bread","عيش",true],["🧀","Cheese","جبنة",false],["🥒","Cucumber","خيار",false],["🍌","Banana","موز",true],["🥛","Milk","لبن",true],["🥚","Egg","بيضة",false]]}},{key:"koshari",icon:"🍲",title_en:"Koshari Builder",title_ar:"اعمل طبق كشري",subtitle_en:"Spot the ingredients",subtitle_ar:"اكتشف المكونات",payload:{ingredients:[["🍚","Rice","أرز"],["🍝","Pasta","مكرونة"],["🫘","Lentils","عدس"],["🫛","Chickpeas","حمص"],["🍅","Tomato sauce","صلصة"],["🧅","Onion","بصل"]]}},{key:"portion",icon:"✋",title_en:"Portion Match",title_ar:"تحدي الحصة",subtitle_en:"Match the amount",subtitle_ar:"طابق الكمية",payload:{options_en:["⅓ cup cooked rice","A full koshari plate","Plain chicken"],options_ar:["⅓ كوب أرز مطبوخ","طبق كشري كامل","قطعة فراخ سادة"],answer:0}}];
 const catalog=games.length?games:fallback,g=catalog.find(x=>x.key===game)||catalog[0]; const foods=(g?.payload?.foods||fallback[0].payload.foods) as [string,string,string,boolean][]; const reset=()=>{setPick(null);setMulti([]);if(game!=="plate")setPlate([])};
 const complete=async(key:string,score=1)=>{await saveProgress(key,score)};
 return <div className={styles.page}><section className={styles.hero}><div><p className={styles.kicker}>{ar?"الأطفال · العائلة":"KIDS · FAMILY"}</p><h1>{ar?<>لعقول وأجسام<br/><em>تنمو.</em></>:<>For growing<br/><em>minds & bodies.</em></>}</h1><p>{ar?"العب · اكتشف · جرّب! عالم صغير مليان ألوان ومهمات يساعد الأطفال يفهموا الطعام بفضول ومن غير خوف أو أحكام.":"Play · discover · try! A colorful little world of games and missions that helps kids understand food with curiosity, never fear or judgement."}</p></div><figure><img src="https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=1800" alt=""/></figure></section>
 <section className={styles.ageBand}><div><p className={styles.kicker}>00 · {ar?"اختار المرحلة":"CHOOSE AN AGE BAND"}</p><h2>{ar?"نفس الفكرة، بطريقة تناسب العمر.":"Same idea, different level."}</h2></div><div>{[["4-5","٤–٥"],["6-9","٦–٩"],["10-12","١٠–١٢"],["Family","العائلة"]].map(([en,ara])=><button className={ageBand===en?styles.ageOn:""} key={en} onClick={()=>setAgeBand(en)}>{ar?ara:en}</button>)}</div><p>{ageBand==="4-5"?(ar?"اكتشاف الألوان والأسماء والاختيارات البسيطة مع شخص بالغ.":"Explore colors, names and simple choices with an adult."):ageBand==="6-9"?(ar?"ألعاب ملاحظة وبناء وجبات وفهم بسيط لمجموعات الطعام.":"Observation games, meal building and simple food-group clues."):ageBand==="10-12"?(ar?"قراءة بطاقة الطعام، حصص تقريبية، وفهم أعمق بدون أحكام على الجسم.":"Label reading, approximate portions and deeper understanding without body judgement."):(ar?"العبوا سوا واتكلموا عن الأكل بفضول، من غير مكافأة أو عقاب بالطعام.":"Play together and talk about food with curiosity, without using food as reward or punishment.")}</p></section><section className={styles.learn}><div className={styles.intro}><p className={styles.kicker}>01 · {ar?"اعرف الطعام":"KNOW YOUR FOOD"}</p><h2>{ar?"الكربوهيدرات موجودة في أماكن كثيرة.":"Carbohydrates live in lots of familiar foods."}</h2></div><div className={styles.groups}>{[[ar?"الحبوب والنشويات":"Grains & starches","🍞",ar?"عيش، أرز، مكرونة، بطاطس":"Bread, rice, pasta, potatoes"],[ar?"الفاكهة":"Fruit","🍊",ar?"الفاكهة الكاملة جزء من الصورة":"Whole fruit is part of the picture"],[ar?"اللبن والزبادي":"Milk & yogurt","🥛",ar?"قد يساهمان بالكربوهيدرات":"They can contribute carbohydrate"],[ar?"البقوليات":"Legumes","🫘",ar?"عدس، فول، حمص":"Lentils, ful, chickpeas"]].map(([t,e,c])=><article key={t}><b>{e}</b><h3>{t}</h3><p>{c}</p></article>)}</div></section>
 <section className={styles.game}><div className={styles.gameCopy}><p className={styles.kicker}>02 · {ar?"عالم الألعاب":"GAME WORLD"}</p><h2>{ar?"اختار لعبتك... وابدأ المغامرة!":"Pick a game... start the adventure!"}</h2><p>{ar?"كل لعبة فيها حاجة جديدة تكتشفها. نجرب ونلاحظ ونسأل — من غير أكل «كويس» أو «وحش».":"Every game has a new clue to discover. Try, notice and ask — no “good” foods or “bad” foods here."}</p></div><div className={styles.gameTabs}>{catalog.map(x=><button key={x.key} className={game===x.key?styles.active:""} onClick={()=>{setGame(x.key);reset()}}><b>{x.icon}</b><span>{ar?x.title_ar:x.title_en}</span><small>{ar?x.subtitle_ar:x.subtitle_en}</small></button>)}</div>
 <div className={styles.builder}>{game==="plate"&&<><div className={styles.foods}>{foods.map(([e,enName,arName])=><button key={enName} onClick={()=>setPlate(p=>p.includes(enName)?p:p.length<6?[...p,enName]:p)}><b>{e}</b><span>{ar?arName:enName}</span></button>)}</div><div className={styles.plate}>{plate.length?plate.map(x=>{const f=foods.find(y=>y[1]===x);return <span key={x}>{f?.[0]}</span>}):<small>{ar?"ابدأ بإضافة طعام":"Add something to begin"}</small>}</div><div className={styles.gameActions}><button onClick={()=>setPlate([])}>{ar?"ابدأ من جديد":"Start again"}</button><button disabled={!plate.length} onClick={()=>complete("plate",plate.length)}>{ar?"احفظ التقدم":"Save progress"}</button></div></>}
 {game==="shop"&&<div className={styles.challenge}><h3>{ar?"أي سطر يخبرك بإجمالي الكربوهيدرات؟":"Which row tells you total carbohydrate?"}</h3>{(g.payload.rows as [string,string,string,string][]).map(r=><button className={pick===r[0]?styles.selected:""} key={r[0]} onClick={async()=>{setPick(r[0]);if(r[0]===g.payload.answer)await complete("shop")}}><span>{ar?r[1]:r[0]}</span><b>{ar?r[3]:r[2]}</b></button>)}{pick&&<p>{pick===g.payload.answer?(ar?"✓ بالضبط — استخدم إجمالي الكربوهيدرات.":"✓ Exactly — use Total Carbohydrate."):(ar?"جرّب سطرًا آخر.":"Try another row.")}</p>}</div>}
 {game==="lunch"&&<div className={styles.challenge}><h3>{ar?"حضّر شنطة فيها اختيارات متنوعة.":"Pack a varied lunchbox."}</h3><div className={styles.foods}>{(g.payload.foods as [string,string,string,boolean][]).map(f=><button className={multi.includes(f[1])?styles.selected:""} key={f[1]} onClick={()=>setMulti(v=>v.includes(f[1])?v.filter(x=>x!==f[1]):[...v,f[1]])}><b>{f[0]}</b><span>{ar?f[2]:f[1]}</span></button>)}</div><button disabled={multi.length<3} onClick={()=>complete("lunch",multi.length)}>{ar?"شنطتي جاهزة":"Lunchbox ready"}</button></div>}
 {game==="koshari"&&<div className={styles.challenge}><h3>{ar?"اكتشف مكونات طبق الكشري.":"Discover what builds a koshari plate."}</h3><div className={styles.foods}>{(g.payload.ingredients as [string,string,string][]).map(f=><button className={multi.includes(f[1])?styles.selected:""} key={f[1]} onClick={()=>setMulti(v=>v.includes(f[1])?v:[...v,f[1]])}><b>{f[0]}</b><span>{ar?f[2]:f[1]}</span></button>)}</div><button disabled={multi.length<(g.payload.ingredients?.length||1)} onClick={()=>complete("koshari",multi.length)}>{ar?"اكتشفت الطبق":"I found them all"}</button></div>}
 {game==="portion"&&<div className={styles.challenge}><h3>{ar?"أي اختيار يطابق حصة صغيرة من الأرز المطبوخ؟":"Which option matches a small cooked-rice portion?"}</h3>{((ar?g.payload.options_ar:g.payload.options_en) as string[]).map((o,i)=><button className={pick===String(i)?styles.selected:""} key={o} onClick={async()=>{setPick(String(i));if(i===Number(g.payload.answer))await complete("portion")}}>{o}</button>)}{pick!==null&&<p>{Number(pick)===Number(g.payload.answer)?(ar?"✓ إجابة صحيحة.":"✓ That's the match."):(ar?"جرّب مرة أخرى.":"Try again.")}</p>}</div>}</div></section>
 <section className={styles.familyQuest}><div><p className={styles.kicker}>{ar?"مهمة عائلية":"FAMILY QUEST"}</p><h2>{ar?"اسألوا سؤالًا واحدًا على السفرة.":"Ask one question at the table."}</h2><p>{ar?"اختاروا طعامًا مألوفًا واسألوا: من أين يأتي؟ كيف نأكله عادة؟ ما الذي نلاحظه في الطعم أو القوام؟ لا توجد إجابة «صحية» مطلوبة.":"Pick a familiar food and ask: where does it come from, how do we usually eat it, and what do we notice about taste or texture? There is no required “healthy” answer."}</p><button onClick={()=>complete("family-quest",1)}>{ar?"أنجزنا المهمة":"Quest complete"}</button></div><aside><b>{ar?"تقدم بلا عقاب":"PROGRESS WITHOUT PUNISHMENT"}</b><p>{ar?"التقدم هنا يعني الاستكشاف والمشاركة، وليس الأكل المثالي أو إنهاء الطبق.":"Progress here means exploring and participating, not perfect eating or finishing the plate."}</p></aside></section><section className={styles.mission}><figure><img src="https://images.pexels.com/photos/3661350/pexels-photo-3661350.jpeg?auto=compress&cs=tinysrgb&w=1400" alt=""/></figure><div><p className={styles.kicker}>03 · {ar?"تحدي سريع":"QUICK MISSION"}</p><h2>{ar?m.prompt_ar:m.prompt_en}</h2><div className={styles.options}>{opts.map((o,i)=><button className={answer===i?(i===m.answer?styles.correct:styles.wrong):""} key={o} onClick={async()=>{setAnswer(i);if(i===m.answer)await saveProgress(m.id,1)}}>{o}</button>)}</div>{answer!==null&&<p className={styles.explain}>{ar?m.explanation_ar:m.explanation_en}</p>}<button className={styles.next} onClick={()=>{setAnswer(null);setMission(x=>(x+1)%list.length)}}>{ar?"التحدي التالي":"Next mission"} <span>→</span></button></div></section></div>
}