"use client";
import {useEffect,useRef,useState} from "react";
import styles from "./KidsWorld.module.css";

type Zone="garden"|"market"|"kitchen"|"body"|"family";
type Localized={en:string;ar:string};
type Game={id:Zone;icon:string;title:Localized;description:Localized;image:string;guide:string};
type Props={ar:boolean;signedIn:boolean;userId?:string;saveProgress:(key:string,score:number)=>Promise<unknown>};

const games:Game[]=[
{id:"garden",icon:"🌱",title:{en:"Grow with Ilama",ar:"ازرع مع إيلاما"},description:{en:"Plant a magical little garden",ar:"ازرع حديقة صغيرة مليانة مفاجآت"},image:"/kids/ilama.webp",guide:"/kids/ilama.webp"},
{id:"market",icon:"🧺",title:{en:"Food Explorer",ar:"مستكشف الطعام"},description:{en:"Find colorful fruit with Ilamo",ar:"اكتشف الفاكهة مع إيلامو"},image:"/kids/ilamo.webp",guide:"/kids/ilamo.webp"},
{id:"kitchen",icon:"🍽️",title:{en:"Build a Happy Plate",ar:"كوّن طبقك المبهج"},description:{en:"Mix and match your favorite foods",ar:"اختار أكلات متنوعة تحبها"},image:"/kids/ilama.webp",guide:"/kids/ilama.webp"},
{id:"body",icon:"💫",title:{en:"My Amazing Body",ar:"جسمي المدهش"},description:{en:"Move, stretch and explore",ar:"اتحرك والعب واكتشف"},image:"/kids/ilamo.webp",guide:"/kids/ilamo.webp"},
{id:"family",icon:"📖",title:{en:"Story Time",ar:"وقت الحكاية"},description:{en:"A garden tale with Grandpa and Grandma",ar:"حكاية الحديقة مع جدو وتيتا"},image:"/kids/grandma.webp",guide:"/kids/grandma.webp"}
];
const fruits=[{id:"apple",icon:"🍎",en:"Apple",ar:"تفاح",fruit:true},{id:"book",icon:"📘",en:"Book",ar:"كتاب",fruit:false},{id:"banana",icon:"🍌",en:"Banana",ar:"موز",fruit:true},{id:"ball",icon:"⚽",en:"Ball",ar:"كرة",fruit:false},{id:"strawberry",icon:"🍓",en:"Strawberry",ar:"فراولة",fruit:true},{id:"hat",icon:"🎩",en:"Hat",ar:"قبعة",fruit:false}];
const foods=[{id:"apple",icon:"🍎",en:"Apple",ar:"تفاح"},{id:"carrot",icon:"🥕",en:"Carrot",ar:"جزر"},{id:"bread",icon:"🍞",en:"Bread",ar:"عيش"},{id:"egg",icon:"🥚",en:"Egg",ar:"بيض"},{id:"tomato",icon:"🍅",en:"Tomato",ar:"طماطم"},{id:"cheese",icon:"🧀",en:"Cheese",ar:"جبنة"}];
const family=[{id:"ilamo",image:"/kids/ilamo.webp",en:"Ilamo",ar:"إيلامو",enAbout:"The curious explorer",arAbout:"المستكشف الفضولي"},{id:"ilama",image:"/kids/ilama.webp",en:"Ilama",ar:"إيلاما",enAbout:"The creative adventurer",arAbout:"المغامرة المبدعة"},{id:"grandpa",image:"/kids/grandpa.webp",en:"Grandpa Ilama",ar:"جدو إيلاما",enAbout:"Stories from the garden",arAbout:"حكايات من الحديقة"},{id:"grandma",image:"/kids/grandma.webp",en:"Grandma Ilama",ar:"تيتا إيلاما",enAbout:"Warm stories to share",arAbout:"حكايات دافية بنحكيها سوا"}];
const discoveries=[{icon:"🍎",en:"Discover Foods",ar:"اكتشف الأطعمة"},{icon:"👀",en:"Explore Your Senses",ar:"اكتشف حواسك"},{icon:"🌻",en:"Grow Together",ar:"نزرع سوا"},{icon:"💃",en:"Move & Play",ar:"اتحرك والعب"},{icon:"📚",en:"Enjoy Stories",ar:"استمتع بالحكايات"},{icon:"💚",en:"Build Happy Habits",ar:"عادات مبهجة"}];
const discoveryNotes:Record<Zone,Localized>={
garden:{en:"A tiny seed needs water, light and time to grow.",ar:"البذرة الصغيرة محتاجة مياه ونور ووقت عشان تكبر."},
market:{en:"Fruit comes in many colors, shapes and flavors!",ar:"الفاكهة ليها ألوان وأشكال وطعم مختلف!"},
kitchen:{en:"Trying a variety of foods helps us explore new flavors.",ar:"تنويع الأكل بيساعدنا نكتشف طعم جديد."},
body:{en:"Gentle movement and rest both help us feel good.",ar:"الحركة الهادية والراحة الاتنين مهمين لراحتنا."},
family:{en:"Caring for something together can make a lovely story.",ar:"لما نهتم بحاجة سوا، بنصنع حكاية جميلة."}
};
const guestStorageKey="ilama-world-stars-v1";

export default function KidsWorld({ar,signedIn,userId,saveProgress}:Props){
const storageKey=signedIn?(userId?"ilama-world-stars-v2:"+userId:"ilama-world-stars-session"):guestStorageKey;
const [zone,setZone]=useState<Zone|null>(null);
const [earned,setEarned]=useState<Zone[]>([]);
const [hydratedKey,setHydratedKey]=useState<string|null>(null);
const [notice,setNotice]=useState("");
const [busy,setBusy]=useState(false);
const [celebrate,setCelebrate]=useState(false);
const [plantedPlots,setPlantedPlots]=useState<number[]>([]);
const [marketFinds,setMarketFinds]=useState<string[]>([]);
const [basket,setBasket]=useState<string[]>([]);
const [movement,setMovement]=useState(0);
const [storyPage,setStoryPage]=useState(0);
const [marketRound,setMarketRound]=useState(0);
const saving=useRef(false);
const adventureRef=useRef<HTMLElement|null>(null);
const label=(v:Localized)=>ar?v.ar:v.en;
const selected=zone?games.find(g=>g.id===zone):undefined;
useEffect(()=>{let cancelled=false;const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),8000);setHydratedKey(null);const restore=async()=>{let stars:Zone[]=[];try{const cached=JSON.parse(localStorage.getItem(storageKey)||"[]");if(Array.isArray(cached))stars=games.map(g=>g.id).filter(id=>cached.includes(id))}catch{}
if(signedIn&&userId){try{const response=await fetch("/api/progress",{cache:"no-store",signal:controller.signal});if(response.ok){const data=await response.json();if(Array.isArray(data.progress))stars=games.map(g=>g.id).filter(id=>data.progress.some((entry:{game_key?:string;completed?:boolean})=>entry.game_key==="world:"+id&&entry.completed===true))}}catch{/* Offline: use account-specific cache */}}
if(!cancelled){setEarned(stars);setHydratedKey(storageKey)}window.clearTimeout(timeout)};void restore();return()=>{cancelled=true;controller.abort();window.clearTimeout(timeout)}},[storageKey,signedIn,userId]);
useEffect(()=>{if(hydratedKey!==storageKey)return;try{localStorage.setItem(storageKey,JSON.stringify(earned))}catch{}},[earned,hydratedKey,storageKey]);
function resetGame(){setPlantedPlots([]);setMarketFinds([]);setMarketRound(v=>v+1);setBasket([]);setMovement(0);setStoryPage(0);setNotice("");setCelebrate(false)}
function openGame(id:Zone){if(saving.current)return;resetGame();setZone(id);window.setTimeout(()=>{adventureRef.current?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});adventureRef.current?.focus({preventScroll:true})},40)}
async function complete(id:Zone){if(saving.current||hydratedKey!==storageKey||earned.includes(id))return;saving.current=true;setBusy(true);setNotice("");try{if(signedIn){const result=await saveProgress("world:"+id,1);if(result===false)throw new Error("Progress save failed")}setEarned(old=>old.includes(id)?old:[...old,id]);setCelebrate(true);setNotice((ar?"برافو! نجمة جديدة في مجموعتك ⭐ ":"Amazing! A new star for your collection ⭐ ")+label(discoveryNotes[id]))}catch{setNotice(ar?"ما قدرناش نحفظ النجمة. جرّب تاني.":"We couldn't save your star. Please try again.")}finally{saving.current=false;setBusy(false)}}
const replay=()=>resetGame();
return <section data-kids-world="true" aria-label={ar?"عالم إيلاما للأطفال":"ILAMA Kids world"} className={styles.world} dir={ar?"rtl":"ltr"} lang={ar?"ar":"en"}>
<div className={styles.sky} aria-hidden="true"><span>🌼</span><span>✨</span><span>🍃</span><span>🌸</span></div>
<nav className={styles.kidsNav} aria-label={ar?"تنقل عالم الأطفال":"Kids world navigation"}><a className={styles.kidsLogo} href="#kids-home"><span>ILAMA</span> <em>Kids</em><span aria-hidden="true"> 🌿</span></a><div className={styles.navLinks}><a href="#kids-home">{ar?"الرئيسية":"Home"}</a><a href="#kids-games">{ar?"الألعاب":"Games"}</a><button type="button" onClick={()=>openGame("market")}>{ar?"أطلس الطعام":"Food Atlas"}</button><button type="button" onClick={()=>openGame("family")}>{ar?"الحكايات":"Stories"}</button><button type="button" onClick={()=>openGame("body")}>{ar?"الأنشطة":"Activities"}</button><a href="#kids-family">{ar?"العيلة":"Our Family"}</a><a href="#kids-parents">{ar?"للأهل":"For Parents"}</a></div><div className={styles.navStars} aria-live="polite">⭐ <strong>{earned.length}/{games.length}</strong><span className={styles.visuallyHidden}>{ar?"نجومك":"Adventure stars"}</span></div></nav>
<header id="kids-home" className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}>{ar?"أهلًا بيك في عالم إيلاما":"WELCOME TO ILAMA KIDS"}</p><h1>{ar?"عجايب صغيرة، اكتشافات كبيرة!":"Little Wonders. Big Discoveries."}</h1><p>{ar?"اكتشف الأكل والطبيعة وجسمك مع إيلامو وإيلاما وجدو وتيتا. كل يوم فيه مغامرة جديدة!":"Explore food, discover your body, and grow with joy — alongside Ilamo, Ilama, Grandpa and Grandma!"}</p><div className={styles.heroActions}><button type="button" onClick={()=>openGame("market")}>{ar?"العب مع إيلامو":"Explore with Ilamo"} <span aria-hidden="true">✦</span></button><button type="button" className={styles.coralButton} onClick={()=>openGame("garden")}>{ar?"العب مع إيلاما":"Explore with Ilama"} <span aria-hidden="true">✿</span></button></div></div><div className={styles.heroArt}><img src="/kids/ilama-family.webp" alt={ar?"إيلامو وإيلاما وجدو وتيتا في حديقة خضراء":"Ilamo, Ilama, Grandpa and Grandma in their garden"}/><span className={styles.heroFlower} aria-hidden="true">🌼</span></div></header>
<section className={styles.discoveryStrip} aria-label={ar?"رحلتنا":"Our discoveries"}>{discoveries.map(item=><div key={item.en}><span aria-hidden="true">{item.icon}</span><strong>{ar?item.ar:item.en}</strong></div>)}</section>
<section className={styles.map} id="kids-games"><p className={styles.eyebrow}>{ar?"العب واكتشف":"FUN GAMES"}</p><h2>{ar?"العب، اتعلم، واكتشف!":"Play, Learn & Explore!"}</h2><p className={styles.sectionLead}>{ar?"خمس مغامرات، كل واحدة فيها حاجة جديدة تعملها مع شخصياتنا.":"Five playful adventures, each with a different way to discover something new."}</p><div className={styles.zones}>{games.map(game=><button type="button" key={game.id} className={styles.zone} onClick={()=>openGame(game.id)} aria-label={label(game.title)+". "+label(game.description)}><div className={styles.zoneArt}><img src={game.image} loading="lazy" alt=""/><span aria-hidden="true">{game.icon}</span></div><span className={styles.zoneTitle}>{label(game.title)} {earned.includes(game.id)?"⭐":""}</span><small>{label(game.description)}</small><span className={styles.enter}>{ar?"العب دلوقتي ←":"Play now →"}</span></button>)}</div></section>
<section className={styles.family} id="kids-family"><p className={styles.eyebrow}>{ar?"أصحابك في كل مغامرة":"MEET OUR FAMILY"}</p><h2>{ar?"اتعرف على عيلتنا":"Meet Our Family"}</h2><p className={styles.sectionLead}>{ar?"أربع شخصيات، عالم واحد مليان حكايات وألوان.":"Four friends, one colorful world of stories and discoveries."}</p><div className={styles.familyGrid}>{family.map(member=><article key={member.id} className={styles.familyMember}><img src={member.image} loading="lazy" alt={ar?member.ar:member.en}/><div><h3>{ar?member.ar:member.en}</h3><p>{ar?member.arAbout:member.enAbout}</p></div></article>)}</div></section>
<section className={styles.adventure} id="kids-adventure" ref={adventureRef} tabIndex={-1} aria-label={ar?"منطقة اللعب":"Interactive play area"}>{selected?<><div className={styles.adventureTop}><button className={styles.back} type="button" onClick={()=>{if(!saving.current){setZone(null);resetGame();document.getElementById("kids-games")?.scrollIntoView({behavior:"smooth"})}}}>{ar?"← رجوع للألعاب":"← Back to games"}</button><span className={styles.progressPill}>⭐ {earned.length}/{games.length}</span></div><div className={styles.game}><div className={styles.gameContent}><p className={styles.eyebrow}>{ar?"مغامرتك مع أصحابك":"YOUR NEXT ADVENTURE"}</p><h2>{label(selected.title)}</h2><div className={styles.guide}><img src={selected.guide} alt=""/><p>{zone==="garden"?(ar?"إيلاما: ساعدني أزرع 3 بذور!":"Ilama: Help me plant three seeds!"):zone==="market"?(ar?"إيلامو: دور معايا على 3 فواكه!":"Ilamo: Can you find three fruits?"):zone==="kitchen"?(ar?"إيلاما: يلا نجهز طبق مليان ألوان!":"Ilama: Let's make a colorful plate!"):zone==="body"?(ar?"إيلامو: مستعد نتحرك سوا؟":"Ilamo: Ready to move with me?"):(ar?"تيتا: تعالى أحكيلك حكاية الحديقة.":"Grandma: Come hear our garden story.")}</p></div>
{zone==="garden"&&<div className={styles.seedGame}><p>{ar?"اضغط على كل بذرة عشان تشوفها تكبر.":"Tap each seed to watch it bloom."}</p><div className={styles.gardenPlots}>{[0,1,2].map(i=><button type="button" key={i} disabled={busy||plantedPlots.includes(i)} aria-label={ar?"البذرة رقم "+(i+1):"Seed "+(i+1)} onClick={()=>setPlantedPlots(old=>old.includes(i)?old:[...old,i])}><span aria-hidden="true">{plantedPlots.includes(i)?"🌻":"🌰"}</span></button>)}</div><p className={styles.gameCounter} aria-live="polite">{plantedPlots.length}/3 {ar?"نباتات":"plants"}</p><button className={styles.rewardButton} type="button" disabled={busy||hydratedKey!==storageKey||plantedPlots.length<3||earned.includes("garden")} onClick={()=>complete("garden")}>{ar?"اجمع نجمة الحديقة ⭐":"Collect your garden star ⭐"}</button></div>}
{zone==="market"&&<div className={styles.marketGame}><p>{ar?"دور على الفاكهة، وسيب الحاجات التانية.":"Find the fruits, not the other objects."}</p><div className={styles.marketShelf}>{[...fruits.slice(marketRound%fruits.length),...fruits.slice(0,marketRound%fruits.length)].map(item=><button type="button" key={item.id} aria-pressed={marketFinds.includes(item.id)} disabled={busy||marketFinds.includes(item.id)} onClick={()=>{if(item.fruit){setMarketFinds(old=>old.includes(item.id)?old:[...old,item.id]);setNotice(ar?"لقيت فاكهة!":"You found a fruit!")}else setNotice(ar?"دي مش فاكهة. جرّب حاجة تانية 🌼":"Not a fruit — try another! 🌼")}}><span aria-hidden="true">{item.icon}</span><small>{ar?item.ar:item.en}</small>{marketFinds.includes(item.id)?" ✓":""}</button>)}</div><p className={styles.gameCounter}>{marketFinds.length}/3 {ar?"فواكه":"fruits"}</p><button className={styles.rewardButton} type="button" disabled={busy||hydratedKey!==storageKey||marketFinds.length<3||earned.includes("market")} onClick={()=>complete("market")}>{ar?"اجمع نجمة السوق ⭐":"Collect your market star ⭐"}</button></div>}
{zone==="kitchen"&&<div className={styles.basketGame}><p>{ar?"اختار 3 أطعمة أو أكتر لطبقك. مفيش أكل وحش هنا!":"Choose at least three foods for your plate. No food is bad here!"}</p><div className={styles.basketItems}>{foods.map(item=><button type="button" key={item.id} aria-pressed={basket.includes(item.id)} disabled={busy} onClick={()=>setBasket(old=>old.includes(item.id)?old.filter(id=>id!==item.id):[...old,item.id])}><span aria-hidden="true">{item.icon}</span><small>{ar?item.ar:item.en}</small></button>)}</div><div className={styles.plate} aria-live="polite">{basket.length?foods.filter(item=>basket.includes(item.id)).map(item=><span key={item.id} aria-label={ar?item.ar:item.en}>{item.icon}</span>):<small>{ar?"طبقك مستني اختياراتك":"Your plate is waiting"}</small>}</div><p className={styles.gameCounter}>{basket.length} {ar?"اختيارات":"choices"}</p><button className={styles.rewardButton} type="button" disabled={busy||hydratedKey!==storageKey||basket.length<3||earned.includes("kitchen")} onClick={()=>complete("kitchen")}>{ar?"اجمع نجمة الطبق ⭐":"Collect your plate star ⭐"}</button></div>}
{zone==="body"&&<div className={styles.bodyGame}><p>{ar?"اتحرك على راحتك. تقدر تعمل الحركات وانت قاعد كمان.":"Move in a way that feels comfortable. You can do these moves while seated, too."}</p><div className={styles.moveFigure} aria-hidden="true">{["🙆","🙋","🧘","🎉"][movement]}</div><div className={styles.progressTrack} role="progressbar" aria-valuenow={movement} aria-valuemin={0} aria-valuemax={3} aria-label={ar?"تقدم الحركة":"Movement progress"}><span style={{width:(movement/3*100)+"%"}}/></div><button className={styles.rewardButton} type="button" disabled={busy||movement===3} onClick={()=>setMovement(v=>Math.min(3,v+1))}>{[ar?"ارفع إيديك برفق 🙌":"Reach up gently 🙌",ar?"حرّك كتافك 🌸":"Roll your shoulders 🌸",ar?"خد نفس هادي 🌿":"Take a gentle breath 🌿"][movement]||(ar?"خلصت الحركات!":"All moves done!")}</button><button className={styles.rewardButton} type="button" disabled={busy||hydratedKey!==storageKey||movement<3||earned.includes("body")} onClick={()=>complete("body")}>{ar?"اجمع نجمة الحركة ⭐":"Collect your movement star ⭐"}</button></div>}
{zone==="family"&&<div className={styles.storyGame}><p>{[ar?"تيتا لقت بذرة صغيرة في الحديقة.":"Grandma found a tiny seed in the garden.",ar?"جدو ساعدها تزرعها وتسقيها.":"Grandpa helped plant and water it.",ar?"إيلامو وإيلاما شافوا أول ورقة خضراء!":"Ilamo and Ilama spotted the first green leaf!"][storyPage]}</p><figure className={styles.storyIllustration}><img src={["/kids/grandma.webp","/kids/grandpa.webp","/kids/ilama-family.webp"][storyPage]} loading="lazy" alt={ar?["تيتا مع البذرة","جدو يساعد في الحديقة","إيلامو وإيلاما مع أول ورقة خضراء"][storyPage]:["Grandma with the seed","Grandpa caring for the garden","Ilamo and Ilama with the new green leaf"][storyPage]}/><figcaption aria-live="polite">{ar?["البداية: بذرة صغيرة","الاهتمام: مياه وحب","النتيجة: ورقة جديدة"][storyPage]:["Beginning: a tiny seed","Care: water and kindness","Discovery: a new leaf"][storyPage]}</figcaption></figure><div className={styles.storyControls}><button className={styles.secondaryButton} type="button" disabled={storyPage===0||busy} onClick={()=>setStoryPage(v=>Math.max(0,v-1))}>{ar?"السابق":"Previous"}</button>{storyPage<2?<button className={styles.rewardButton} type="button" disabled={busy} onClick={()=>setStoryPage(v=>Math.min(2,v+1))}>{ar?"الصفحة التالية":"Next page"} →</button>:<button className={styles.rewardButton} type="button" disabled={busy||hydratedKey!==storageKey||earned.includes("family")} onClick={()=>complete("family")}>{ar?"نجمة الحكاية ⭐":"Story star ⭐"}</button>}</div><p className={styles.gameCounter}>{storyPage+1}/3 {ar?"صفحات":"pages"}</p></div>}
<div className={styles.gameFeedback} role="status" aria-live="polite">{notice|| (earned.includes(selected.id)?(ar?"نجمتك محفوظة! تقدر تلعب تاني.":"Your star is earned! You can play again."):"")}</div><button type="button" className={styles.replay} disabled={busy} onClick={replay}>{ar?"↻ العب من أول وجديد":"↻ Play again"}</button></div><div className={styles.gameVisual}><img src={selected.image} alt={label(selected.title)}/>{celebrate&&<div className={styles.confetti} aria-hidden="true">{["⭐","🌸","✨","🎉","🌼","⭐"].map((icon,i)=><span key={i}>{icon}</span>)}</div>}</div></div></>:<div className={styles.welcome}><img src="/kids/ilamo.webp" loading="lazy" alt=""/><div><h2>{ar?"المغامرة مستنياك!":"Your adventure is waiting!"}</h2><p>{ar?"اختار لعبة من فوق، وإيلامو وإيلاما هيبقوا معاك.":"Choose a game above and explore with Ilamo and Ilama."}</p><a href="#kids-games">{ar?"شوف الألعاب ↑":"See the games ↑"}</a></div><img src="/kids/ilama.webp" loading="lazy" alt=""/></div>}</section>
<section className={styles.parents} id="kids-parents"><div><p className={styles.eyebrow}>{ar?"للأهل":"FOR PARENTS"}</p><h2>{ar?"التعلّم بيكبر باللعب":"Little discoveries grow into healthy habits"}</h2><p>{ar?"الألعاب دي بتشجع الفضول والحركة واكتشاف الأطعمة من غير أحكام أو ضغط. العبوا مع أطفالكم، واحكوا عن الألوان والروائح والطعم.":"Our games encourage curiosity, movement, food exploration and family conversation — without labeling foods as good or bad. Join in, ask questions and celebrate discovery."}</p><small>{ar?"محتوى تعليمي فقط، وليس نصيحة طبية.":"Educational content only, not medical advice."}</small></div><img src="/kids/grandpa.webp" loading="lazy" alt=""/></section>
<footer className={styles.footer}>{ar?"إيلاما كيدز · نكتشف ونكبر سوا 🌿":"ILAMA Kids · Little wonders grow here 🌿"}</footer>
</section>
}