"use client";
import {useEffect,useState} from "react";

type Localized={ar:string;en:string};
type Choice={id:string;label:Localized};
type Step={question:Localized;choices:Choice[];correct:string;explain:Localized;hint:Localized};
type Quest={id:string;icon:string;title:Localized;intro:Localized;steps:Step[];offline:Localized};
const L=(ar:string,en:string):Localized=>({ar,en});
const quests:Quest[]=[
 {id:"seed",icon:"🌱",title:L("سر بذرة جدو","Grandpa's Seed Mystery"),intro:L("ساعد جدو يزرع محصولًا، واكتشف احتياجات النبات.","Help Grandpa grow food and discover what plants need."),steps:[
 {question:L("جدو معاه بذور طماطم. فين نزرعها؟","Grandpa has tomato seeds. Where should we plant them?"),choices:[{id:"soil",label:L("في تربة مناسبة","In suitable soil")},{id:"glass",label:L("على الزجاج","On glass")},{id:"toy",label:L("داخل لعبة بلاستيك","Inside a plastic toy")}],correct:"soil",hint:L("فكر في مكان تقدر الجذور تنمو فيه.","Think of a place where roots can grow."),explain:L("التربة المناسبة بتساعد النبات يثبت جذوره وياخد ماء وعناصر غذائية.","Suitable soil supports roots and provides water and nutrients.")},
 {question:L("التربة بدأت تنشف. إيه اللي يساعد النبتة؟","The soil is drying. What helps the plant?"),choices:[{id:"water",label:L("كمية مناسبة من الماء","A suitable amount of water")},{id:"paint",label:L("نلون الأوراق","Paint the leaves")},{id:"dark",label:L("نخفيها في الظلام دائمًا","Keep it in darkness forever")}],correct:"water",hint:L("النباتات بتحتاج مياه، بس مش بكميات زيادة.","Plants need water, but not too much."),explain:L("كمية الماء المناسبة بتختلف حسب النبات والتربة والجو.","The right amount of water depends on the plant, soil and weather.")},
 {question:L("كبرت الطماطم. نعمل إيه قبل أكلها؟","The tomatoes have grown. What before eating them?"),choices:[{id:"wash",label:L("نغسلها بماء جارٍ صالح للشرب","Rinse with safe running water")},{id:"mud",label:L("ناكلها وعليها تراب","Eat them with soil")},{id:"soap",label:L("نغسلها بالصابون","Wash them with soap")}],correct:"wash",hint:L("الأكل الطازج يحتاج تنظيفًا مناسبًا.","Fresh produce needs suitable cleaning."),explain:L("غسل الخضروات والفاكهة بالماء الجاري يساعد على إزالة الأوساخ؛ لا نستخدم الصابون.","Rinsing produce under running water helps remove dirt; do not use soap.")}],
 offline:L("مع شخص بالغ: ازرع بذرة في أصيص، وراقب نموها وقت ما تحب.","With a grown-up: plant a seed in a pot and observe when convenient.")},
 {id:"fish",icon:"🐟",title:L("رحلة السمكة من النيل للمائدة","Fish: From Nile to Table"),intro:L("استكشف موطن البلطي وكيف نحضر وجبة سمك بأمان.","Explore tilapia's habitat and safe food preparation."),steps:[
 {question:L("البلطي النيلي يعيش عادة فين؟","Where does Nile tilapia usually live?"),choices:[{id:"fresh",label:L("المياه العذبة","Freshwater")},{id:"salt",label:L("مياه البحر المالحة فقط","Only salty seawater")},{id:"sand",label:L("الرمال الجافة","Dry sand")}],correct:"fresh",hint:L("فكر في مياه النيل.","Think of the Nile."),explain:L("البلطي النيلي من أسماك المياه العذبة.","Nile tilapia is a freshwater fish.")},
 {question:L("مين المسؤول عن تجهيز السمك النيّ وطهيه؟","Who should handle and cook raw fish?"),choices:[{id:"adult",label:L("شخص بالغ يستخدم أدوات نظيفة ويطهوه جيدًا","An adult using clean tools and cooking thoroughly")},{id:"child",label:L("الطفل لوحده","A child alone")},{id:"raw",label:L("نقدمه من غير تجهيز","Serve without preparation")}],correct:"adult",hint:L("سلامة الغذاء ومصادر الحرارة تحتاج شخص بالغ.","Food safety and heat need adult supervision."),explain:L("تجهيز السمك النيّ والطهي الآمن من مسؤوليات البالغين، مع تجنب التلوث المتبادل.","Adults should handle raw fish and cook it safely, preventing cross-contamination.")},
 {question:L("هل كل أنواع السمك فيها نفس كمية أوميجا ٣؟","Do all fish species contain the same omega-3 amount?"),choices:[{id:"vary",label:L("لا، الكمية تختلف حسب النوع","No, amounts vary by species")},{id:"same",label:L("نعم، كلها متساوية","Yes, all are identical")},{id:"none",label:L("مفيش أي سمك فيه أوميجا ٣","No fish contains omega-3")}],correct:"vary",hint:L("الأنواع المختلفة ممكن تختلف في العناصر الغذائية.","Different species can have different nutrients."),explain:L("الأسماك ممكن توفر بروتينًا وعناصر غذائية، لكن محتوى أوميجا ٣ وفيتامين د يختلف.","Fish can provide protein and nutrients, but omega-3 and vitamin D levels vary.")}],
 offline:L("مع الأسرة: شوفوا أنواع السمك في السوق، واسألوا عن مصدرها من غير لمس السمك النيّ.","With family: spot fish varieties at a market and ask where they came from; don't touch raw fish.")},
 {id:"egypt",icon:"🗺️",title:L("مغامرة الغذاء عبر مصر","Food Journey Across Egypt"),intro:L("سافر من الدلتا للصعيد والساحل واكتشف الغذاء والطبيعة.","Travel from the Delta to Upper Egypt and the coast."),steps:[
 {question:L("كفر الشيخ معروفة بنشاط إيه؟","Which activity is Kafr El Sheikh known for?"),choices:[{id:"fish",label:L("الاستزراع السمكي","Aquaculture")},{id:"snow",label:L("مزارع الثلج","Snow farms")},{id:"coffee",label:L("غابات البن الاستوائية","Tropical coffee forests")}],correct:"fish",hint:L("فكر في المزارع اللي فيها مياه وأسماك.","Think of farms with water and fish."),explain:L("كفر الشيخ من المحافظات المصرية المعروفة بالاستزراع السمكي.","Kafr El Sheikh is known for aquaculture in Egypt.")},
 {question:L("أي محصول مشهور في واحات مصر وأسوان؟","Which crop is common in Egyptian oases and Aswan?"),choices:[{id:"dates",label:L("التمر","Dates")},{id:"pine",label:L("أناناس استوائي","Tropical pineapples")},{id:"maple",label:L("شراب القيقب","Maple syrup")}],correct:"dates",hint:L("بيطلع من النخيل.","It grows on date palms."),explain:L("النخيل والتمر جزء من الزراعة والتراث في مناطق مصرية عديدة.","Date palms are part of farming and culture in many Egyptian regions.")},
 {question:L("إيه الفرق بين النيل والبحر المتوسط؟","How do the Nile and Mediterranean differ?"),choices:[{id:"water",label:L("النيل مياه عذبة والبحر مياه مالحة","The Nile is freshwater; the sea is saltwater")},{id:"same",label:L("الاتنين مياه مالحة","Both are saltwater")},{id:"dry",label:L("الاتنين من غير مياه","Both have no water")}],correct:"water",hint:L("افتكر البلطي النيلي والسردين.","Remember Nile tilapia and sardines."),explain:L("اختلاف الملوحة بيساعد يحدد أنواع الأسماك والبيئات المناسبة لها.","Different salinity shapes fish habitats and ecosystems.")}],
 offline:L("مع الأسرة: اختاروا محافظة على الخريطة، واتكلموا عن محصول أو أكلة مشهورة فيها.","With family: choose a governorate on a map and discuss a food or crop associated with it.")}
];
const storagePrefix="ilama-quest-passport-v1:";
type Progress=Record<string,number>;
const clean=(x:unknown):Progress=>{if(!x||typeof x!=="object"||Array.isArray(x))return {};const raw=x as Record<string,unknown>;return Object.fromEntries(quests.map(q=>[q.id,Math.min(q.steps.length,Math.max(0,Math.floor(Number(raw[q.id])||0)))]))};
export default function KidsQuestTrail({ar,userId}:{ar:boolean;userId?:string}){
 const [active,setActive]=useState("seed"),[progress,setProgress]=useState<Progress>({}),[loaded,setLoaded]=useState<string|null>(null),[choice,setChoice]=useState<string|null>(null),[showOffline,setShowOffline]=useState(false);
 const key=storagePrefix+(userId||"guest");const t=(v:Localized)=>ar?v.ar:v.en;
 useEffect(()=>{try{setProgress(clean(JSON.parse(localStorage.getItem(key)||"{}")))}catch{setProgress({})}setChoice(null);setLoaded(key)},[key]);
 useEffect(()=>{if(loaded===key)try{localStorage.setItem(key,JSON.stringify(progress))}catch{}},[key,loaded,progress]);
 const quest=quests.find(q=>q.id===active)!;const stepIndex=progress[active]||0;const finished=stepIndex>=quest.steps.length;const step=quest.steps[Math.min(stepIndex,quest.steps.length-1)];
 const select=(id:string)=>setChoice(id);
 const continueStory=()=>{if(choice!==step.correct)return;setProgress(p=>({...p,[active]:Math.max(p[active]||0,stepIndex+1)}));setChoice(null)};
 return <section id="kids-quest-trail" dir={ar?"rtl":"ltr"} aria-label={t(L("مغامرات إيلاما التعليمية","Ilama learning adventures"))} style={{margin:"28px 0",padding:"clamp(14px,3vw,30px)",borderRadius:24,background:"#f1ecf8",color:"#3e3550"}}>
 <h2 style={{fontSize:"clamp(25px,4vw,40px)",margin:"0 0 10px"}}>{t(L("🎒 مغامرات إيلاما","🎒 Ilama's Story Quests"))}</h2>
 <p>{t(L("ثلاث حكايات تفاعلية. اختار مغامرة وامشِ على مهلك، من غير مؤقت أو منافسة.","Three interactive stories. Explore at your own pace, with no timer or competition."))}</p>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(175px,1fr))",gap:10}}>{quests.map(q=><button key={q.id} type="button" onClick={()=>{setActive(q.id);setChoice(null);setShowOffline(false)}} aria-pressed={active===q.id} style={{padding:16,textAlign:ar?"right":"left",borderRadius:16,border:active===q.id?"3px solid #67568a":"1px solid #b6aacd",background:active===q.id?"#e3d9f5":"#fff",cursor:"pointer",fontSize:16}}><span aria-hidden="true">{q.icon}</span> <strong>{t(q.title)}</strong><div style={{fontSize:13,marginTop:6}}>{(progress[q.id]||0)===q.steps.length?t(L("مكتملة 🌟","Discovered 🌟")):t(L("مراحل مكتملة","Steps explored"))+" "+(progress[q.id]||0)+"/"+q.steps.length}</div></button>)}</div>
 <article style={{marginTop:16,padding:"clamp(14px,2vw,24px)",borderRadius:18,background:"#fff"}}>
 <h3 style={{marginTop:0}}>{quest.icon} {t(quest.title)}</h3><p>{t(quest.intro)}</p>
 {finished?<div role="status"><h4>{t(L("أحسنت! خلصت المغامرة 🌿","You explored the whole story 🌿"))}</h4><p>{t(L("تقدر تعيدها أو تكتشف مغامرة تانية في أي وقت.","Revisit this story or explore another whenever you like."))}</p><button type="button" onClick={()=>{setProgress(p=>({...p,[active]:0}));setChoice(null)}}>{t(L("ابدأ الحكاية من الأول","Replay this story"))}</button></div>:<div><p style={{fontWeight:700}}>{t(L("المشهد","Scene"))} {stepIndex+1} / {quest.steps.length}</p><h4 style={{fontSize:20}}>{t(step.question)}</h4><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(185px,1fr))",gap:9}}>{step.choices.map(c=><button type="button" key={c.id} onClick={()=>select(c.id)} disabled={loaded!==key||choice===step.correct} style={{borderRadius:14,padding:15,background:choice===c.id?"#f8edcb":"#f4f7ef",border:"2px solid #a2b8a5",cursor:"pointer",fontSize:16}}>{t(c.label)}</button>)}</div><p role="status" aria-live="polite" style={{minHeight:32}}>{choice===step.correct?t(step.explain):choice?t(step.hint):t(L("كل اختيار فرصة للتعلم. خُد وقتك.","Every choice is a chance to learn. Take your time."))}</p>{choice===step.correct&&<button type="button" onClick={continueStory} style={{padding:"12px 20px",borderRadius:12,background:"#416d52",color:"white",border:0,cursor:"pointer",fontWeight:700}}>{t(L("نكمل الحكاية ←","Continue the story →"))}</button>}<details><summary style={{cursor:"pointer"}}>{t(L("تلميح لطيف","A gentle hint"))}</summary><p>{t(step.hint)}</p></details></div>}
 <div style={{marginTop:15,borderTop:"1px solid #e6e2ef",paddingTop:14}}><button type="button" onClick={()=>setShowOffline(x=>!x)} aria-expanded={showOffline} style={{borderRadius:12,padding:12,background:"#eaf2df",border:"1px solid #90ad80"}}>{t(L("🌳 نشاط اختياري مع الأسرة بعيدًا عن الشاشة","🌳 Optional family activity away from the screen"))}</button>{showOffline&&<p>{t(quest.offline)}</p>}</div>
 </article>
 <p style={{fontSize:13}}>{t(L("جواز المغامرات بيتحفظ على الجهاز فقط. مفيش نقاط مالية أو إعلانات أو عقاب على الغياب.","Story progress is saved only on this device. No financial points, ads or absence penalties."))}</p>
 </section>
}