"use client";
import {useAdventureState} from "./KidsJourney";
import {useEffect,useState} from "react";
import {simulatePlant,type PlantCondition} from "../lib/kids/gameplay";
import styles from './KidsWeatherLab.module.css';
type Question={icon:string;ar:string;en:string;options:{id:string;ar:string;en:string}[];answer:string;whyAr:string;whyEn:string};
const questions:Question[]=[
{icon:"☀️",ar:"تربة النبتة ناشفة. إيه اللي ممكن يساعد؟",en:"The plant's soil is dry. What could help?",options:[{id:"water",ar:"كمية مياه مناسبة 💧",en:"A suitable amount of water 💧"},{id:"dark",ar:"ظلام دائم 🌑",en:"Permanent darkness 🌑"},{id:"paint",ar:"ألوان 🎨",en:"Paint 🎨"}],answer:"water",whyAr:"النباتات بتحتاج مياه، لكن الكمية المناسبة بتختلف حسب النبات والجو.",whyEn:"Plants need water, but the right amount varies by plant and weather."},
{icon:"🌤️",ar:"النبتة في مكان مظلم طول الوقت. إيه اللي ينقصها؟",en:"The plant stays in darkness all the time. What does it need?",options:[{id:"light",ar:"ضوء مناسب ☀️",en:"Suitable light ☀️"},{id:"music",ar:"موسيقى 🎵",en:"Music 🎵"},{id:"sugar",ar:"سكر 🍬",en:"Sugar 🍬"}],answer:"light",whyAr:"معظم النباتات بتستخدم الضوء في البناء الضوئي علشان تصنع غذاءها.",whyEn:"Most plants use light to make their own food through photosynthesis."},
{icon:"🌧️",ar:"مياه كتير متجمعة في الأصيص. نعمل إيه مع شخص كبير؟",en:"Too much water collects in a pot. What can we do with a grown-up?",options:[{id:"drain",ar:"نساعد المياه الزيادة تتصرف",en:"Help excess water drain"},{id:"more",ar:"نزود مياه أكتر",en:"Add more water"},{id:"cover",ar:"نغطي النبات بالكامل",en:"Cover the plant completely"}],answer:"drain",whyAr:"التربة المشبعة بالمياه ممكن تقلل الهواء المتاح للجذور.",whyEn:"Waterlogged soil can reduce air available to roots."}
];
const descriptions:Record<PlantCondition,{ar:string;en:string}>={
 dry:{ar:'التربة في النموذج جافة. جرب كمية مياه مناسبة، ولاحظ التغير. احتياجات النباتات الحقيقية مختلفة.',en:'The toy’s soil is dry. Try a suitable water setting and notice the change. Real plants have different needs.'},
 dark:{ar:'النبتة في النموذج ينقصها الضوء. جرّب تغيير الضوء ولاحظ الفرق.',en:'The toy plant needs light. Try changing the light setting and notice the difference.'},
 flooded:{ar:'المياه متجمعة في النموذج. جرّب فتح التصريف أو تقليل المياه. في الواقع اطلب مساعدة شخص بالغ.',en:'Water collects in the toy. Try allowing drainage or reducing water. Ask a grown-up for help with a real pot.'},
 balanced:{ar:'النبتة في النموذج عندها ضوء ومياه وتصريف مناسب. دي تجربة مبسطة؛ مش جدول ري لنبات حقيقي.',en:'The toy has suitable light, water and drainage. This is a simple experiment, not a watering schedule for a real plant.'}
};
export default function KidsWeatherLab({ar}:{ar:boolean}){
 const [index,setIndex]=useState(0),[feedback,setFeedback]=useState(''),[done,setDone]=useState(false),[family,setFamily]=useState(false),[reduced,setReduced]=useState(false);
 const [water,setWater]=useState(1),[light,setLight]=useState(1),[drain,setDrain]=useState(true),[observed,setObserved]=useState<PlantCondition|null>(null);
 const [weather,setWeather,ready]=useAdventureState<{completed:string[];experiments:number;observations:string[]}>("weather",{completed:[],experiments:0,observations:[]});
 const t=(a:string,b:string)=>ar?a:b,condition=simulatePlant(water,light,drain);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 const choose=(id:string)=>{if(!ready||done)return;const q=questions[index];if(id!==q.answer){setFeedback(t('تجربة جميلة! فكّر في احتياجات النبتة وجرب تاني.','Good exploration! Think about what the plant needs and try again.'));return}
  setWeather(old=>({...old,completed:old.completed.includes(q.answer)?old.completed:[...old.completed,q.answer]}));
  if(index===questions.length-1){setDone(true);setFeedback(t('اكتشفت احتياجات النباتات. خد راحة وقت ما تحب 🌿','You discovered what plants need. Take a break whenever you like 🌿'))}else{setIndex(x=>x+1);setFeedback(t(q.whyAr,q.whyEn))}
 };
 const observe=()=>{if(!ready)return;setObserved(condition);setWeather(old=>({...old,observations:(old.observations||[]).includes(condition)?old.observations:[...(old.observations||[]),condition],experiments:condition==='balanced'?1:old.experiments}))};
 return <section id="kids-weather-lab" dir={ar?'rtl':'ltr'} aria-label={t('معمل النباتات والطقس','Plant and weather science lab')} className={styles.lab}>
 <h2>{t('🌦️ معمل النبات والطقس','🌦️ Plant & Weather Lab')}</h2><p>{t('تجارب علمية صغيرة من غير خوف أو درجات. الاختيارات الغلط جزء من التعلم.','Gentle science experiments. Wrong guesses are part of learning, not a failure.')}</p>
 <div className={styles.card}>{done?<div><h3>{t('🌱 اكتشاف جميل!','🌱 Wonderful discovery!')}</h3><p>{t('مش لازم تكمل لعب. جرب تلاحظ نبات حقيقي مع أسرتك.','No need to keep playing. Try observing a real plant with your family.')}</p><button type="button" onClick={()=>{setIndex(0);setDone(false);setFeedback('')}}>{t('العب تاني لو حابب','Play again if you like')}</button></div>:<><p>{t('التجربة','Experiment')} {index+1} / {questions.length}</p><h3>{questions[index].icon} {t(questions[index].ar,questions[index].en)}</h3><div className={styles.choices}>{questions[index].options.map(c=><button key={c.id} type="button" disabled={!ready} onClick={()=>choose(c.id)}>{t(c.ar,c.en)}</button>)}</div></>}<p role="status" aria-live="polite" className={styles.feedback}>{feedback}</p></div>
 <section className={styles.card} aria-label={t('تجربة نبتة افتراضية','Toy plant experiment')}><h3>{t('🔍 غيّر ولاحظ: نبتة التجربة','🔍 Change and notice: the toy plant')}</h3><p>{t('جرّب إعدادات مختلفة وشوف تأثيرها في النموذج. مفيش اختيار يخسرك أي حاجة، ومش لازم تجمع كل الملاحظات.','Try different settings and see how the model changes. Nothing is lost by experimenting, and there’s no need to collect every observation.')}</p><div className={styles.simulation}>
 <div className={styles.plant} data-state={condition} role="img" aria-label={t('نموذج نبات توضيحي: ','Illustrative plant model: ')+t(descriptions[condition].ar,descriptions[condition].en)}><span className={styles.sky} aria-hidden="true">{light?'☀️':'☁️'}</span><span className={styles.stem}/><span className={styles.pot}/><span className={styles.water}/></div>
 <fieldset className={styles.controls}><legend>{t('إعدادات التجربة','Experiment settings')}</legend><label>{t('المياه','Water')}<input type="range" min={0} max={2} step={1} value={water} aria-valuetext={water===0?t('بلا مياه','No water'):water===1?t('كمية متوسطة','Moderate water'):t('مياه كثيرة','Lots of water')} onChange={e=>{setWater(Number(e.target.value));setObserved(null)}}/></label><label>{t('الضوء','Light')}<input type="range" min={0} max={2} step={1} value={light} aria-valuetext={light===0?t('ظلام','Dark'):light===1?t('ضوء متوسط','Moderate light'):t('ضوء كثير','More light')} onChange={e=>{setLight(Number(e.target.value));setObserved(null)}}/></label><label className={styles.drain}><input type="checkbox" checked={drain} onChange={e=>{setDrain(e.target.checked);setObserved(null)}}/>{t('المياه الزيادة تقدر تتصرف','Excess water can drain')}</label><button type="button" disabled={!ready} onClick={observe}>{t('لاحظ نبتة التجربة','Observe the toy plant')}</button></fieldset></div>
 {observed&&<p role="status" className={styles.observation}>{t(descriptions[observed].ar,descriptions[observed].en)}</p>}<p className={styles.saved}>{t('ملاحظات اكتشفتها: ','Observations explored: ')}{weather.observations?.length||0} / 4</p></section>
 <div className={styles.family}><button type="button" aria-expanded={family} onClick={()=>setFamily(x=>!x)}>{t('👨‍👩‍👧 تجربة اختيارية مع الأسرة','👨‍👩‍👧 Optional family experiment')} {family?'−':'+'}</button>{family&&<p>{t('مع شخص بالغ: ازرعوا بذرة في أصيص، وراقبوا التغيرات وقت ما يناسبكم. اغسلوا إيديكم بعد لمس التربة. مش لازم متابعة يومية.','With a grown-up: plant a seed in a pot and observe changes whenever convenient. Wash hands after handling soil. No daily check-in required.')}</p>}</div>
 <small>{reduced?t('تم احترام إعداد تقليل الحركة.','Reduced-motion preference respected.'):t('مفيش مؤقت، ومفيش عقاب على المحاولات.','No timers or penalties for trying.')}</small></section>;
}
