"use client";
import {useEffect,useState} from "react";
import styles from "./KidsWorld.module.css";
type Props={ar:boolean;signedIn:boolean;saveProgress:(key:string,score:number)=>Promise<unknown>};
type Zone="garden"|"market"|"kitchen"|"family";
const scenes:{id:Zone;emoji:string;en:string;ar:string;descEn:string;descAr:string;img:string}[]=[
{id:"garden",emoji:"🌱",en:"The Wonder Garden",ar:"حديقة العجائب",descEn:"Find the colors growing around us",descAr:"اكتشف ألوان النباتات",img:"/kids/ilama-family.webp"},
{id:"market",emoji:"🧺",en:"The Rainbow Market",ar:"سوق الألوان",descEn:"Help Ilamo fill his basket",descAr:"ساعد إيلامو يملأ السلة",img:"/kids/ilamo.webp"},
{id:"kitchen",emoji:"🍲",en:"Ilama's Kitchen",ar:"مطبخ إيلاما",descEn:"Build a colorful snack",descAr:"حضّر وجبة خفيفة ملونة",img:"/kids/ilama.webp"},
{id:"family",emoji:"📖",en:"Grandma's Story Corner",ar:"ركن حكايات تيتا",descEn:"Explore food stories together",descAr:"اكتشفوا حكايات الطعام سوا",img:"/kids/grandma.webp"}];
const tasks:Record<Zone,{en:string;ar:string;choices:{en:string;ar:string;icon:string;ok:boolean}[]}>={
garden:{en:"Which one grows in a garden?",ar:"مين في دول بيكبر في الحديقة؟",choices:[{en:"Carrot",ar:"جزر",icon:"🥕",ok:true},{en:"Spoon",ar:"معلقة",icon:"🥄",ok:false},{en:"Shoe",ar:"جزمة",icon:"👟",ok:false}]},
market:{en:"Find a colorful fruit for Ilamo!",ar:"اختار فاكهة ملونة لإيلامو!",choices:[{en:"Strawberry",ar:"فراولة",icon:"🍓",ok:true},{en:"Book",ar:"كتاب",icon:"📘",ok:false},{en:"Ball",ar:"كرة",icon:"⚽",ok:false}]},
kitchen:{en:"What could we add to our fruit bowl?",ar:"نضيف إيه لطبق الفاكهة؟",choices:[{en:"Banana",ar:"موز",icon:"🍌",ok:true},{en:"Sock",ar:"شراب",icon:"🧦",ok:false},{en:"Pencil",ar:"قلم",icon:"✏️",ok:false}]},
family:{en:"What can Grandma grow in the garden?",ar:"تيتا ممكن تزرع إيه في الجنينة؟",choices:[{en:"Tomato",ar:"طماطم",icon:"🍅",ok:true},{en:"Clock",ar:"ساعة",icon:"⏰",ok:false},{en:"Chair",ar:"كرسي",icon:"🪑",ok:false}]}};
export default function KidsWorld({ar,signedIn,saveProgress}:Props){
const [hydrated,setHydrated]=useState(false),[celebrate,setCelebrate]=useState(false),[zone,setZone]=useState<Zone|null>(null),[answer,setAnswer]=useState<number|null>(null),[earned,setEarned]=useState<Zone[]>([]),[notice,setNotice]=useState(""),[step,setStep]=useState(0),[busy,setBusy]=useState(false);
useEffect(()=>{setAnswer(null);setNotice("");setStep(0);setCelebrate(false)},[zone]);
useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem("ilama-world-stars-v1")||"[]");if(Array.isArray(raw))setEarned(raw.filter((v):v is Zone=>scenes.some(x=>x.id===v)).slice(0,4))}catch{}finally{setHydrated(true)}},[]);
useEffect(()=>{if(!hydrated)return;try{localStorage.setItem("ilama-world-stars-v1",JSON.stringify(earned))}catch{}},[earned,hydrated]);
const current=zone?scenes.find(x=>x.id===zone):null;
const task=zone?tasks[zone]:null;
const guide=zone==="garden"?"/kids/ilama.webp":zone==="market"?"/kids/ilamo.webp":zone==="kitchen"?"/kids/ilama.webp":"/kids/grandpa.webp";
async function choose(i:number){if(!zone||!task||answer!==null||busy)return;setAnswer(i);if(!task.choices[i].ok)return;setBusy(true);
try{if(signedIn){const result=await saveProgress("world:"+zone,1);if(result===false){setNotice(ar?"تعذر حفظ النجمة، حاول مرة تانية":"Could not save your star. Try again.");return}}
setEarned(old=>old.includes(zone)?old:[...old,zone]);setCelebrate(true);setNotice(ar?"برافو! كسبت نجمة ⭐":"Wonderful! You earned a star ⭐")}catch{setNotice(ar?"تعذر حفظ التقدم":"Could not save progress")}finally{setBusy(false)}}
return <main className={styles.world} dir={ar?"rtl":"ltr"}><div className={styles.sky} aria-hidden="true"><span>☁️</span><span>✨</span><span>☁️</span><span>🌼</span><span>✨</span></div>
<div className={styles.stars} aria-live="polite">⭐ {earned.length} / {scenes.length} <span>{ar?"نجوم المغامرة":"Adventure stars"}</span></div>
<header className={styles.hero}><div className={styles.sparkles} aria-hidden="true">✦ ✧ ✦</div><div className={styles.heroText}><p className={styles.eyebrow}>{ar?"أهلًا بيك في عالمنا":"WELCOME TO OUR WORLD"}</p><h1>{ar?"عالم إيلاما وإيلامو":"Ilama & Ilamo's World"}</h1><p>{ar?"تعال نلعب ونكتشف الطعام والطبيعة مع أصحابنا وجدو وتيتا.":"Come play and discover food and nature with our friends, Grandpa and Grandma."}</p><button onClick={()=>{setZone("garden");document.getElementById("kids-adventure")?.scrollIntoView({behavior:"smooth"})}}>{ar?"ابدأ المغامرة ✨":"Start exploring ✨"}</button></div><img src="/kids/ilama-family.webp" alt={ar?"عائلة إيلاما وإيلامو في الحديقة":"Ilama and Ilamo's family garden"}/></header>
<section className={styles.map} aria-label={ar?"خريطة المغامرات":"Adventure map"}><p className={styles.eyebrow}>{ar?"اختار مكانًا":"PICK A PLACE"}</p><h2>{ar?"هنروح فين النهارده؟":"Where shall we go today?"}</h2><div className={styles.pathway} aria-hidden="true">🌱 · · · 🌼 · · · 🌿 · · · ⭐</div><div className={styles.zones}>{scenes.map((s,i)=><button key={s.id} className={styles.zone} onClick={()=>{setZone(s.id);document.getElementById("kids-adventure")?.scrollIntoView({behavior:"smooth"})}}><img src={s.img} alt=""/><span className={styles.zoneTitle}>{s.emoji} {ar?s.ar:s.en} {earned.includes(s.id)?"⭐":""}</span><small>{ar?s.descAr:s.descEn}</small><span className={styles.enter}>{ar?"ادخل المغامرة ←":"Explore →"}</span><span className={styles.zoneGlow} aria-hidden="true">✦</span></button>)}</div></section>
<section className={styles.family} id="kids-family"><p className={styles.eyebrow}>{ar?"أصحاب المغامرات":"MEET OUR FAMILY"}</p><h2>{ar?"قابل عيلتنا":"Meet Our Family"}</h2><p>{ar?"أربعة أصحاب، وعالم مليان اكتشافات":"Four friends, one world full of wonder"}</p><div className={styles.familyGrid}>{[{img:"/kids/ilamo.webp",en:"Ilamo",ar:"إيلامو",detailEn:"Curious garden explorer",detailAr:"مستكشف الحديقة"},{img:"/kids/ilama.webp",en:"Ilama",ar:"إيلاما",detailEn:"Creative food adventurer",detailAr:"محبة المغامرات"},{img:"/kids/grandpa.webp",en:"Grandpa",ar:"جدو",detailEn:"Garden stories and wisdom",detailAr:"حكايات وخبرة"},{img:"/kids/grandma.webp",en:"Grandma",ar:"تيتا",detailEn:"Warm stories and recipes",detailAr:"حكايات ووصفات"}].map(p=><div className={styles.familyMember} key={p.en}><img src={p.img} alt={ar?p.ar:p.en}/><div><strong>{ar?p.ar:p.en}</strong><small>{ar?p.detailAr:p.detailEn}</small></div></div>)}</div></section><section id="kids-adventure" className={styles.adventure} aria-live="polite">{current&&task?<><button className={styles.back} onClick={()=>setZone(null)}>{ar?"← خريطة العالم":"← World map"}</button><div className={styles.game}><div className={styles.bubbles} aria-hidden="true"><span>✨</span><span>🌸</span><span>⭐</span></div><div><p className={styles.eyebrow}>{ar?"مهمة مع الأصدقاء":"A FRIENDLY QUEST"}</p><h2>{ar?current.ar:current.en}</h2><div className={styles.guide}><img src={guide} alt=""/><p>{ar?task.ar:task.en}</p></div>{celebrate&&<div className={styles.confetti} aria-hidden="true">{["⭐","🌸","✨","🎉","⭐","🌼","✨"].map((item,i)=><span key={i}>{item}</span>)}</div>}<div className={styles.choices}>{task.choices.map((c,i)=><button key={i} disabled={answer!==null||busy} className={answer===i?(c.ok?styles.right:styles.tryAgain):""} onClick={()=>choose(i)} aria-pressed={answer===i}><span>{c.icon}</span>{ar?c.ar:c.en}</button>)}</div>{answer!==null&&<p role="status" className={styles.feedback}>{task.choices[answer].ok?notice:(ar?"قريب! جرب مغامرة تانية، مفيش مشكلة 🌼":"Nice try! Every discovery counts 🌼")}</p>}<button className={styles.again} disabled={busy} onClick={()=>{setAnswer(null);setNotice("");setCelebrate(false);setStep(v=>v+1)}}>{ar?"جولة جديدة":"Another round"}</button><p className={styles.round}>{ar?"الجولة":"Round"} {step+1}</p></div><img src={current.img} alt={ar?current.ar:current.en}/></div></>:<div className={styles.welcome}><img src="/kids/ilamo.webp" alt="Ilamo"/><div><h2>{ar?"إيلامو مستنيك!":"Ilamo is waiting for you!"}</h2><p>{ar?"اختار مكان من خريطة العالم عشان تبدأ اللعب.":"Choose a place on the world map to start playing."}</p></div><img src="/kids/ilama.webp" alt="Ilama"/></div>}</section>
<footer className={styles.footer}>{ar?"نلعب ونتعلم مع بعض، من غير درجات ولا أحكام على الأكل.":"Play and learn together — no food scores or judgment."}</footer>
</main>}
