"use client";
import {useEffect,useState} from "react";
import styles from "./KidsEditorial.module.css";
type Mission={id:string;title_en:string;title_ar:string;prompt_en:string;prompt_ar:string;options_en:string[];options_ar:string[];answer:number;explanation_en:string;explanation_ar:string};
type Game={key:string;icon:string;title_en:string;title_ar:string;subtitle_en:string;subtitle_ar:string;payload:any};
export default function KidsEditorial({ar,saveProgress}:{ar:boolean;saveProgress:(key:string,score:number)=>Promise<boolean>}){
 const [ageBand,setAgeBand]=useState("6-9");
 const [missions,setMissions]=useState<Mission[]>([]),[mission,setMission]=useState(0),[answer,setAnswer]=useState<number|null>(null),[plate,setPlate]=useState<string[]>([]),[games,setGames]=useState<Game[]>([]),[game,setGame]=useState("plate"),[pick,setPick]=useState<string|null>(null),[multi,setMulti]=useState<string[]>([]),[petals,setPetals]=useState(0);
 useEffect(()=>{fetch("/api/learning-missions").then(r=>r.ok?r.json():null).then(d=>Array.isArray(d?.missions)&&setMissions(d.missions)).catch(()=>{});fetch("/api/learning-games").then(r=>r.ok?r.json():null).then(d=>Array.isArray(d?.games)&&setGames(d.games)).catch(()=>{})},[]);
 const local:Mission={id:"local-carb",title_en:"Carb clue",title_ar:"دليل الكربوهيدرات",prompt_en:"Which one contains carbohydrate?",prompt_ar:"أنهي واحد فيهم فيه كربوهيدرات؟",options_en:["Chicken","Baladi bread","Egg"],options_ar:["فراخ","عيش بلدي","بيضة"],answer:1,explanation_en:"Bread is a grain food and contains carbohydrate.",explanation_ar:"العيش من الحبوب ويحتوي على كربوهيدرات."}; const list=missions.length?missions:[local],m=list[mission%list.length],opts=ar?m.options_ar:m.options_en;
 const fallback:Game[]=[
{key:"detective",icon:"🕵️",title_en:"Food Detective",title_ar:"محقق الطعام",subtitle_en:"Clues + curiosity",subtitle_ar:"دلائل وفضول",payload:{question_en:"I am creamy, cool, made from milk and often eaten with fruit. What am I?",question_ar:"أنا كريمي وبارد، مصنوع من اللبن وغالبًا نأكلني مع الفاكهة. من أنا؟",options:[["Yogurt","زبادي"],["Rice","أرز"],["Carrot","جزر"]],answer:0}},
{key:"taste",icon:"👃",title_en:"Taste Explorer",title_ar:"مستكشف الطعم",subtitle_en:"Look · touch · smell",subtitle_ar:"شوف · المس · شم",payload:{steps:[["👀","Look","شوف"],["✋","Touch","المس"],["👃","Smell","شم"],["👅","Taste if you want","تذوق لو حابب"]]}},
{key:"pair",icon:"🧩",title_en:"Food Pair Match",title_ar:"طابق الطعام",subtitle_en:"Food + where it comes from",subtitle_ar:"الطعام ومصدره",payload:{pairs:[["🥛","Milk","لبن","🐄","Animal / dairy","حيوان / ألبان"],["🍞","Bread","عيش","🌾","Grain","حبوب"],["🍊","Orange","برتقال","🌳","Tree","شجرة"],["🫘","Lentils","عدس","🌱","Plant","نبات"]]}},
{key:"egypt",icon:"🇪🇬",title_en:"Egyptian Food Quest",title_ar:"مغامرة أكل مصر",subtitle_en:"Explore familiar foods",subtitle_ar:"اكتشف أكلنا",payload:{foods:[["🫘","Ful","فول","A familiar bean dish with many family versions.","طبق بقول مألوف وله طرق عائلية كثيرة."],["🥣","Lentil soup","شوربة عدس","Warm, simple and found in many Egyptian homes.","دافئة وبسيطة وموجودة في بيوت مصرية كثيرة."],["🫓","Baladi bread","عيش بلدي","A familiar Egyptian bread made from grain.","عيش مصري مألوف مصنوع من الحبوب."],["🌿","Molokhia","ملوخية","A leafy dish with a very Egyptian story.","طبق ورقي له حكاية مصرية مميزة."]]}} ,{key:"chef",icon:"🧑‍🍳",title_en:"Little Chef",title_ar:"الشيف الصغير",subtitle_en:"Build a simple recipe",subtitle_ar:"كوّن وصفة بسيطة",payload:{kind:"collect",prompt_en:"Build a simple yogurt bowl. Pick ingredients you would like to explore.",prompt_ar:"كوّن طبق زبادي بسيط. اختار مكونات تحب تستكشفها.",items:[["🥛","Yogurt","زبادي"],["🍌","Banana","موز"],["🌾","Oats","شوفان"],["🥜","Nuts","مكسرات"]]}},
{key:"garden",icon:"🌱",title_en:"Grow a Garden",title_ar:"ازرع حديقتك",subtitle_en:"Seed to food",subtitle_ar:"من البذرة للأكل",payload:{kind:"collect",prompt_en:"What could grow in our little food garden?",prompt_ar:"إيه اللي ممكن نزرعه في حديقة أكل صغيرة؟",items:[["🍅","Tomato","طماطم"],["🥒","Cucumber","خيار"],["🌿","Herbs","أعشاب"],["🫘","Beans","فاصوليا"]]}},
{key:"label",icon:"🏷️",title_en:"Label Detective",title_ar:"محقق البطاقة",subtitle_en:"Read, don't judge",subtitle_ar:"اقرأ بدون أحكام",payload:{kind:"collect",prompt_en:"Find useful facts on a food label — facts are clues, not grades.",prompt_ar:"اكتشف معلومات مفيدة في البطاقة — المعلومات دلائل مش درجات.",items:[["📏","Serving size","حجم الحصة"],["🌾","Carbohydrate","كربوهيدرات"],["🥚","Protein","بروتين"],["🧂","Sodium","صوديوم"]]}},
{key:"science",icon:"🧪",title_en:"Kitchen Science",title_ar:"علوم المطبخ",subtitle_en:"Notice what changes",subtitle_ar:"لاحظ التغيير",payload:{kind:"collect",prompt_en:"Which kitchen changes can we observe?",prompt_ar:"إيه التغييرات اللي نقدر نلاحظها في المطبخ؟",items:[["🔥","Heat","حرارة"],["💧","Water","مياه"],["🌀","Mixing","خلط"],["❄️","Cooling","تبريد"]]}},
{key:"safety",icon:"🧼",title_en:"Food Safety Lab",title_ar:"معمل سلامة الأكل",subtitle_en:"Safer kitchen habits",subtitle_ar:"عادات مطبخ أكثر أمانًا",payload:{kind:"collect",prompt_en:"Pick kitchen habits that help keep food safer.",prompt_ar:"اختار عادات تساعد تخلي الأكل أكثر أمانًا.",items:[["🧼","Wash hands","اغسل إيديك"],["🧊","Keep cold food cold","خلي البارد بارد"],["🔪","Separate raw foods","افصل الأكل النيء"],["♨️","Cook thoroughly","اطبخ كويس"]]}},
{key:"water",icon:"💧",title_en:"Hydration Hero",title_ar:"بطل المياه",subtitle_en:"Spot drink moments",subtitle_ar:"اكتشف أوقات الشرب",payload:{kind:"collect",prompt_en:"When might a drink break feel useful?",prompt_ar:"إمتى ممكن وقفة شرب تكون مفيدة؟",items:[["☀️","Hot day","يوم حر"],["⚽","After active play","بعد اللعب"],["🎒","School day","يوم مدرسة"],["🚗","Long trip","مشوار طويل"]]}},
{key:"rainbow",icon:"🌈",title_en:"Colour Explorer",title_ar:"مستكشف الألوان",subtitle_en:"Explore variety",subtitle_ar:"استكشف التنوع",payload:{kind:"collect",prompt_en:"Collect different food colours — variety is the mission, perfection isn't.",prompt_ar:"اجمع ألوان أكل مختلفة — المهمة هي التنوع مش الكمال.",items:[["🍅","Red","أحمر"],["🥕","Orange","برتقالي"],["🥬","Green","أخضر"],["🍆","Purple","بنفسجي"]]}},
{key:"farm",icon:"🚜",title_en:"Farm to Fork",title_ar:"من الأرض للسفرة",subtitle_en:"Trace the journey",subtitle_ar:"تتبع الرحلة",payload:{kind:"collect",prompt_en:"Collect the steps a food can travel through.",prompt_ar:"اجمع مراحل ممكن يمر بها الطعام.",items:[["🌱","Grow","يزرع"],["🧺","Harvest","يتجمع"],["🏪","Market","السوق"],["🍽️","Table","السفرة"]]}},
{key:"waste",icon:"♻️",title_en:"Zero-Waste Kitchen",title_ar:"مطبخ أقل هدر",subtitle_en:"Use what you have",subtitle_ar:"استفيد من الموجود",payload:{kind:"collect",prompt_en:"Find ways a family can waste less food.",prompt_ar:"اكتشف طرق تساعد الأسرة تقلل هدر الأكل.",items:[["📋","Plan","خطط"],["🥡","Save leftovers","احفظ البواقي"],["❄️","Freeze extras","جمّد الزيادة"],["🍲","Remix a meal","استخدمها في وجبة جديدة"]]}},
{key:"recipe",icon:"🥣",title_en:"Recipe Rescue",title_ar:"إنقاذ الوصفة",subtitle_en:"Adapt with context",subtitle_ar:"عدّل حسب المتاح",payload:{kind:"collect",prompt_en:"A recipe is flexible. What can help when an ingredient is missing?",prompt_ar:"الوصفة مرنة. إيه اللي يساعد لو مكون مش موجود؟",items:[["🔁","Swap a similar food","بدّل بمكون مشابه"],["📏","Adjust the amount","عدّل الكمية"],["👃","Taste and notice","تذوق ولاحظ"],["👨‍👩‍👧","Ask the family","اسأل الأسرة"]]}},
{key:"picnic",icon:"🧺",title_en:"Picnic Planner",title_ar:"خطط للنزهة",subtitle_en:"Pack for the context",subtitle_ar:"حضّر حسب الموقف",payload:{kind:"collect",prompt_en:"Pack a picnic for a warm day.",prompt_ar:"حضّر نزهة ليوم دافئ.",items:[["💧","Water","مياه"],["🍌","Fruit","فاكهة"],["🥪","Sandwich","ساندوتش"],["🧊","Cool bag","شنطة تبريد"]]}},
{key:"plate",icon:"🍽️",title_en:"Build My Plate",title_ar:"اعمل وجبتك",subtitle_en:"Build + notice",subtitle_ar:"كوّن واكتشف",payload:{foods:[["🥖","Bread","عيش",true],["🍚","Rice","أرز",true],["🍗","Chicken","فراخ",false],["🥒","Cucumber","خيار",false],["🍊","Orange","برتقال",true],["🥛","Milk","لبن",true]]}},{key:"shop",icon:"🛒",title_en:"Supermarket Hunt",title_ar:"مهمة السوبرماركت",subtitle_en:"Find the label clue",subtitle_ar:"دور على المعلومة",payload:{rows:[["Energy","الطاقة","380 kcal","380 سعر"],["Protein","البروتين","7 g","7 جم"],["Total Carbohydrate","إجمالي الكربوهيدرات","68 g","68 جم"],["Fat","الدهون","8 g","8 جم"]],answer:"Total Carbohydrate"}},{key:"lunch",icon:"🎒",title_en:"Pack My Lunchbox",title_ar:"حضّر شنطتك",subtitle_en:"Pack + discover",subtitle_ar:"اختار واكتشف",payload:{foods:[["🥖","Bread","عيش",true],["🧀","Cheese","جبنة",false],["🥒","Cucumber","خيار",false],["🍌","Banana","موز",true],["🥛","Milk","لبن",true],["🥚","Egg","بيضة",false]]}},{key:"koshari",icon:"🍲",title_en:"Koshari Builder",title_ar:"اعمل طبق كشري",subtitle_en:"Spot the ingredients",subtitle_ar:"اكتشف المكونات",payload:{ingredients:[["🍚","Rice","أرز"],["🍝","Pasta","مكرونة"],["🫘","Lentils","عدس"],["🫛","Chickpeas","حمص"],["🍅","Tomato sauce","صلصة"],["🧅","Onion","بصل"]]}},{key:"portion",icon:"✋",title_en:"Portion Match",title_ar:"تحدي الحصة",subtitle_en:"Match the amount",subtitle_ar:"طابق الكمية",payload:{options_en:["⅓ cup cooked rice","A full koshari plate","Plain chicken"],options_ar:["⅓ كوب أرز مطبوخ","طبق كشري كامل","قطعة فراخ سادة"],answer:0}}];
 const catalog=games.length?games:fallback,g=catalog.find(x=>x.key===game)||catalog[0]; const foods=(g?.payload?.foods||fallback[0].payload.foods) as [string,string,string,boolean][]; const reset=()=>{setPick(null);setMulti([]);if(game!=="plate")setPlate([])};
 const complete=async(key:string,score=1)=>{setPetals(v=>v+Math.max(1,score));await saveProgress(key,score)};
 return <div className={styles.page}><section className={styles.hero}><div><p className={styles.kicker}>{ar?"الأطفال · العائلة":"KIDS · FAMILY"}</p><h1>{ar?<>لعقول وأجسام<br/><em>تنمو.</em></>:<>For growing<br/><em>minds & bodies.</em></>}</h1><p>{ar?"العب · اكتشف · جرّب! عالم صغير مليان ألوان ومهمات يساعد الأطفال يفهموا الطعام بفضول ومن غير خوف أو أحكام.":"Play · discover · try! A colorful little world of games and missions that helps kids understand food with curiosity, never fear or judgement."}</p></div><figure><img src="https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=1800" alt=""/></figure></section>
 <section className={styles.ageBand}><div><p className={styles.kicker}>00 · {ar?"اختار المرحلة":"CHOOSE AN AGE BAND"}</p><h2>{ar?"نفس الفكرة، بطريقة تناسب العمر.":"Same idea, different level."}</h2></div><div>{[["4-5","٤–٥"],["6-9","٦–٩"],["10-12","١٠–١٢"],["Family","العائلة"]].map(([en,ara])=><button type="button" className={ageBand===en?styles.ageOn:""} key={en} onClick={()=>setAgeBand(en)}>{ar?ara:en}</button>)}</div><p>{ageBand==="4-5"?(ar?"اكتشاف الألوان والأسماء والاختيارات البسيطة مع شخص بالغ.":"Explore colors, names and simple choices with an adult."):ageBand==="6-9"?(ar?"ألعاب ملاحظة وبناء وجبات وفهم بسيط لمجموعات الطعام.":"Observation games, meal building and simple food-group clues."):ageBand==="10-12"?(ar?"قراءة بطاقة الطعام، حصص تقريبية، وفهم أعمق بدون أحكام على الجسم.":"Label reading, approximate portions and deeper understanding without body judgement."):(ar?"العبوا سوا واتكلموا عن الأكل بفضول، من غير مكافأة أو عقاب بالطعام.":"Play together and talk about food with curiosity, without using food as reward or punishment.")}</p></section><section className={styles.learn}><div className={styles.intro}><p className={styles.kicker}>01 · {ar?"اعرف الطعام":"KNOW YOUR FOOD"}</p><h2>{ar?"الكربوهيدرات موجودة في أماكن كثيرة.":"Carbohydrates live in lots of familiar foods."}</h2></div><div className={styles.groups}>{[[ar?"الحبوب والنشويات":"Grains & starches","🍞",ar?"عيش، أرز، مكرونة، بطاطس":"Bread, rice, pasta, potatoes"],[ar?"الفاكهة":"Fruit","🍊",ar?"الفاكهة الكاملة جزء من الصورة":"Whole fruit is part of the picture"],[ar?"اللبن والزبادي":"Milk & yogurt","🥛",ar?"قد يساهمان بالكربوهيدرات":"They can contribute carbohydrate"],[ar?"البقوليات":"Legumes","🫘",ar?"عدس، فول، حمص":"Lentils, ful, chickpeas"]].map(([t,e,c])=><article key={t}><b>{e}</b><h3>{t}</h3><p>{c}</p></article>)}</div></section>
 <section className={styles.playGarden}><div><p className={styles.kicker}>{ar?"حديقة اللعب":"ILAMA PLAY GARDEN"}</p><h2>{ar?"اكتشف. جرّب. اجمع بتلات الفضول.":"Discover. Try. Collect curiosity petals."}</h2><p>{ar?"البتلات هنا للاكتشاف والمشاركة — مش لإنهاء الطبق، ومفيش أكل كويس أو وحش.":"Petals celebrate exploring and participating — never finishing a plate, and never labeling foods good or bad."}</p></div><div className={styles.petals}><b>{petals}</b><span>{ar?"بتلات فضول":"curiosity petals"}</span></div></section>
 <section className={styles.game}><div className={styles.gameCopy}><p className={styles.kicker}>02 · {ar?"عالم الألعاب":"GAME WORLD"}</p><h2>{ar?"اختار لعبتك... وابدأ المغامرة!":"Pick a game... start the adventure!"}</h2><p>{ar?"كل لعبة فيها حاجة جديدة تكتشفها. نجرب ونلاحظ ونسأل — من غير أكل «كويس» أو «وحش».":"Every game has a new clue to discover. Try, notice and ask — no “good” foods or “bad” foods here."}</p></div><div className={styles.gameTabs}>{catalog.map(x=><button type="button" key={x.key} className={game===x.key?styles.active:""} onClick={()=>{setGame(x.key);reset()}}><b>{x.icon}</b><span>{ar?x.title_ar:x.title_en}</span><small>{ar?x.subtitle_ar:x.subtitle_en}</small></button>)}</div>
 <div className={styles.builder}>{game==="plate"&&<><div className={styles.foods}>{foods.map(([e,enName,arName])=><button type="button" key={enName} onClick={()=>setPlate(p=>p.includes(enName)?p:p.length<6?[...p,enName]:p)}><b>{e}</b><span>{ar?arName:enName}</span></button>)}</div><div className={styles.plate}>{plate.length?plate.map(x=>{const f=foods.find(y=>y[1]===x);return <span key={x}>{f?.[0]}</span>}):<small>{ar?"ابدأ بإضافة طعام":"Add something to begin"}</small>}</div><div className={styles.gameActions}><button type="button" onClick={()=>setPlate([])}>{ar?"ابدأ من جديد":"Start again"}</button><button type="button" disabled={!plate.length} onClick={()=>complete("plate",plate.length)}>{ar?"احفظ التقدم":"Save progress"}</button></div></>}
 {game==="detective"&&<div className={styles.challenge}><h3>{ar?g.payload.question_ar:g.payload.question_en}</h3>{(g.payload.options as [string,string][]).map((o,i)=><button type="button" className={pick===String(i)?styles.selected:""} key={o[0]} onClick={async()=>{setPick(String(i));if(i===g.payload.answer)await complete("detective")}}>{ar?o[1]:o[0]}</button>)}{pick!==null&&<p>{Number(pick)===g.payload.answer?(ar?"✓ حلّيت اللغز! لاحظت الدلائل.":"✓ Mystery solved! You noticed the clues."):(ar?"مش مشكلة — راجع الدلائل وجرب تاني.":"No problem — check the clues and try again.")}</p>}</div>}
 {game==="taste"&&<div className={styles.challenge}><h3>{ar?"اختار خطوات الاستكشاف اللي تحب تعملها. التذوق اختياري.":"Choose the exploration steps you feel ready for. Tasting is optional."}</h3><div className={styles.sensorySteps}>{(g.payload.steps as [string,string,string][]).map(x=><button type="button" className={multi.includes(x[1])?styles.selected:""} key={x[1]} onClick={()=>setMulti(v=>v.includes(x[1])?v.filter(y=>y!==x[1]):[...v,x[1]])}><b>{x[0]}</b><span>{ar?x[2]:x[1]}</span></button>)}</div><button type="button" disabled={!multi.length} onClick={()=>complete("taste",multi.length)}>{ar?"أنهيت استكشافي":"Exploration complete"}</button></div>}
 {game==="pair"&&<div className={styles.challenge}><h3>{ar?"اختار كل طعام واكتشف مصدره.":"Tap each food to discover where it comes from."}</h3><div className={styles.pairGrid}>{(g.payload.pairs as [string,string,string,string,string,string][]).map(x=><button type="button" className={multi.includes(x[1])?styles.selected:""} key={x[1]} onClick={()=>setMulti(v=>v.includes(x[1])?v:[...v,x[1]])}><b>{x[0]} <i>→</i> {multi.includes(x[1])?x[3]:"?"}</b><span>{ar?x[2]:x[1]}</span>{multi.includes(x[1])&&<small>{ar?x[5]:x[4]}</small>}</button>)}</div><button type="button" disabled={multi.length<(g.payload.pairs?.length||1)} onClick={()=>complete("pair",multi.length)}>{ar?"اكتشفت المصادر":"I found the sources"}</button></div>}
 {game==="egypt"&&<div className={styles.challenge}><h3>{ar?"افتح أكلات مصرية مألوفة واجمع حكاياتها.":"Open familiar Egyptian foods and collect their stories."}</h3><div className={styles.egyptGrid}>{(g.payload.foods as [string,string,string,string,string][]).map(x=><button type="button" className={multi.includes(x[1])?styles.selected:""} key={x[1]} onClick={()=>setMulti(v=>v.includes(x[1])?v:[...v,x[1]])}><b>{x[0]}</b><span>{ar?x[2]:x[1]}</span>{multi.includes(x[1])&&<small>{ar?x[4]:x[3]}</small>}</button>)}</div><button type="button" disabled={multi.length<(g.payload.foods?.length||1)} onClick={()=>complete("egypt",multi.length)}>{ar?"أكملت الجولة المصرية":"Egypt quest complete"}</button></div>}
 {g?.payload?.kind==="collect"&&<div className={styles.challenge}><h3>{ar?g.payload.prompt_ar:g.payload.prompt_en}</h3><div className={styles.egyptGrid}>{(g.payload.items as [string,string,string][]).map(x=><button type="button" className={multi.includes(x[1])?styles.selected:""} key={x[1]} onClick={()=>setMulti(v=>v.includes(x[1])?v.filter(y=>y!==x[1]):[...v,x[1]])}><b>{x[0]}</b><span>{ar?x[2]:x[1]}</span></button>)}</div><button type="button" disabled={!multi.length} onClick={()=>complete(g.key,multi.length)}>{ar?"اكتشاف جديد! احفظ البتلات":"New discovery! Save petals"}</button></div>}
 {game==="shop"&&<div className={styles.challenge}><h3>{ar?"أي سطر يخبرك بإجمالي الكربوهيدرات؟":"Which row tells you total carbohydrate?"}</h3>{(g.payload.rows as [string,string,string,string][]).map(r=><button type="button" className={pick===r[0]?styles.selected:""} key={r[0]} onClick={async()=>{setPick(r[0]);if(r[0]===g.payload.answer)await complete("shop")}}><span>{ar?r[1]:r[0]}</span><b>{ar?r[3]:r[2]}</b></button>)}{pick&&<p>{pick===g.payload.answer?(ar?"✓ بالضبط — استخدم إجمالي الكربوهيدرات.":"✓ Exactly — use Total Carbohydrate."):(ar?"جرّب سطرًا آخر.":"Try another row.")}</p>}</div>}
 {game==="lunch"&&<div className={styles.challenge}><h3>{ar?"حضّر شنطة فيها اختيارات متنوعة.":"Pack a varied lunchbox."}</h3><div className={styles.foods}>{(g.payload.foods as [string,string,string,boolean][]).map(f=><button type="button" className={multi.includes(f[1])?styles.selected:""} key={f[1]} onClick={()=>setMulti(v=>v.includes(f[1])?v.filter(x=>x!==f[1]):[...v,f[1]])}><b>{f[0]}</b><span>{ar?f[2]:f[1]}</span></button>)}</div><button type="button" disabled={multi.length<3} onClick={()=>complete("lunch",multi.length)}>{ar?"شنطتي جاهزة":"Lunchbox ready"}</button></div>}
 {game==="koshari"&&<div className={styles.challenge}><h3>{ar?"اكتشف مكونات طبق الكشري.":"Discover what builds a koshari plate."}</h3><div className={styles.foods}>{(g.payload.ingredients as [string,string,string][]).map(f=><button type="button" className={multi.includes(f[1])?styles.selected:""} key={f[1]} onClick={()=>setMulti(v=>v.includes(f[1])?v:[...v,f[1]])}><b>{f[0]}</b><span>{ar?f[2]:f[1]}</span></button>)}</div><button type="button" disabled={multi.length<(g.payload.ingredients?.length||1)} onClick={()=>complete("koshari",multi.length)}>{ar?"اكتشفت الطبق":"I found them all"}</button></div>}
 {game==="portion"&&<div className={styles.challenge}><h3>{ar?"أي اختيار يطابق حصة صغيرة من الأرز المطبوخ؟":"Which option matches a small cooked-rice portion?"}</h3>{((ar?g.payload.options_ar:g.payload.options_en) as string[]).map((o,i)=><button type="button" className={pick===String(i)?styles.selected:""} key={o} onClick={async()=>{setPick(String(i));if(i===Number(g.payload.answer))await complete("portion")}}>{o}</button>)}{pick!==null&&<p>{Number(pick)===Number(g.payload.answer)?(ar?"✓ إجابة صحيحة.":"✓ That's the match."):(ar?"جرّب مرة أخرى.":"Try again.")}</p>}</div>}</div></section>
 <section className={styles.familyQuest}><div><p className={styles.kicker}>{ar?"مهمة عائلية":"FAMILY QUEST"}</p><h2>{ar?"اسألوا سؤالًا واحدًا على السفرة.":"Ask one question at the table."}</h2><p>{ar?"اختاروا طعامًا مألوفًا واسألوا: من أين يأتي؟ كيف نأكله عادة؟ ما الذي نلاحظه في الطعم أو القوام؟ لا توجد إجابة «صحية» مطلوبة.":"Pick a familiar food and ask: where does it come from, how do we usually eat it, and what do we notice about taste or texture? There is no required “healthy” answer."}</p><button type="button" onClick={()=>complete("family-quest",1)}>{ar?"أنجزنا المهمة":"Quest complete"}</button></div><aside><b>{ar?"تقدم بلا عقاب":"PROGRESS WITHOUT PUNISHMENT"}</b><p>{ar?"التقدم هنا يعني الاستكشاف والمشاركة، وليس الأكل المثالي أو إنهاء الطبق.":"Progress here means exploring and participating, not perfect eating or finishing the plate."}</p></aside></section><section className={styles.mission}><figure><img src="https://images.pexels.com/photos/3661350/pexels-photo-3661350.jpeg?auto=compress&cs=tinysrgb&w=1400" alt=""/></figure><div><p className={styles.kicker}>03 · {ar?"تحدي سريع":"QUICK MISSION"}</p><h2>{ar?m.prompt_ar:m.prompt_en}</h2><div className={styles.options}>{opts.map((o,i)=><button type="button" className={answer===i?(i===m.answer?styles.correct:styles.wrong):""} key={o} onClick={async()=>{setAnswer(i);if(i===m.answer)await saveProgress(m.id,1)}}>{o}</button>)}</div>{answer!==null&&<p className={styles.explain}>{ar?m.explanation_ar:m.explanation_en}</p>}<button type="button" className={styles.next} onClick={()=>{setAnswer(null);setMission(x=>(x+1)%list.length)}}>{ar?"التحدي التالي":"Next mission"} <span>→</span></button></div></section></div>
}