"use client";
import {useState} from "react";
import styles from "./MentalHealthNutrition.module.css";
type Props={ar:boolean;go:(v:any)=>void}; type Pair=[string,string];
const topics:Array<{n:string;title:Pair;copy:Pair;notes:Pair[]}>= [
 {n:"01",title:["Mood & appetite","المزاج والشهية"],copy:["Mood can change appetite, meal regularity and the effort food takes. Nutrition support starts by noticing what is happening — not blaming yourself or turning food into a psychiatric treatment.","المزاج ممكن يغيّر الشهية وانتظام الوجبات والمجهود المطلوب للأكل. الدعم الغذائي يبدأ بملاحظة اللي بيحصل، مش بلوم النفس ولا بتحويل الأكل لعلاج نفسي."] as Pair,notes:[["Low or changing appetite","شهية قليلة أو متغيرة"],["Irregular meals","وجبات غير منتظمة"],["Energy to shop, cook and eat","القدرة على الشراء والطبخ والأكل"]] as Pair[]},
 {n:"02",title:["Anxiety, caffeine & the gut","القلق والكافيين والجهاز الهضمي"],copy:["Anxiety can overlap with nausea, gut discomfort and appetite changes. Caffeine and energy drinks can also affect sleep or how some people feel. Context matters more than blanket bans.","القلق ممكن يتداخل مع الغثيان وأعراض الجهاز الهضمي وتغير الشهية. الكافيين ومشروبات الطاقة ممكن يؤثروا على النوم أو الإحساس عند بعض الناس. السياق أهم من المنع العام."] as Pair,notes:[["Coffee / tea / energy drinks","قهوة / شاي / مشروبات طاقة"],["Sleep timing","توقيت النوم"],["GI comfort","راحة الجهاز الهضمي"]] as Pair[]},
 {n:"03",title:["ADHD & eating friction","ADHD وصعوبة روتين الأكل"],copy:["Planning, remembering meals, sensory preferences and medication-related appetite observations can all shape eating. ILAMA can help organise observations; medication decisions stay with the treating clinician.","التخطيط وتذكّر الوجبات والحساسية الحسية وملاحظات الشهية مع الدواء كلها ممكن تؤثر على الأكل. إيلاما يساعد في تنظيم الملاحظات؛ قرارات الدواء تظل مع الطبيب المعالج."] as Pair,notes:[["Routine friction","صعوبة الروتين"],["Sensory-tolerable foods","أطعمة مقبولة حسيًا"],["Questions for the clinician","أسئلة للطبيب"]] as Pair[]},
 {n:"04",title:["Sleep × food × energy","النوم × الأكل × الطاقة"],copy:["Sleep, meal timing, caffeine, appetite and daytime energy interact. A journal can show patterns, but a pattern is not proof that one thing caused another.","النوم وتوقيت الأكل والكافيين والشهية والطاقة خلال اليوم بيتداخلوا مع بعض. اليوميات ممكن تظهر نمط، لكن النمط مش دليل إن حاجة سببت التانية."] as Pair,notes:[["Descriptive patterns","أنماط وصفية"],["Association ≠ cause","الارتباط ≠ السببية"],["Bring useful notes to care","خد الملاحظات المفيدة للزيارة"]] as Pair[]}
];
const gentle:Array<{title:Pair;copy:Pair}>=[
 {title:["No-cook counts","من غير طبخ ينفع"],copy:["Yogurt, fruit, bread, cheese, eggs already prepared, beans or other familiar ready foods can be a workable meal when capacity is low.","الزبادي والفاكهة والعيش والجبنة والبيض الجاهز والفول أو أكل مألوف جاهز ممكن يكون وجبة عملية لما الطاقة قليلة."]},
 {title:["One step at a time","خطوة واحدة كفاية"],copy:["Choose the next doable action: drink something, open something, assemble something. The goal is workable nourishment, not a perfect plate.","اختار الخطوة الممكنة دلوقتي: اشرب حاجة، افتح حاجة، جمّع حاجة. الهدف تغذية قابلة للتنفيذ، مش طبق مثالي."]},
 {title:["Sensory-friendly is valid","المقبول حسيًا له قيمة"],copy:["Texture, smell and temperature can affect what feels possible. A familiar tolerated option is useful information, not a failure.","القوام والرائحة والحرارة ممكن يغيروا المقبول. الاختيار المألوف والمحتمل معلومة مفيدة، مش فشل."]},
 {title:["Ask for practical help","اطلب مساعدة عملية"],copy:["Shopping, preparing one staple, sharing a meal or leaving an easy option visible can reduce the work around eating.","المساعدة في الشراء أو تجهيز أساس للوجبة أو مشاركة الأكل أو ترك اختيار سهل ظاهر ممكن يقلل مجهود الأكل."]}
];
const observe:Array<Pair>=[["Mood","المزاج"],["Appetite","الشهية"],["Meal regularity","انتظام الوجبات"],["Sleep","النوم"],["Energy","الطاقة"],["Caffeine","الكافيين"],["Hydration","السوائل"],["GI comfort","راحة الجهاز الهضمي"],["Medication context","سياق الدواء"],["Free note","ملاحظة حرة"]];
export default function MentalHealthNutrition({ar,go}:Props){const[mode,setMode]=useState<"learn"|"gentle"|"observe">("learn");const t=(p:Pair)=>p[ar?1:0];return <div className={styles.page}>
<section className={styles.hero}><p className={styles.kicker}>FOOD · BODY · MIND · CONTEXT</p><h1>{ar?<>الأكل والصحة النفسية،<br/><em>بدون وعود زائفة.</em></>:<>Food and mental health,<br/><em>without false promises.</em></>}</h1><p>{ar?"الأكل ممكن يدعم الصحة العامة، والمزاج ممكن يغيّر طريقة الأكل. إيلاما يساعدك تفهم العلاقة وتسجل ملاحظات مفيدة — لكنه لا يشخص ولا يستبدل العلاج النفسي أو الدواء.":"Food can support general health, and mental health can change how eating feels. ILAMA helps you understand the relationship and capture useful observations — it does not diagnose or replace mental-health treatment or medication."}</p></section>
<nav className={styles.mode} aria-label={ar?"أقسام التغذية والصحة النفسية":"Mental health nutrition sections"}><button className={mode==="learn"?styles.on:""} onClick={()=>setMode("learn")}>{ar?"افهم":"Understand"}</button><button className={mode==="gentle"?styles.on:""} onClick={()=>setMode("gentle")}>{ar?"الأيام الصعبة":"Gentle Eating"}</button><button className={mode==="observe"?styles.on:""} onClick={()=>setMode("observe")}>{ar?"لاحظ":"Observe"}</button></nav>
{mode==="learn"&&<section className={styles.topics}>{topics.map(x=><article key={x.n}><span>{x.n}</span><div><h2>{t(x.title)}</h2><p>{t(x.copy)}</p></div><ul>{x.notes.map(n=><li key={n[0]}>{t(n)}</li>)}</ul></article>)}</section>}
{mode==="gentle"&&<section className={styles.gentle}><header><p className={styles.kicker}>GENTLE EATING MODE</p><h2>{ar?"لما الأكل نفسه يبقى مجهود.":"When eating itself feels like work."}</h2><p>{ar?"وضع للأيام اللي الاكتئاب أو القلق أو الإرهاق أو صعوبة التنظيم مخليين الطبخ والأكل أصعب. مش دايت، ومش خطة علاج.":"For days when depression, anxiety, fatigue or executive-function friction makes cooking and eating harder. Not a diet and not a treatment plan."}</p></header><div>{gentle.map((x,i)=><article key={x.title[0]}><b>0{i+1}</b><h3>{t(x.title)}</h3><p>{t(x.copy)}</p></article>)}</div><aside><strong>{ar?"«أي حاجة عملية» أفضل من مطاردة الكمال.":"Workable beats perfect."}</strong><p>{ar?"لو صعوبة الأكل شديدة أو مستمرة، أو في فقدان وزن غير مقصود/إغماء/جفاف أو قلق حول اضطراب أكل، الدعم الغذائي وحده مش كفاية ويحتاج تقييمًا مهنيًا.":"If eating difficulty is severe or persistent, or there is unintentional weight loss, fainting, dehydration or concern about an eating disorder, nutrition self-help is not enough and professional assessment is appropriate."}</p></aside></section>}
{mode==="observe"&&<section className={styles.observe}><div><p className={styles.kicker}>MOOD & FOOD JOURNAL</p><h2>{ar?"سجّل، ما تشخّصش.":"Observe, don’t diagnose."}</h2><p>{ar?"ملاحظات اختيارية تساعدك تشوف الصورة وتدخل الزيارة بأسئلة أحسن. إيلاما لا يحولها لدرجة اكتئاب أو قلق، ولا يستنتج إن طعامًا سبب تغيرًا نفسيًا.":"Optional observations can help you see the picture and arrive at care with better questions. ILAMA does not turn them into a depression/anxiety score or infer that a food caused a mental-health change."}</p><button onClick={()=>go("journal")}>{ar?"افتح اليوميات":"Open Journal"} →</button></div><div className={styles.observationList}>{observe.map((x,i)=><p key={x[0]}><span>{String(i+1).padStart(2,"0")}</span>{t(x)}</p>)}</div></section>}
<section className={styles.medication}><div><p className={styles.kicker}>MEDICATION & APPETITE CONTEXT</p><h2>{ar?"سجّل الملاحظة. القرار للطبيب.":"Record the observation. Leave the prescription decision to care."}</h2></div><p>{ar?"لو لاحظت تغيرًا في الشهية أو الغثيان أو جفاف الفم أو النوم أو صعوبة توقيت الوجبات أثناء استخدام دواء نفسي، سجّل ما حدث ومتى، وجهّز سؤالًا للطبيب. إيلاما لا ينصح بإيقاف الدواء أو تغيير الجرعة أو التوقيت.":"If you notice appetite, nausea, dry-mouth, sleep or meal-timing changes while using psychiatric medication, record what happened and when, then prepare a question for your clinician. ILAMA does not advise stopping medication or changing its dose or timing."}</p><div className={styles.actions}><button onClick={()=>go("visit")}>{ar?"جهّز سؤالًا للزيارة":"Prepare a visit question"} →</button><a href="/account">{ar?"افتح Care":"Open Care"} →</a></div></section>
<section className={styles.pattern}><p className={styles.kicker}>EVIDENCE, NOT HYPE</p><h2>{ar?"نمط الأكل مهم. لكنه مش «علاج سحري».":"Dietary patterns matter. They are not a “cure.”"}</h2><p>{ar?"نقدر نشرح أنماطًا غذائية متوازنة مثل النمط المتوسطي، والعلاقة بين جودة الغذاء والصحة العامة، ونناقش gut–brain axis بحذر. لكن لا نحول الميكروبيوم أو البروبيوتك أو أي مكمل لوعد بعلاج الاكتئاب أو القلق أو ADHD.":"We can explain balanced patterns such as Mediterranean-style eating, overall diet quality and the gut–brain axis with appropriate uncertainty. We do not turn the microbiome, probiotics or supplements into promises to treat depression, anxiety or ADHD."}</p></section>
<section className={styles.safety}><strong>{ar?"اضطرابات الأكل تحتاج تصميمًا مختلفًا.":"Eating-disorder-sensitive by design."}</strong><p>{ar?"لا مسابقات وزن أو سعرات، لا صيام أو تقييد كـ«حل»، ولا لغة ذنب حول الطعام. أي قلق حول اضطراب أكل أو تدهور نفسي واضح يُوجّه للرعاية المناسبة بدل coaching غذائي آلي.":"No weight/calorie competitions, fasting or restriction as a “solution,” and no food-guilt language. Concern about an eating disorder or clear mental-health deterioration routes toward appropriate care rather than automated nutrition coaching."}</p></section>
</div>}