import {neon} from "@neondatabase/serverless";
import type {NeonQueryFunction} from "@neondatabase/serverless";
import {currentUser} from "../../../lib/auth/server";
function db(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.ILAMA_BLOOM_DATABASE_URL||process.env.ILAMA_BLOOM_POSTGRES_URL||process.env.NutClueDB_DATABASE_URL||process.env.NutClueDB_POSTGRES_URL;if(!url)throw new Error("Database is not configured");return neon(url)}

async function ensure(sql:NeonQueryFunction<false,false>){await sql`CREATE TABLE IF NOT EXISTS public.game_progress (user_id text NOT NULL, game_key text NOT NULL, completed boolean NOT NULL DEFAULT false, score integer NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (user_id,game_key))`}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{"Cache-Control":"no-store"}});
export async function GET(){try{const u=await currentUser();if(!u)return json({progress:[],error:"Unauthorized"},401);const sql=db();await ensure(sql);const rows=await sql`SELECT game_key,completed,score,updated_at FROM public.game_progress WHERE user_id=${u.id} ORDER BY updated_at DESC`;return json({progress:rows})}catch(error){console.error("progress GET failed",error);return json({error:"Unable to load progress"},500)}}
export async function POST(request:Request){try{const u=await currentUser();if(!u)return json({error:"Unauthorized"},401);const body=await request.json().catch(()=>null);if(!body||typeof body!=="object"||Array.isArray(body))return json({error:"Invalid JSON object"},400);if(typeof body.gameKey!=="string"||body.gameKey.length>60||!/^[-a-zA-Z0-9:_]+$/.test(body.gameKey)||typeof body.score!=="number"||typeof body.completed!=="boolean")return json({error:"Invalid progress fields"},400);const gameKey=body.gameKey,rawScore=body.score,completed=body.completed;if(!gameKey)return json({error:"gameKey is required"},400);if(!Number.isFinite(rawScore))return json({error:"score must be a number"},400);const score=Math.max(0,Math.min(10000,Math.round(rawScore)));const sql=db();await ensure(sql);const rows=await sql`INSERT INTO public.game_progress (user_id,game_key,completed,score) VALUES (${u.id},${gameKey},${completed},${score}) ON CONFLICT (user_id,game_key) DO UPDATE SET completed=${completed},score=${score},updated_at=now() RETURNING game_key,completed,score,updated_at`;return json({progress:rows[0]},201)}catch(error){console.error("progress POST failed",error);return json({error:"Unable to save progress"},500)}}
