import {neon} from "@neondatabase/serverless";
import {currentUser} from "../../../lib/auth/server";

function db(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.ILAMA_BLOOM_DATABASE_URL||process.env.ILAMA_BLOOM_POSTGRES_URL||process.env.NutClueDB_DATABASE_URL||process.env.NutClueDB_POSTGRES_URL;if(!url)throw new Error("Database is not configured");return neon(url)}

async function ensure(sql:any){await sql`CREATE TABLE IF NOT EXISTS public.child_profiles (id text PRIMARY KEY DEFAULT md5(random()::text || clock_timestamp()::text), user_id text NOT NULL, nickname text NOT NULL, age_band text NOT NULL, consent_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE UNIQUE INDEX IF NOT EXISTS child_profiles_user_idx ON public.child_profiles (user_id)`}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{"Cache-Control":"no-store"}});
export async function GET(){try{const u=await currentUser();if(!u)return json({profiles:[],error:"Unauthorized"},401);const sql=db();await ensure(sql);const rows=await sql`SELECT id,nickname,age_band,consent_at,created_at,updated_at FROM public.child_profiles WHERE user_id=${u.id} LIMIT 1`;return json({profiles:rows})}catch(error){console.error("child profile GET failed",error);return json({error:"Unable to load profile"},500)}}
export async function POST(request:Request){try{const u=await currentUser();if(!u)return json({error:"Unauthorized"},401);const body=await request.json().catch(()=>null);if(!body||typeof body!=="object"||Array.isArray(body))return json({error:"Invalid JSON object"},400);if(typeof body.nickname!=="string"||body.nickname.length>40||typeof body.ageBand!=="string")return json({error:"Invalid profile fields"},400);const nickname=String(body.nickname||"").trim().slice(0,40),ageBand=String(body.ageBand||"");const allowed=["under-8","8-12","13-17"];if(!nickname||!allowed.includes(ageBand)||body.consent!==true)return json({error:"Nickname, age band and caregiver consent are required"},400);const sql=db();await ensure(sql);const rows=await sql`INSERT INTO public.child_profiles (user_id,nickname,age_band,consent_at) VALUES (${u.id},${nickname},${ageBand},now()) ON CONFLICT (user_id) DO UPDATE SET nickname=${nickname},age_band=${ageBand},consent_at=now(),updated_at=now() RETURNING id,nickname,age_band,consent_at,created_at,updated_at`;return json({profile:rows[0]},201)}catch(error){console.error("child profile POST failed",error);return json({error:"Unable to save profile"},500)}}
export async function DELETE(){try{const u=await currentUser();if(!u)return json({error:"Unauthorized"},401);const sql=db();await ensure(sql);await sql`DELETE FROM public.child_profiles WHERE user_id=${u.id}`;return json({ok:true})}catch(error){console.error("child profile DELETE failed",error);return json({error:"Unable to delete profile"},500)}}
